/*
 * (c) 2011,2012,2013,2017 Renesas Electronics Corporation
 * RENESAS ELECTRONICS CONFIDENTIAL AND PROPRIETARY
 * This program must be used solely for the purpose for which
 * it was furnished by Renesas Electronics Corporation. No part of this
 * program may be reproduced or disclosed to others, in any
 * form, without the prior written permission of Renesas Electronics
 * Corporation.
 */

#include "./config.h"
#include "./regid.h"
#include "./sregfile.h"
#include "./proc_element.h"


void NcSRegFile::InitSRegs (ContextId ctxt_id, ProcElementBase* pe)
{
    switch (pe->GetArchClass()) {
    case E3V5_F:
    // System register group 0
    m_srf[CF_SR_HMEIPC]   = new SRegHMEIPC  (ctxt_id, pe);
    m_srf[CF_SR_HMEIPSW]  = new SRegHMEIPSW (ctxt_id, pe);
    m_srf[CF_SR_HMFEPC]   = new SRegHMFEPC  (ctxt_id, pe);
    m_srf[CF_SR_HMFEPSW]  = new SRegHMFEPSW (ctxt_id, pe);
    m_srf[CF_SR_HMPSW]    = new SRegHMPSW   (ctxt_id, pe);
    m_srf[CF_SR_FPSR]     = new SRegFPSR    (ctxt_id, pe);
    m_srf[CF_SR_FPEPC]    = new SRegFPEPC   (ctxt_id, pe);
    m_srf[CF_SR_FPST]     = new SRegFPST    (ctxt_id, pe);
    m_srf[CF_SR_FPCC]     = new SRegFPCC    (ctxt_id, pe);
    m_srf[CF_SR_FPCFG]    = new SRegFPCFG   (ctxt_id, pe);
    m_srf[CF_SR_FPEC]     = new SRegFPEC    (ctxt_id, pe);
    m_srf[CF_SR_HMEIIC]   = new SRegHMEIIC  (ctxt_id, pe);
    m_srf[CF_SR_HMFEIC]   = new SRegHMFEIC  (ctxt_id, pe);
    m_srf[CF_SR_PSWH]     = new SRegPSWH    (ctxt_id, pe);
    m_srf[CF_SR_CTPC]     = new SRegCTPC    (ctxt_id, pe);
    m_srf[CF_SR_CTPSW]    = new SRegCTPSW   (ctxt_id, pe);
    m_srf[CF_SR_EIPSWH]   = new SRegEIPSWH  (ctxt_id, pe);
    m_srf[CF_SR_FEPSWH]   = new SRegFEPSWH  (ctxt_id, pe);
    m_srf[CF_SR_CTBP]     = new SRegCTBP    (ctxt_id, pe);
    m_srf[CF_SR_SNZCFG]   = new SRegSNZCFG  (ctxt_id, pe);
    m_srf[CF_SR_HMEIWR]   = new SRegHMEIWR  (ctxt_id, pe);
    m_srf[CF_SR_HMFEWR]   = new SRegHMFEWR  (ctxt_id, pe);
    // System register group 1
    m_srf[CF_SR_HMSPID]   = new SRegHMSPID  (ctxt_id, pe);
    m_srf[CF_SR_HMSPIDLIST] = new SRegHMSPIDLIST (ctxt_id, pe);
    m_srf[CF_SR_RBASE]    = new SRegRBASE   (ctxt_id, pe);
    m_srf[CF_SR_HMEBASE]  = new SRegHMEBASE (ctxt_id, pe);
    m_srf[CF_SR_HMINTBP]  = new SRegHMINTBP (ctxt_id, pe);
    m_srf[CF_SR_MCTL]     = new SRegMCTL    (ctxt_id, pe);
    m_srf[CF_SR_PID]      = new SRegPID     (ctxt_id, pe);
    m_srf[CF_SR_FPIPR]    = new SRegFPIPR   (ctxt_id, pe);
    m_srf[CF_SR_HMSVLOCK] = new SRegHMSVLOCK (ctxt_id, pe);
    m_srf[CF_SR_SCCFG]    = new SRegSCCFG   (ctxt_id, pe);
    m_srf[CF_SR_SCBP]     = new SRegSCBP    (ctxt_id, pe);
    m_srf[CF_SR_HVCFG]    = new SRegHVCFG   (ctxt_id, pe);
    m_srf[CF_SR_GMCFG]    = new SRegGMCFG   (ctxt_id, pe);
    m_srf[CF_SR_HVSB]     = new SRegHVSB    (ctxt_id, pe);
    // System register group 2
    m_srf[CF_SR_HMPEID]   = new SRegHMPEID  (ctxt_id, pe);
    m_srf[CF_SR_BMID]     = new SRegBMID    (ctxt_id, pe);
    m_srf[CF_SR_HMMEA]    = new SRegHMMEA   (ctxt_id, pe);
    m_srf[CF_SR_HMMEI]    = new SRegHMMEI   (ctxt_id, pe);
    m_srf[CF_SR_ISPR]     = new SRegISPR    (ctxt_id, pe);
    m_srf[CF_SR_IMSR]     = new SRegIMSR    (ctxt_id, pe);
    m_srf[CF_SR_ICSR]     = new SRegICSR    (ctxt_id, pe);
    m_srf[CF_SR_HMINTCFG] = new SRegHMINTCFG (ctxt_id, pe);
    m_srf[CF_SR_HMPLMR]   = new SRegHMPLMR  (ctxt_id, pe);
    m_srf[CF_SR_RBCR0]    = new SRegRBCR0   (ctxt_id, pe);
    m_srf[CF_SR_RBCR1]    = new SRegRBCR1   (ctxt_id, pe);
    m_srf[CF_SR_RBNR]     = new SRegRBNR    (ctxt_id, pe);
    m_srf[CF_SR_RBIP]     = new SRegRBIP    (ctxt_id, pe);
    // System register group 3
    m_srf[CF_SR_DBGEN]    = new SRegDBGEN   (ctxt_id, pe);
    m_srf[CF_SR_DBPSWH]   = new SRegDBPSWH  (ctxt_id, pe);
    m_srf[CF_SR_DBIC]     = new SRegDBIC    (ctxt_id, pe);
    m_srf[CF_SR_DBPC]     = new SRegDBPC    (ctxt_id, pe);
    m_srf[CF_SR_DBPSW]    = new SRegDBPSW   (ctxt_id, pe);
    m_srf[CF_SR_DIR0]     = new SRegDIR0    (ctxt_id, pe);
    m_srf[CF_SR_DIR1]     = new SRegDIR1    (ctxt_id, pe);
    m_srf[CF_SR_BPC]      = new SRegBPC     (ctxt_id, pe);
    m_srf[CF_SR_BPAV]     = new SRegBPAV    (ctxt_id, pe);
    m_srf[CF_SR_BPAM]     = new SRegBPAM    (ctxt_id, pe);
    m_srf[CF_SR_DBCFG]    = new SRegDBCFG   (ctxt_id, pe);
    m_srf[CF_SR_DBWR]     = new SRegDBWR    (ctxt_id, pe);
    // System register group 4
    m_srf[CF_SR_ICTAGL]   = new SRegICTAGL  (ctxt_id, pe);
    m_srf[CF_SR_ICTAGH]   = new SRegICTAGH  (ctxt_id, pe);
    m_srf[CF_SR_ICDATL]   = new SRegICDATL  (ctxt_id, pe);
    m_srf[CF_SR_ICDATH]   = new SRegICDATH  (ctxt_id, pe);
    m_srf[CF_SR_ICCTRL]   = new SRegICCTRL  (ctxt_id, pe);
    m_srf[CF_SR_ICCFG]    = new SRegICCFG   (ctxt_id, pe);
    m_srf[CF_SR_ICERR]    = new SRegICERR   (ctxt_id, pe);
    // System register group 5
    m_srf[CF_SR_HMMPM]    = new SRegHMMPM   (ctxt_id, pe);
    m_srf[CF_SR_MPCFG]    = new SRegMPCFG   (ctxt_id, pe);
    m_srf[CF_SR_MCA]      = new SRegMCA     (ctxt_id, pe);
    m_srf[CF_SR_MCS]      = new SRegMCS     (ctxt_id, pe);
    m_srf[CF_SR_MCC]      = new SRegMCC     (ctxt_id, pe);
    m_srf[CF_SR_MCR]      = new SRegMCR     (ctxt_id, pe);
    m_srf[CF_SR_MCI]      = new SRegMCI     (ctxt_id, pe);
    m_srf[CF_SR_MPIDX]    = new SRegMPIDX   (ctxt_id, pe);
    m_srf[CF_SR_MPBK]     = new SRegMPBK    (ctxt_id, pe);
    m_srf[CF_SR_MPLA]     = new SRegMPLA    (ctxt_id, pe);
    m_srf[CF_SR_MPUA]     = new SRegMPUA    (ctxt_id, pe);
    m_srf[CF_SR_MPAT]     = new SRegMPAT    (ctxt_id, pe);
    m_srf[CF_SR_MPID0]    = new SRegMPID    (ctxt_id, pe, 0);
    m_srf[CF_SR_MPID1]    = new SRegMPID    (ctxt_id, pe, 1);
    m_srf[CF_SR_MPID2]    = new SRegMPID    (ctxt_id, pe, 2);
    m_srf[CF_SR_MPID3]    = new SRegMPID    (ctxt_id, pe, 3);
    m_srf[CF_SR_MPID4]    = new SRegMPID    (ctxt_id, pe, 4);
    m_srf[CF_SR_MPID5]    = new SRegMPID    (ctxt_id, pe, 5);
    m_srf[CF_SR_MPID6]    = new SRegMPID    (ctxt_id, pe, 6);
    m_srf[CF_SR_MPID7]    = new SRegMPID    (ctxt_id, pe, 7);
    // System register group 9
    m_srf[CF_SR_GMEIPC]   = new SRegGMEIPC  (ctxt_id, pe);
    m_srf[CF_SR_GMEIPSW]  = new SRegGMEIPSW (ctxt_id, pe);
    m_srf[CF_SR_GMFEPC]   = new SRegGMFEPC  (ctxt_id, pe);
    m_srf[CF_SR_GMFEPSW]  = new SRegGMFEPSW (ctxt_id, pe);
    m_srf[CF_SR_GMPSW]    = new SRegGMPSW   (ctxt_id, pe);
    m_srf[CF_SR_GMMEA]    = new SRegGMMEA   (ctxt_id, pe);
    m_srf[CF_SR_GMMEI]    = new SRegGMMEI   (ctxt_id, pe);
    m_srf[CF_SR_GMEIIC]   = new SRegGMEIIC  (ctxt_id, pe);
    m_srf[CF_SR_GMFEIC]   = new SRegGMFEIC  (ctxt_id, pe);
    m_srf[CF_SR_GMSPID]   = new SRegGMSPID  (ctxt_id, pe);
    m_srf[CF_SR_GMSPIDLIST] = new SRegGMSPIDLIST (ctxt_id, pe);
    m_srf[CF_SR_GMEBASE]  = new SRegGMEBASE (ctxt_id, pe);
    m_srf[CF_SR_GMINTBP]  = new SRegGMINTBP (ctxt_id, pe);
    m_srf[CF_SR_GMINTCFG] = new SRegGMINTCFG (ctxt_id, pe);
    m_srf[CF_SR_GMPLMR]   = new SRegGMPLMR  (ctxt_id, pe);
    m_srf[CF_SR_GMSVLOCK] = new SRegGMSVLOCK (ctxt_id, pe);
    m_srf[CF_SR_GMMPM]    = new SRegGMMPM   (ctxt_id, pe);
    m_srf[CF_SR_GMEIWR]   = new SRegGMEIWR  (ctxt_id, pe);
    m_srf[CF_SR_GMFEWR]   = new SRegGMFEWR  (ctxt_id, pe);
    m_srf[CF_SR_GMPEID]   = new SRegGMPEID  (ctxt_id, pe);
    // System register group 10
    m_srf[CF_SR_FXSR]     = new SRegFXSR    (ctxt_id, pe);
    m_srf[CF_SR_FXST]     = new SRegFXST    (ctxt_id, pe);
    m_srf[CF_SR_FXINFO]   = new SRegFXINFO  (ctxt_id, pe);
    m_srf[CF_SR_FXCFG]    = new SRegFXCFG   (ctxt_id, pe);
    m_srf[CF_SR_FXXC]     = new SRegFXXC    (ctxt_id, pe);
    m_srf[CF_SR_FXXP]     = new SRegFXXP    (ctxt_id, pe);
    // System register group 11
    m_srf[CF_SR_TSCOUNTL] = new SRegTSCOUNTL (ctxt_id, pe);
    m_srf[CF_SR_TSCOUNTH] = new SRegTSCOUNTH (ctxt_id, pe);
    m_srf[CF_SR_TSCTRL]   = new SRegTSCTRL  (ctxt_id, pe);
    m_srf[CF_SR_PMUMCTRL] = new SRegPMUMCTRL (ctxt_id, pe);
    m_srf[CF_SR_PMGMCTRL] = new SRegPMGMCTRL (ctxt_id, pe);
    m_srf[CF_SR_PMCOUNT0_G4X1X] = new SRegPMCOUNT (ctxt_id, pe, 0);
    m_srf[CF_SR_PMCTRL0_G4X1X] = new SRegPMCTRL  (ctxt_id, pe, 0);
    m_srf[CF_SR_PMCOUNT1_G4X1X] = new SRegPMCOUNT (ctxt_id, pe, 1);
    m_srf[CF_SR_PMCTRL1_G4X1X] = new SRegPMCTRL  (ctxt_id, pe, 1);
    m_srf[CF_SR_PMCOUNT2_G4X1X] = new SRegPMCOUNT (ctxt_id, pe, 2);
    m_srf[CF_SR_PMCTRL2_G4X1X] = new SRegPMCTRL  (ctxt_id, pe, 2);
    m_srf[CF_SR_PMCOUNT3_G4X1X] = new SRegPMCOUNT (ctxt_id, pe, 3);
    m_srf[CF_SR_PMCTRL3_G4X1X] = new SRegPMCTRL  (ctxt_id, pe, 3);
    // System register group 12
    m_srf[CF_SR_LSTEST0]  = new SRegLSTEST0 (ctxt_id, pe);
    m_srf[CF_SR_LSTEST1]  = new SRegLSTEST1 (ctxt_id, pe);
    m_srf[CF_SR_LSCFG]    = new SRegLSCFG   (ctxt_id, pe);
    m_srf[CF_SR_ICBKEY]   = new SRegICBKEY  (ctxt_id, pe);
    m_srf[CF_SR_IFCR]     = new SRegIFCR    (ctxt_id, pe);
    m_srf[CF_SR_IFCR1]    = new SRegIFCR1   (ctxt_id, pe);
    m_srf[CF_SR_BRPCTRL0] = new SRegBRPCTRL0 (ctxt_id, pe);
    m_srf[CF_SR_BRPCTRL1] = new SRegBRPCTRL1 (ctxt_id, pe);
    m_srf[CF_SR_BRPCFG]   = new SRegBRPCFG  (ctxt_id, pe);
    m_srf[CF_SR_BRPACTRL] = new SRegBRPACTRL (ctxt_id, pe);
    m_srf[CF_SR_BRPDATA]  = new SRegBRPDATA (ctxt_id, pe);
    // System register group 13
    m_srf[CF_SR_DCBKEY]   = new SRegDCBKEY  (ctxt_id, pe);
    m_srf[CF_SR_LSUCR]    = new SRegLSUCR   (ctxt_id, pe);
    m_srf[CF_SR_LSULNK0]  = new SRegLSULNK0 (ctxt_id, pe);
    m_srf[CF_SR_LSULNK1]  = new SRegLSULNK1 (ctxt_id, pe);
    m_srf[CF_SR_L1RLCR]   = new SRegL1RLCR  (ctxt_id, pe);
    m_srf[CF_SR_L1RLNK0]  = new SRegL1RLNK0 (ctxt_id, pe);
    m_srf[CF_SR_L1RLNK1]  = new SRegL1RLNK1 (ctxt_id, pe);
    m_srf[CF_SR_L1RCFG]   = new SRegL1RCFG  (ctxt_id, pe);
    m_srf[CF_SR_DECFG]    = new SRegDECFG   (ctxt_id, pe);
    m_srf[CF_SR_DECTRL]   = new SRegDECTRL  (ctxt_id, pe);
    m_srf[CF_SR_DEVDS]    = new SRegDEVDS   (ctxt_id, pe);
    m_srf[CF_SR_RDBCR]    = new SRegRDBCR   (ctxt_id, pe);
    m_srf[CF_SR_RDBACR]   = new SRegRDBACR  (ctxt_id, pe);
    m_srf[CF_SR_RDBATAG]  = new SRegRDBATAG (ctxt_id, pe);
    m_srf[CF_SR_RDBADAT0] = new SRegRDBADAT0 (ctxt_id, pe);
    m_srf[CF_SR_RDBADAT1] = new SRegRDBADAT1 (ctxt_id, pe);
    m_srf[CF_SR_RDBADAT2] = new SRegRDBADAT2 (ctxt_id, pe);
    m_srf[CF_SR_RDBADAT3] = new SRegRDBADAT3 (ctxt_id, pe);
    m_srf[CF_SR_RDBSTAT]  = new SRegRDBSTAT (ctxt_id, pe);
    // System register group 14
    m_srf[CF_SR_PMCTRL0_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 0);
    m_srf[CF_SR_PMCTRL1_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 1);
    m_srf[CF_SR_PMCTRL2_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 2);
    m_srf[CF_SR_PMCTRL3_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 3);
    m_srf[CF_SR_PMCTRL4_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 4);
    m_srf[CF_SR_PMCTRL5_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 5);
    m_srf[CF_SR_PMCTRL6_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 6);
    m_srf[CF_SR_PMCTRL7_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 7);
    m_srf[CF_SR_PMCOUNT0_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 0);
    m_srf[CF_SR_PMCOUNT1_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 1);
    m_srf[CF_SR_PMCOUNT2_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 2);
    m_srf[CF_SR_PMCOUNT3_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 3);
    m_srf[CF_SR_PMCOUNT4_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 4);
    m_srf[CF_SR_PMCOUNT5_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 5);
    m_srf[CF_SR_PMCOUNT6_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 6);
    m_srf[CF_SR_PMCOUNT7_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 7);
    // System register group 15
    m_srf[CF_SR_PMSUBCND0] = new SRegPMSUBCND (ctxt_id, pe, 0);
    m_srf[CF_SR_PMSUBCND1] = new SRegPMSUBCND (ctxt_id, pe, 1);
    m_srf[CF_SR_PMSUBCND2] = new SRegPMSUBCND (ctxt_id, pe, 2);
    m_srf[CF_SR_PMSUBCND3] = new SRegPMSUBCND (ctxt_id, pe, 3);
    m_srf[CF_SR_PMSUBCND4] = new SRegPMSUBCND (ctxt_id, pe, 4);
    m_srf[CF_SR_PMSUBCND5] = new SRegPMSUBCND (ctxt_id, pe, 5);
    m_srf[CF_SR_PMSUBCND6] = new SRegPMSUBCND (ctxt_id, pe, 6);
    m_srf[CF_SR_PMSUBCND7] = new SRegPMSUBCND (ctxt_id, pe, 7);
    // System register group 32
    m_srf[CF_SR_BPC0]     = new SRegBPC_N   (ctxt_id, pe, 0);
    m_srf[CF_SR_BPC1]     = new SRegBPC_N   (ctxt_id, pe, 1);
    m_srf[CF_SR_BPC2]     = new SRegBPC_N   (ctxt_id, pe, 2);
    m_srf[CF_SR_BPC3]     = new SRegBPC_N   (ctxt_id, pe, 3);
    m_srf[CF_SR_BPC4]     = new SRegBPC_N   (ctxt_id, pe, 4);
    m_srf[CF_SR_BPC5]     = new SRegBPC_N   (ctxt_id, pe, 5);
    m_srf[CF_SR_BPC6]     = new SRegBPC_N   (ctxt_id, pe, 6);
    m_srf[CF_SR_BPC7]     = new SRegBPC_N   (ctxt_id, pe, 7);
    m_srf[CF_SR_BPC8]     = new SRegBPC_N   (ctxt_id, pe, 8);
    m_srf[CF_SR_BPC9]     = new SRegBPC_N   (ctxt_id, pe, 9);
    m_srf[CF_SR_BPC10]    = new SRegBPC_N   (ctxt_id, pe, 10);
    m_srf[CF_SR_BPC11]    = new SRegBPC_N   (ctxt_id, pe, 11);
    // System register group 33
    m_srf[CF_SR_BPAV0]    = new SRegBPAV_N  (ctxt_id, pe, 0);
    m_srf[CF_SR_BPAV1]    = new SRegBPAV_N  (ctxt_id, pe, 1);
    m_srf[CF_SR_BPAV2]    = new SRegBPAV_N  (ctxt_id, pe, 2);
    m_srf[CF_SR_BPAV3]    = new SRegBPAV_N  (ctxt_id, pe, 3);
    m_srf[CF_SR_BPAV4]    = new SRegBPAV_N  (ctxt_id, pe, 4);
    m_srf[CF_SR_BPAV5]    = new SRegBPAV_N  (ctxt_id, pe, 5);
    m_srf[CF_SR_BPAV6]    = new SRegBPAV_N  (ctxt_id, pe, 6);
    m_srf[CF_SR_BPAV7]    = new SRegBPAV_N  (ctxt_id, pe, 7);
    m_srf[CF_SR_BPAV8]    = new SRegBPAV_N  (ctxt_id, pe, 8);
    m_srf[CF_SR_BPAV9]    = new SRegBPAV_N  (ctxt_id, pe, 9);
    m_srf[CF_SR_BPAV10]   = new SRegBPAV_N  (ctxt_id, pe, 10);
    m_srf[CF_SR_BPAV11]   = new SRegBPAV_N  (ctxt_id, pe, 11);
    // System register group 34
    m_srf[CF_SR_BPAM0]    = new SRegBPAM_N  (ctxt_id, pe, 0);
    m_srf[CF_SR_BPAM1]    = new SRegBPAM_N  (ctxt_id, pe, 1);
    m_srf[CF_SR_BPAM2]    = new SRegBPAM_N  (ctxt_id, pe, 2);
    m_srf[CF_SR_BPAM3]    = new SRegBPAM_N  (ctxt_id, pe, 3);
    m_srf[CF_SR_BPAM4]    = new SRegBPAM_N  (ctxt_id, pe, 4);
    m_srf[CF_SR_BPAM5]    = new SRegBPAM_N  (ctxt_id, pe, 5);
    m_srf[CF_SR_BPAM6]    = new SRegBPAM_N  (ctxt_id, pe, 6);
    m_srf[CF_SR_BPAM7]    = new SRegBPAM_N  (ctxt_id, pe, 7);
    m_srf[CF_SR_BPAM8]    = new SRegBPAM_N  (ctxt_id, pe, 8);
    m_srf[CF_SR_BPAM9]    = new SRegBPAM_N  (ctxt_id, pe, 9);
    m_srf[CF_SR_BPAM10]   = new SRegBPAM_N  (ctxt_id, pe, 10);
    m_srf[CF_SR_BPAM11]   = new SRegBPAM_N  (ctxt_id, pe, 11);
    // System register group 37
    m_srf[CF_SR_MPLA0]    = new SRegMPLA_N  (ctxt_id, pe, 0, 0);
    m_srf[CF_SR_MPLA1]    = new SRegMPLA_N  (ctxt_id, pe, 1, 0);
    m_srf[CF_SR_MPLA2]    = new SRegMPLA_N  (ctxt_id, pe, 2, 0);
    m_srf[CF_SR_MPLA3]    = new SRegMPLA_N  (ctxt_id, pe, 3, 0);
    m_srf[CF_SR_MPLA4]    = new SRegMPLA_N  (ctxt_id, pe, 4, 0);
    m_srf[CF_SR_MPLA5]    = new SRegMPLA_N  (ctxt_id, pe, 5, 0);
    m_srf[CF_SR_MPLA6]    = new SRegMPLA_N  (ctxt_id, pe, 6, 0);
    m_srf[CF_SR_MPLA7]    = new SRegMPLA_N  (ctxt_id, pe, 7, 0);
    m_srf[CF_SR_MPLA8]    = new SRegMPLA_N  (ctxt_id, pe, 8, 0);
    m_srf[CF_SR_MPLA9]    = new SRegMPLA_N  (ctxt_id, pe, 9, 0);
    m_srf[CF_SR_MPLA10]   = new SRegMPLA_N  (ctxt_id, pe, 10, 0);
    m_srf[CF_SR_MPLA11]   = new SRegMPLA_N  (ctxt_id, pe, 11, 0);
    m_srf[CF_SR_MPLA12]   = new SRegMPLA_N  (ctxt_id, pe, 12, 0);
    m_srf[CF_SR_MPLA13]   = new SRegMPLA_N  (ctxt_id, pe, 13, 0);
    m_srf[CF_SR_MPLA14]   = new SRegMPLA_N  (ctxt_id, pe, 14, 0);
    m_srf[CF_SR_MPLA15]   = new SRegMPLA_N  (ctxt_id, pe, 15, 0);
    m_srf[CF_SR_MPLA16]   = new SRegMPLA_N  (ctxt_id, pe, 16, 0);
    m_srf[CF_SR_MPLA17]   = new SRegMPLA_N  (ctxt_id, pe, 17, 0);
    m_srf[CF_SR_MPLA18]   = new SRegMPLA_N  (ctxt_id, pe, 18, 0);
    m_srf[CF_SR_MPLA19]   = new SRegMPLA_N  (ctxt_id, pe, 19, 0);
    m_srf[CF_SR_MPLA20]   = new SRegMPLA_N  (ctxt_id, pe, 20, 0);
    m_srf[CF_SR_MPLA21]   = new SRegMPLA_N  (ctxt_id, pe, 21, 0);
    m_srf[CF_SR_MPLA22]   = new SRegMPLA_N  (ctxt_id, pe, 22, 0);
    m_srf[CF_SR_MPLA23]   = new SRegMPLA_N  (ctxt_id, pe, 23, 0);
    m_srf[CF_SR_MPLA24]   = new SRegMPLA_N  (ctxt_id, pe, 24, 0);
    m_srf[CF_SR_MPLA25]   = new SRegMPLA_N  (ctxt_id, pe, 25, 0);
    m_srf[CF_SR_MPLA26]   = new SRegMPLA_N  (ctxt_id, pe, 26, 0);
    m_srf[CF_SR_MPLA27]   = new SRegMPLA_N  (ctxt_id, pe, 27, 0);
    m_srf[CF_SR_MPLA28]   = new SRegMPLA_N  (ctxt_id, pe, 28, 0);
    m_srf[CF_SR_MPLA29]   = new SRegMPLA_N  (ctxt_id, pe, 29, 0);
    m_srf[CF_SR_MPLA30]   = new SRegMPLA_N  (ctxt_id, pe, 30, 0);
    m_srf[CF_SR_MPLA31]   = new SRegMPLA_N  (ctxt_id, pe, 31, 0);
    // System register group 38
    m_srf[CF_SR_MPUA0]    = new SRegMPUA_N  (ctxt_id, pe, 0, 0);
    m_srf[CF_SR_MPUA1]    = new SRegMPUA_N  (ctxt_id, pe, 1, 0);
    m_srf[CF_SR_MPUA2]    = new SRegMPUA_N  (ctxt_id, pe, 2, 0);
    m_srf[CF_SR_MPUA3]    = new SRegMPUA_N  (ctxt_id, pe, 3, 0);
    m_srf[CF_SR_MPUA4]    = new SRegMPUA_N  (ctxt_id, pe, 4, 0);
    m_srf[CF_SR_MPUA5]    = new SRegMPUA_N  (ctxt_id, pe, 5, 0);
    m_srf[CF_SR_MPUA6]    = new SRegMPUA_N  (ctxt_id, pe, 6, 0);
    m_srf[CF_SR_MPUA7]    = new SRegMPUA_N  (ctxt_id, pe, 7, 0);
    m_srf[CF_SR_MPUA8]    = new SRegMPUA_N  (ctxt_id, pe, 8, 0);
    m_srf[CF_SR_MPUA9]    = new SRegMPUA_N  (ctxt_id, pe, 9, 0);
    m_srf[CF_SR_MPUA10]   = new SRegMPUA_N  (ctxt_id, pe, 10, 0);
    m_srf[CF_SR_MPUA11]   = new SRegMPUA_N  (ctxt_id, pe, 11, 0);
    m_srf[CF_SR_MPUA12]   = new SRegMPUA_N  (ctxt_id, pe, 12, 0);
    m_srf[CF_SR_MPUA13]   = new SRegMPUA_N  (ctxt_id, pe, 13, 0);
    m_srf[CF_SR_MPUA14]   = new SRegMPUA_N  (ctxt_id, pe, 14, 0);
    m_srf[CF_SR_MPUA15]   = new SRegMPUA_N  (ctxt_id, pe, 15, 0);
    m_srf[CF_SR_MPUA16]   = new SRegMPUA_N  (ctxt_id, pe, 16, 0);
    m_srf[CF_SR_MPUA17]   = new SRegMPUA_N  (ctxt_id, pe, 17, 0);
    m_srf[CF_SR_MPUA18]   = new SRegMPUA_N  (ctxt_id, pe, 18, 0);
    m_srf[CF_SR_MPUA19]   = new SRegMPUA_N  (ctxt_id, pe, 19, 0);
    m_srf[CF_SR_MPUA20]   = new SRegMPUA_N  (ctxt_id, pe, 20, 0);
    m_srf[CF_SR_MPUA21]   = new SRegMPUA_N  (ctxt_id, pe, 21, 0);
    m_srf[CF_SR_MPUA22]   = new SRegMPUA_N  (ctxt_id, pe, 22, 0);
    m_srf[CF_SR_MPUA23]   = new SRegMPUA_N  (ctxt_id, pe, 23, 0);
    m_srf[CF_SR_MPUA24]   = new SRegMPUA_N  (ctxt_id, pe, 24, 0);
    m_srf[CF_SR_MPUA25]   = new SRegMPUA_N  (ctxt_id, pe, 25, 0);
    m_srf[CF_SR_MPUA26]   = new SRegMPUA_N  (ctxt_id, pe, 26, 0);
    m_srf[CF_SR_MPUA27]   = new SRegMPUA_N  (ctxt_id, pe, 27, 0);
    m_srf[CF_SR_MPUA28]   = new SRegMPUA_N  (ctxt_id, pe, 28, 0);
    m_srf[CF_SR_MPUA29]   = new SRegMPUA_N  (ctxt_id, pe, 29, 0);
    m_srf[CF_SR_MPUA30]   = new SRegMPUA_N  (ctxt_id, pe, 30, 0);
    m_srf[CF_SR_MPUA31]   = new SRegMPUA_N  (ctxt_id, pe, 31, 0);
    // System register group 39
    m_srf[CF_SR_MPAT0]    = new SRegMPAT_N  (ctxt_id, pe, 0, 0);
    m_srf[CF_SR_MPAT1]    = new SRegMPAT_N  (ctxt_id, pe, 1, 0);
    m_srf[CF_SR_MPAT2]    = new SRegMPAT_N  (ctxt_id, pe, 2, 0);
    m_srf[CF_SR_MPAT3]    = new SRegMPAT_N  (ctxt_id, pe, 3, 0);
    m_srf[CF_SR_MPAT4]    = new SRegMPAT_N  (ctxt_id, pe, 4, 0);
    m_srf[CF_SR_MPAT5]    = new SRegMPAT_N  (ctxt_id, pe, 5, 0);
    m_srf[CF_SR_MPAT6]    = new SRegMPAT_N  (ctxt_id, pe, 6, 0);
    m_srf[CF_SR_MPAT7]    = new SRegMPAT_N  (ctxt_id, pe, 7, 0);
    m_srf[CF_SR_MPAT8]    = new SRegMPAT_N  (ctxt_id, pe, 8, 0);
    m_srf[CF_SR_MPAT9]    = new SRegMPAT_N  (ctxt_id, pe, 9, 0);
    m_srf[CF_SR_MPAT10]   = new SRegMPAT_N  (ctxt_id, pe, 10, 0);
    m_srf[CF_SR_MPAT11]   = new SRegMPAT_N  (ctxt_id, pe, 11, 0);
    m_srf[CF_SR_MPAT12]   = new SRegMPAT_N  (ctxt_id, pe, 12, 0);
    m_srf[CF_SR_MPAT13]   = new SRegMPAT_N  (ctxt_id, pe, 13, 0);
    m_srf[CF_SR_MPAT14]   = new SRegMPAT_N  (ctxt_id, pe, 14, 0);
    m_srf[CF_SR_MPAT15]   = new SRegMPAT_N  (ctxt_id, pe, 15, 0);
    m_srf[CF_SR_MPAT16]   = new SRegMPAT_N  (ctxt_id, pe, 16, 0);
    m_srf[CF_SR_MPAT17]   = new SRegMPAT_N  (ctxt_id, pe, 17, 0);
    m_srf[CF_SR_MPAT18]   = new SRegMPAT_N  (ctxt_id, pe, 18, 0);
    m_srf[CF_SR_MPAT19]   = new SRegMPAT_N  (ctxt_id, pe, 19, 0);
    m_srf[CF_SR_MPAT20]   = new SRegMPAT_N  (ctxt_id, pe, 20, 0);
    m_srf[CF_SR_MPAT21]   = new SRegMPAT_N  (ctxt_id, pe, 21, 0);
    m_srf[CF_SR_MPAT22]   = new SRegMPAT_N  (ctxt_id, pe, 22, 0);
    m_srf[CF_SR_MPAT23]   = new SRegMPAT_N  (ctxt_id, pe, 23, 0);
    m_srf[CF_SR_MPAT24]   = new SRegMPAT_N  (ctxt_id, pe, 24, 0);
    m_srf[CF_SR_MPAT25]   = new SRegMPAT_N  (ctxt_id, pe, 25, 0);
    m_srf[CF_SR_MPAT26]   = new SRegMPAT_N  (ctxt_id, pe, 26, 0);
    m_srf[CF_SR_MPAT27]   = new SRegMPAT_N  (ctxt_id, pe, 27, 0);
    m_srf[CF_SR_MPAT28]   = new SRegMPAT_N  (ctxt_id, pe, 28, 0);
    m_srf[CF_SR_MPAT29]   = new SRegMPAT_N  (ctxt_id, pe, 29, 0);
    m_srf[CF_SR_MPAT30]   = new SRegMPAT_N  (ctxt_id, pe, 30, 0);
    m_srf[CF_SR_MPAT31]   = new SRegMPAT_N  (ctxt_id, pe, 31, 0);
    // System register group 40
    m_srf[CF_SR_MPLA0_B1] = new SRegMPLA_N  (ctxt_id, pe, 0, 1);
    m_srf[CF_SR_MPLA1_B1] = new SRegMPLA_N  (ctxt_id, pe, 1, 1);
    m_srf[CF_SR_MPLA2_B1] = new SRegMPLA_N  (ctxt_id, pe, 2, 1);
    m_srf[CF_SR_MPLA3_B1] = new SRegMPLA_N  (ctxt_id, pe, 3, 1);
    m_srf[CF_SR_MPLA4_B1] = new SRegMPLA_N  (ctxt_id, pe, 4, 1);
    m_srf[CF_SR_MPLA5_B1] = new SRegMPLA_N  (ctxt_id, pe, 5, 1);
    m_srf[CF_SR_MPLA6_B1] = new SRegMPLA_N  (ctxt_id, pe, 6, 1);
    m_srf[CF_SR_MPLA7_B1] = new SRegMPLA_N  (ctxt_id, pe, 7, 1);
    m_srf[CF_SR_MPLA8_B1] = new SRegMPLA_N  (ctxt_id, pe, 8, 1);
    m_srf[CF_SR_MPLA9_B1] = new SRegMPLA_N  (ctxt_id, pe, 9, 1);
    m_srf[CF_SR_MPLA10_B1] = new SRegMPLA_N  (ctxt_id, pe, 10, 1);
    m_srf[CF_SR_MPLA11_B1] = new SRegMPLA_N  (ctxt_id, pe, 11, 1);
    m_srf[CF_SR_MPLA12_B1] = new SRegMPLA_N  (ctxt_id, pe, 12, 1);
    m_srf[CF_SR_MPLA13_B1] = new SRegMPLA_N  (ctxt_id, pe, 13, 1);
    m_srf[CF_SR_MPLA14_B1] = new SRegMPLA_N  (ctxt_id, pe, 14, 1);
    m_srf[CF_SR_MPLA15_B1] = new SRegMPLA_N  (ctxt_id, pe, 15, 1);
    m_srf[CF_SR_MPLA16_B1] = new SRegMPLA_N  (ctxt_id, pe, 16, 1);
    m_srf[CF_SR_MPLA17_B1] = new SRegMPLA_N  (ctxt_id, pe, 17, 1);
    m_srf[CF_SR_MPLA18_B1] = new SRegMPLA_N  (ctxt_id, pe, 18, 1);
    m_srf[CF_SR_MPLA19_B1] = new SRegMPLA_N  (ctxt_id, pe, 19, 1);
    m_srf[CF_SR_MPLA20_B1] = new SRegMPLA_N  (ctxt_id, pe, 20, 1);
    m_srf[CF_SR_MPLA21_B1] = new SRegMPLA_N  (ctxt_id, pe, 21, 1);
    m_srf[CF_SR_MPLA22_B1] = new SRegMPLA_N  (ctxt_id, pe, 22, 1);
    m_srf[CF_SR_MPLA23_B1] = new SRegMPLA_N  (ctxt_id, pe, 23, 1);
    m_srf[CF_SR_MPLA24_B1] = new SRegMPLA_N  (ctxt_id, pe, 24, 1);
    m_srf[CF_SR_MPLA25_B1] = new SRegMPLA_N  (ctxt_id, pe, 25, 1);
    m_srf[CF_SR_MPLA26_B1] = new SRegMPLA_N  (ctxt_id, pe, 26, 1);
    m_srf[CF_SR_MPLA27_B1] = new SRegMPLA_N  (ctxt_id, pe, 27, 1);
    m_srf[CF_SR_MPLA28_B1] = new SRegMPLA_N  (ctxt_id, pe, 28, 1);
    m_srf[CF_SR_MPLA29_B1] = new SRegMPLA_N  (ctxt_id, pe, 29, 1);
    m_srf[CF_SR_MPLA30_B1] = new SRegMPLA_N  (ctxt_id, pe, 30, 1);
    m_srf[CF_SR_MPLA31_B1] = new SRegMPLA_N  (ctxt_id, pe, 31, 1);
    // System register group 41
    m_srf[CF_SR_MPUA0_B1] = new SRegMPUA_N  (ctxt_id, pe, 0, 1);
    m_srf[CF_SR_MPUA1_B1] = new SRegMPUA_N  (ctxt_id, pe, 1, 1);
    m_srf[CF_SR_MPUA2_B1] = new SRegMPUA_N  (ctxt_id, pe, 2, 1);
    m_srf[CF_SR_MPUA3_B1] = new SRegMPUA_N  (ctxt_id, pe, 3, 1);
    m_srf[CF_SR_MPUA4_B1] = new SRegMPUA_N  (ctxt_id, pe, 4, 1);
    m_srf[CF_SR_MPUA5_B1] = new SRegMPUA_N  (ctxt_id, pe, 5, 1);
    m_srf[CF_SR_MPUA6_B1] = new SRegMPUA_N  (ctxt_id, pe, 6, 1);
    m_srf[CF_SR_MPUA7_B1] = new SRegMPUA_N  (ctxt_id, pe, 7, 1);
    m_srf[CF_SR_MPUA8_B1] = new SRegMPUA_N  (ctxt_id, pe, 8, 1);
    m_srf[CF_SR_MPUA9_B1] = new SRegMPUA_N  (ctxt_id, pe, 9, 1);
    m_srf[CF_SR_MPUA10_B1] = new SRegMPUA_N  (ctxt_id, pe, 10, 1);
    m_srf[CF_SR_MPUA11_B1] = new SRegMPUA_N  (ctxt_id, pe, 11, 1);
    m_srf[CF_SR_MPUA12_B1] = new SRegMPUA_N  (ctxt_id, pe, 12, 1);
    m_srf[CF_SR_MPUA13_B1] = new SRegMPUA_N  (ctxt_id, pe, 13, 1);
    m_srf[CF_SR_MPUA14_B1] = new SRegMPUA_N  (ctxt_id, pe, 14, 1);
    m_srf[CF_SR_MPUA15_B1] = new SRegMPUA_N  (ctxt_id, pe, 15, 1);
    m_srf[CF_SR_MPUA16_B1] = new SRegMPUA_N  (ctxt_id, pe, 16, 1);
    m_srf[CF_SR_MPUA17_B1] = new SRegMPUA_N  (ctxt_id, pe, 17, 1);
    m_srf[CF_SR_MPUA18_B1] = new SRegMPUA_N  (ctxt_id, pe, 18, 1);
    m_srf[CF_SR_MPUA19_B1] = new SRegMPUA_N  (ctxt_id, pe, 19, 1);
    m_srf[CF_SR_MPUA20_B1] = new SRegMPUA_N  (ctxt_id, pe, 20, 1);
    m_srf[CF_SR_MPUA21_B1] = new SRegMPUA_N  (ctxt_id, pe, 21, 1);
    m_srf[CF_SR_MPUA22_B1] = new SRegMPUA_N  (ctxt_id, pe, 22, 1);
    m_srf[CF_SR_MPUA23_B1] = new SRegMPUA_N  (ctxt_id, pe, 23, 1);
    m_srf[CF_SR_MPUA24_B1] = new SRegMPUA_N  (ctxt_id, pe, 24, 1);
    m_srf[CF_SR_MPUA25_B1] = new SRegMPUA_N  (ctxt_id, pe, 25, 1);
    m_srf[CF_SR_MPUA26_B1] = new SRegMPUA_N  (ctxt_id, pe, 26, 1);
    m_srf[CF_SR_MPUA27_B1] = new SRegMPUA_N  (ctxt_id, pe, 27, 1);
    m_srf[CF_SR_MPUA28_B1] = new SRegMPUA_N  (ctxt_id, pe, 28, 1);
    m_srf[CF_SR_MPUA29_B1] = new SRegMPUA_N  (ctxt_id, pe, 29, 1);
    m_srf[CF_SR_MPUA30_B1] = new SRegMPUA_N  (ctxt_id, pe, 30, 1);
    m_srf[CF_SR_MPUA31_B1] = new SRegMPUA_N  (ctxt_id, pe, 31, 1);
    // System register group 42
    m_srf[CF_SR_MPAT0_B1] = new SRegMPAT_N  (ctxt_id, pe, 0, 1);
    m_srf[CF_SR_MPAT1_B1] = new SRegMPAT_N  (ctxt_id, pe, 1, 1);
    m_srf[CF_SR_MPAT2_B1] = new SRegMPAT_N  (ctxt_id, pe, 2, 1);
    m_srf[CF_SR_MPAT3_B1] = new SRegMPAT_N  (ctxt_id, pe, 3, 1);
    m_srf[CF_SR_MPAT4_B1] = new SRegMPAT_N  (ctxt_id, pe, 4, 1);
    m_srf[CF_SR_MPAT5_B1] = new SRegMPAT_N  (ctxt_id, pe, 5, 1);
    m_srf[CF_SR_MPAT6_B1] = new SRegMPAT_N  (ctxt_id, pe, 6, 1);
    m_srf[CF_SR_MPAT7_B1] = new SRegMPAT_N  (ctxt_id, pe, 7, 1);
    m_srf[CF_SR_MPAT8_B1] = new SRegMPAT_N  (ctxt_id, pe, 8, 1);
    m_srf[CF_SR_MPAT9_B1] = new SRegMPAT_N  (ctxt_id, pe, 9, 1);
    m_srf[CF_SR_MPAT10_B1] = new SRegMPAT_N  (ctxt_id, pe, 10, 1);
    m_srf[CF_SR_MPAT11_B1] = new SRegMPAT_N  (ctxt_id, pe, 11, 1);
    m_srf[CF_SR_MPAT12_B1] = new SRegMPAT_N  (ctxt_id, pe, 12, 1);
    m_srf[CF_SR_MPAT13_B1] = new SRegMPAT_N  (ctxt_id, pe, 13, 1);
    m_srf[CF_SR_MPAT14_B1] = new SRegMPAT_N  (ctxt_id, pe, 14, 1);
    m_srf[CF_SR_MPAT15_B1] = new SRegMPAT_N  (ctxt_id, pe, 15, 1);
    m_srf[CF_SR_MPAT16_B1] = new SRegMPAT_N  (ctxt_id, pe, 16, 1);
    m_srf[CF_SR_MPAT17_B1] = new SRegMPAT_N  (ctxt_id, pe, 17, 1);
    m_srf[CF_SR_MPAT18_B1] = new SRegMPAT_N  (ctxt_id, pe, 18, 1);
    m_srf[CF_SR_MPAT19_B1] = new SRegMPAT_N  (ctxt_id, pe, 19, 1);
    m_srf[CF_SR_MPAT20_B1] = new SRegMPAT_N  (ctxt_id, pe, 20, 1);
    m_srf[CF_SR_MPAT21_B1] = new SRegMPAT_N  (ctxt_id, pe, 21, 1);
    m_srf[CF_SR_MPAT22_B1] = new SRegMPAT_N  (ctxt_id, pe, 22, 1);
    m_srf[CF_SR_MPAT23_B1] = new SRegMPAT_N  (ctxt_id, pe, 23, 1);
    m_srf[CF_SR_MPAT24_B1] = new SRegMPAT_N  (ctxt_id, pe, 24, 1);
    m_srf[CF_SR_MPAT25_B1] = new SRegMPAT_N  (ctxt_id, pe, 25, 1);
    m_srf[CF_SR_MPAT26_B1] = new SRegMPAT_N  (ctxt_id, pe, 26, 1);
    m_srf[CF_SR_MPAT27_B1] = new SRegMPAT_N  (ctxt_id, pe, 27, 1);
    m_srf[CF_SR_MPAT28_B1] = new SRegMPAT_N  (ctxt_id, pe, 28, 1);
    m_srf[CF_SR_MPAT29_B1] = new SRegMPAT_N  (ctxt_id, pe, 29, 1);
    m_srf[CF_SR_MPAT30_B1] = new SRegMPAT_N  (ctxt_id, pe, 30, 1);
    m_srf[CF_SR_MPAT31_B1] = new SRegMPAT_N  (ctxt_id, pe, 31, 1);
    break;

    case E3V5_V:
    // System register group 0
    m_srf[CF_SR_HMEIPC]   = new SRegHMEIPC  (ctxt_id, pe);
    m_srf[CF_SR_HMEIPSW]  = new SRegHMEIPSW (ctxt_id, pe);
    m_srf[CF_SR_HMFEPC]   = new SRegHMFEPC  (ctxt_id, pe);
    m_srf[CF_SR_HMFEPSW]  = new SRegHMFEPSW (ctxt_id, pe);
    m_srf[CF_SR_HMPSW]    = new SRegHMPSW   (ctxt_id, pe);
    m_srf[CF_SR_FPSR]     = new SRegFPSR    (ctxt_id, pe);
    m_srf[CF_SR_FPEPC]    = new SRegFPEPC   (ctxt_id, pe);
    m_srf[CF_SR_FPST]     = new SRegFPST    (ctxt_id, pe);
    m_srf[CF_SR_FPCC]     = new SRegFPCC    (ctxt_id, pe);
    m_srf[CF_SR_FPCFG]    = new SRegFPCFG   (ctxt_id, pe);
    m_srf[CF_SR_FPEC]     = new SRegFPEC    (ctxt_id, pe);
    m_srf[CF_SR_HMEIIC]   = new SRegHMEIIC  (ctxt_id, pe);
    m_srf[CF_SR_HMFEIC]   = new SRegHMFEIC  (ctxt_id, pe);
    m_srf[CF_SR_PSWH]     = new SRegPSWH    (ctxt_id, pe);
    m_srf[CF_SR_CTPC]     = new SRegCTPC    (ctxt_id, pe);
    m_srf[CF_SR_CTPSW]    = new SRegCTPSW   (ctxt_id, pe);
    m_srf[CF_SR_EIPSWH]   = new SRegEIPSWH  (ctxt_id, pe);
    m_srf[CF_SR_FEPSWH]   = new SRegFEPSWH  (ctxt_id, pe);
    m_srf[CF_SR_CTBP]     = new SRegCTBP    (ctxt_id, pe);
    m_srf[CF_SR_SNZCFG]   = new SRegSNZCFG  (ctxt_id, pe);
    m_srf[CF_SR_HMEIWR]   = new SRegHMEIWR  (ctxt_id, pe);
    m_srf[CF_SR_HMFEWR]   = new SRegHMFEWR  (ctxt_id, pe);
    // System register group 1
    m_srf[CF_SR_HMSPID]   = new SRegHMSPID  (ctxt_id, pe);
    m_srf[CF_SR_HMSPIDLIST] = new SRegHMSPIDLIST (ctxt_id, pe);
    m_srf[CF_SR_RBASE]    = new SRegRBASE   (ctxt_id, pe);
    m_srf[CF_SR_HMEBASE]  = new SRegHMEBASE (ctxt_id, pe);
    m_srf[CF_SR_HMINTBP]  = new SRegHMINTBP (ctxt_id, pe);
    m_srf[CF_SR_MCTL]     = new SRegMCTL    (ctxt_id, pe);
    m_srf[CF_SR_PID]      = new SRegPID     (ctxt_id, pe);
    m_srf[CF_SR_FPIPR]    = new SRegFPIPR   (ctxt_id, pe);
    m_srf[CF_SR_HMSVLOCK] = new SRegHMSVLOCK (ctxt_id, pe);
    m_srf[CF_SR_SCCFG]    = new SRegSCCFG   (ctxt_id, pe);
    m_srf[CF_SR_SCBP]     = new SRegSCBP    (ctxt_id, pe);
    m_srf[CF_SR_HVCFG]    = new SRegHVCFG   (ctxt_id, pe);
    m_srf[CF_SR_GMCFG]    = new SRegGMCFG   (ctxt_id, pe);
    m_srf[CF_SR_HVSB]     = new SRegHVSB    (ctxt_id, pe);
    // System register group 2
    m_srf[CF_SR_HMPEID]   = new SRegHMPEID  (ctxt_id, pe);
    m_srf[CF_SR_BMID]     = new SRegBMID    (ctxt_id, pe);
    m_srf[CF_SR_HMMEA]    = new SRegHMMEA   (ctxt_id, pe);
    m_srf[CF_SR_HMMEI]    = new SRegHMMEI   (ctxt_id, pe);
    m_srf[CF_SR_ISPR]     = new SRegISPR    (ctxt_id, pe);
    m_srf[CF_SR_IMSR]     = new SRegIMSR    (ctxt_id, pe);
    m_srf[CF_SR_ICSR]     = new SRegICSR    (ctxt_id, pe);
    m_srf[CF_SR_HMINTCFG] = new SRegHMINTCFG (ctxt_id, pe);
    m_srf[CF_SR_HMPLMR]   = new SRegHMPLMR  (ctxt_id, pe);
    m_srf[CF_SR_RBCR0]    = new SRegRBCR0   (ctxt_id, pe);
    m_srf[CF_SR_RBCR1]    = new SRegRBCR1   (ctxt_id, pe);
    m_srf[CF_SR_RBNR]     = new SRegRBNR    (ctxt_id, pe);
    m_srf[CF_SR_RBIP]     = new SRegRBIP    (ctxt_id, pe);
    // System register group 3
    m_srf[CF_SR_DBGEN]    = new SRegDBGEN   (ctxt_id, pe);
    m_srf[CF_SR_DBPSWH]   = new SRegDBPSWH  (ctxt_id, pe);
    m_srf[CF_SR_DBIC]     = new SRegDBIC    (ctxt_id, pe);
    m_srf[CF_SR_DBPC]     = new SRegDBPC    (ctxt_id, pe);
    m_srf[CF_SR_DBPSW]    = new SRegDBPSW   (ctxt_id, pe);
    m_srf[CF_SR_DIR0]     = new SRegDIR0    (ctxt_id, pe);
    m_srf[CF_SR_DIR1]     = new SRegDIR1    (ctxt_id, pe);
    m_srf[CF_SR_BPC]      = new SRegBPC     (ctxt_id, pe);
    m_srf[CF_SR_BPAV]     = new SRegBPAV    (ctxt_id, pe);
    m_srf[CF_SR_BPAM]     = new SRegBPAM    (ctxt_id, pe);
    m_srf[CF_SR_DBCFG]    = new SRegDBCFG   (ctxt_id, pe);
    m_srf[CF_SR_DBWR]     = new SRegDBWR    (ctxt_id, pe);
    // System register group 4
    m_srf[CF_SR_ICTAGL]   = new SRegICTAGL  (ctxt_id, pe);
    m_srf[CF_SR_ICTAGH]   = new SRegICTAGH  (ctxt_id, pe);
    m_srf[CF_SR_ICDATL]   = new SRegICDATL  (ctxt_id, pe);
    m_srf[CF_SR_ICDATH]   = new SRegICDATH  (ctxt_id, pe);
    m_srf[CF_SR_ICCTRL]   = new SRegICCTRL  (ctxt_id, pe);
    m_srf[CF_SR_ICCFG]    = new SRegICCFG   (ctxt_id, pe);
    m_srf[CF_SR_ICERR]    = new SRegICERR   (ctxt_id, pe);
    // System register group 5
    m_srf[CF_SR_HMMPM]    = new SRegHMMPM   (ctxt_id, pe);
    m_srf[CF_SR_MPCFG]    = new SRegMPCFG   (ctxt_id, pe);
    m_srf[CF_SR_MCA]      = new SRegMCA     (ctxt_id, pe);
    m_srf[CF_SR_MCS]      = new SRegMCS     (ctxt_id, pe);
    m_srf[CF_SR_MCC]      = new SRegMCC     (ctxt_id, pe);
    m_srf[CF_SR_MCR]      = new SRegMCR     (ctxt_id, pe);
    m_srf[CF_SR_MCI]      = new SRegMCI     (ctxt_id, pe);
    m_srf[CF_SR_MPIDX]    = new SRegMPIDX   (ctxt_id, pe);
    m_srf[CF_SR_MPBK]     = new SRegMPBK    (ctxt_id, pe);
    m_srf[CF_SR_MPLA]     = new SRegMPLA    (ctxt_id, pe);
    m_srf[CF_SR_MPUA]     = new SRegMPUA    (ctxt_id, pe);
    m_srf[CF_SR_MPAT]     = new SRegMPAT    (ctxt_id, pe);
    m_srf[CF_SR_MPID0]    = new SRegMPID    (ctxt_id, pe, 0);
    m_srf[CF_SR_MPID1]    = new SRegMPID    (ctxt_id, pe, 1);
    m_srf[CF_SR_MPID2]    = new SRegMPID    (ctxt_id, pe, 2);
    m_srf[CF_SR_MPID3]    = new SRegMPID    (ctxt_id, pe, 3);
    m_srf[CF_SR_MPID4]    = new SRegMPID    (ctxt_id, pe, 4);
    m_srf[CF_SR_MPID5]    = new SRegMPID    (ctxt_id, pe, 5);
    m_srf[CF_SR_MPID6]    = new SRegMPID    (ctxt_id, pe, 6);
    m_srf[CF_SR_MPID7]    = new SRegMPID    (ctxt_id, pe, 7);
    // System register group 9
    m_srf[CF_SR_GMEIPC]   = new SRegGMEIPC  (ctxt_id, pe);
    m_srf[CF_SR_GMEIPSW]  = new SRegGMEIPSW (ctxt_id, pe);
    m_srf[CF_SR_GMFEPC]   = new SRegGMFEPC  (ctxt_id, pe);
    m_srf[CF_SR_GMFEPSW]  = new SRegGMFEPSW (ctxt_id, pe);
    m_srf[CF_SR_GMPSW]    = new SRegGMPSW   (ctxt_id, pe);
    m_srf[CF_SR_GMMEA]    = new SRegGMMEA   (ctxt_id, pe);
    m_srf[CF_SR_GMMEI]    = new SRegGMMEI   (ctxt_id, pe);
    m_srf[CF_SR_GMEIIC]   = new SRegGMEIIC  (ctxt_id, pe);
    m_srf[CF_SR_GMFEIC]   = new SRegGMFEIC  (ctxt_id, pe);
    m_srf[CF_SR_GMSPID]   = new SRegGMSPID  (ctxt_id, pe);
    m_srf[CF_SR_GMSPIDLIST] = new SRegGMSPIDLIST (ctxt_id, pe);
    m_srf[CF_SR_GMEBASE]  = new SRegGMEBASE (ctxt_id, pe);
    m_srf[CF_SR_GMINTBP]  = new SRegGMINTBP (ctxt_id, pe);
    m_srf[CF_SR_GMINTCFG] = new SRegGMINTCFG (ctxt_id, pe);
    m_srf[CF_SR_GMPLMR]   = new SRegGMPLMR  (ctxt_id, pe);
    m_srf[CF_SR_GMSVLOCK] = new SRegGMSVLOCK (ctxt_id, pe);
    m_srf[CF_SR_GMMPM]    = new SRegGMMPM   (ctxt_id, pe);
    m_srf[CF_SR_GMEIWR]   = new SRegGMEIWR  (ctxt_id, pe);
    m_srf[CF_SR_GMFEWR]   = new SRegGMFEWR  (ctxt_id, pe);
    m_srf[CF_SR_GMPEID]   = new SRegGMPEID  (ctxt_id, pe);
    // System register group 10
    m_srf[CF_SR_FXSR]     = new SRegFXSR    (ctxt_id, pe);
    m_srf[CF_SR_FXST]     = new SRegFXST    (ctxt_id, pe);
    m_srf[CF_SR_FXINFO]   = new SRegFXINFO  (ctxt_id, pe);
    m_srf[CF_SR_FXCFG]    = new SRegFXCFG   (ctxt_id, pe);
    m_srf[CF_SR_FXXC]     = new SRegFXXC    (ctxt_id, pe);
    m_srf[CF_SR_FXXP]     = new SRegFXXP    (ctxt_id, pe);
    // System register group 11
    m_srf[CF_SR_TSCOUNTL] = new SRegTSCOUNTL (ctxt_id, pe);
    m_srf[CF_SR_TSCOUNTH] = new SRegTSCOUNTH (ctxt_id, pe);
    m_srf[CF_SR_TSCTRL]   = new SRegTSCTRL  (ctxt_id, pe);
    m_srf[CF_SR_PMUMCTRL] = new SRegPMUMCTRL (ctxt_id, pe);
    m_srf[CF_SR_PMGMCTRL] = new SRegPMGMCTRL (ctxt_id, pe);
    m_srf[CF_SR_PMCOUNT0_G4X1X] = new SRegPMCOUNT (ctxt_id, pe, 0);
    m_srf[CF_SR_PMCTRL0_G4X1X] = new SRegPMCTRL  (ctxt_id, pe, 0);
    m_srf[CF_SR_PMCOUNT1_G4X1X] = new SRegPMCOUNT (ctxt_id, pe, 1);
    m_srf[CF_SR_PMCTRL1_G4X1X] = new SRegPMCTRL  (ctxt_id, pe, 1);
    m_srf[CF_SR_PMCOUNT2_G4X1X] = new SRegPMCOUNT (ctxt_id, pe, 2);
    m_srf[CF_SR_PMCTRL2_G4X1X] = new SRegPMCTRL  (ctxt_id, pe, 2);
    m_srf[CF_SR_PMCOUNT3_G4X1X] = new SRegPMCOUNT (ctxt_id, pe, 3);
    m_srf[CF_SR_PMCTRL3_G4X1X] = new SRegPMCTRL  (ctxt_id, pe, 3);
    // System register group 12
    m_srf[CF_SR_LSTEST0]  = new SRegLSTEST0 (ctxt_id, pe);
    m_srf[CF_SR_LSTEST1]  = new SRegLSTEST1 (ctxt_id, pe);
    m_srf[CF_SR_LSCFG]    = new SRegLSCFG   (ctxt_id, pe);
    m_srf[CF_SR_ICBKEY]   = new SRegICBKEY  (ctxt_id, pe);
    m_srf[CF_SR_IFCR]     = new SRegIFCR    (ctxt_id, pe);
    m_srf[CF_SR_IFCR1]    = new SRegIFCR1   (ctxt_id, pe);
    m_srf[CF_SR_BRPCTRL0] = new SRegBRPCTRL0 (ctxt_id, pe);
    m_srf[CF_SR_BRPCTRL1] = new SRegBRPCTRL1 (ctxt_id, pe);
    m_srf[CF_SR_BRPCFG]   = new SRegBRPCFG  (ctxt_id, pe);
    m_srf[CF_SR_BRPACTRL] = new SRegBRPACTRL (ctxt_id, pe);
    m_srf[CF_SR_BRPDATA]  = new SRegBRPDATA (ctxt_id, pe);
    // System register group 13
    m_srf[CF_SR_DCBKEY]   = new SRegDCBKEY  (ctxt_id, pe);
    m_srf[CF_SR_LSUCR]    = new SRegLSUCR   (ctxt_id, pe);
    m_srf[CF_SR_LSULNK0]  = new SRegLSULNK0 (ctxt_id, pe);
    m_srf[CF_SR_LSULNK1]  = new SRegLSULNK1 (ctxt_id, pe);
    m_srf[CF_SR_L1RLCR]   = new SRegL1RLCR  (ctxt_id, pe);
    m_srf[CF_SR_L1RLNK0]  = new SRegL1RLNK0 (ctxt_id, pe);
    m_srf[CF_SR_L1RLNK1]  = new SRegL1RLNK1 (ctxt_id, pe);
    m_srf[CF_SR_L1RCFG]   = new SRegL1RCFG  (ctxt_id, pe);
    m_srf[CF_SR_DECFG]    = new SRegDECFG   (ctxt_id, pe);
    m_srf[CF_SR_DECTRL]   = new SRegDECTRL  (ctxt_id, pe);
    m_srf[CF_SR_DEVDS]    = new SRegDEVDS   (ctxt_id, pe);
    m_srf[CF_SR_RDBCR]    = new SRegRDBCR   (ctxt_id, pe);
    m_srf[CF_SR_RDBACR]   = new SRegRDBACR  (ctxt_id, pe);
    m_srf[CF_SR_RDBATAG]  = new SRegRDBATAG (ctxt_id, pe);
    m_srf[CF_SR_RDBADAT0] = new SRegRDBADAT0 (ctxt_id, pe);
    m_srf[CF_SR_RDBADAT1] = new SRegRDBADAT1 (ctxt_id, pe);
    m_srf[CF_SR_RDBADAT2] = new SRegRDBADAT2 (ctxt_id, pe);
    m_srf[CF_SR_RDBADAT3] = new SRegRDBADAT3 (ctxt_id, pe);
    m_srf[CF_SR_RDBSTAT]  = new SRegRDBSTAT (ctxt_id, pe);
    // System register group 14
    m_srf[CF_SR_PMCTRL0_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 0);
    m_srf[CF_SR_PMCTRL1_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 1);
    m_srf[CF_SR_PMCTRL2_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 2);
    m_srf[CF_SR_PMCTRL3_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 3);
    m_srf[CF_SR_PMCTRL4_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 4);
    m_srf[CF_SR_PMCTRL5_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 5);
    m_srf[CF_SR_PMCTRL6_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 6);
    m_srf[CF_SR_PMCTRL7_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 7);
    m_srf[CF_SR_PMCOUNT0_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 0);
    m_srf[CF_SR_PMCOUNT1_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 1);
    m_srf[CF_SR_PMCOUNT2_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 2);
    m_srf[CF_SR_PMCOUNT3_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 3);
    m_srf[CF_SR_PMCOUNT4_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 4);
    m_srf[CF_SR_PMCOUNT5_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 5);
    m_srf[CF_SR_PMCOUNT6_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 6);
    m_srf[CF_SR_PMCOUNT7_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 7);
    // System register group 15
    m_srf[CF_SR_PMSUBCND0] = new SRegPMSUBCND (ctxt_id, pe, 0);
    m_srf[CF_SR_PMSUBCND1] = new SRegPMSUBCND (ctxt_id, pe, 1);
    m_srf[CF_SR_PMSUBCND2] = new SRegPMSUBCND (ctxt_id, pe, 2);
    m_srf[CF_SR_PMSUBCND3] = new SRegPMSUBCND (ctxt_id, pe, 3);
    m_srf[CF_SR_PMSUBCND4] = new SRegPMSUBCND (ctxt_id, pe, 4);
    m_srf[CF_SR_PMSUBCND5] = new SRegPMSUBCND (ctxt_id, pe, 5);
    m_srf[CF_SR_PMSUBCND6] = new SRegPMSUBCND (ctxt_id, pe, 6);
    m_srf[CF_SR_PMSUBCND7] = new SRegPMSUBCND (ctxt_id, pe, 7);
    // System register group 32
    m_srf[CF_SR_BPC0]     = new SRegBPC_N   (ctxt_id, pe, 0);
    m_srf[CF_SR_BPC1]     = new SRegBPC_N   (ctxt_id, pe, 1);
    m_srf[CF_SR_BPC2]     = new SRegBPC_N   (ctxt_id, pe, 2);
    m_srf[CF_SR_BPC3]     = new SRegBPC_N   (ctxt_id, pe, 3);
    m_srf[CF_SR_BPC4]     = new SRegBPC_N   (ctxt_id, pe, 4);
    m_srf[CF_SR_BPC5]     = new SRegBPC_N   (ctxt_id, pe, 5);
    m_srf[CF_SR_BPC6]     = new SRegBPC_N   (ctxt_id, pe, 6);
    m_srf[CF_SR_BPC7]     = new SRegBPC_N   (ctxt_id, pe, 7);
    m_srf[CF_SR_BPC8]     = new SRegBPC_N   (ctxt_id, pe, 8);
    m_srf[CF_SR_BPC9]     = new SRegBPC_N   (ctxt_id, pe, 9);
    m_srf[CF_SR_BPC10]    = new SRegBPC_N   (ctxt_id, pe, 10);
    m_srf[CF_SR_BPC11]    = new SRegBPC_N   (ctxt_id, pe, 11);
    // System register group 33
    m_srf[CF_SR_BPAV0]    = new SRegBPAV_N  (ctxt_id, pe, 0);
    m_srf[CF_SR_BPAV1]    = new SRegBPAV_N  (ctxt_id, pe, 1);
    m_srf[CF_SR_BPAV2]    = new SRegBPAV_N  (ctxt_id, pe, 2);
    m_srf[CF_SR_BPAV3]    = new SRegBPAV_N  (ctxt_id, pe, 3);
    m_srf[CF_SR_BPAV4]    = new SRegBPAV_N  (ctxt_id, pe, 4);
    m_srf[CF_SR_BPAV5]    = new SRegBPAV_N  (ctxt_id, pe, 5);
    m_srf[CF_SR_BPAV6]    = new SRegBPAV_N  (ctxt_id, pe, 6);
    m_srf[CF_SR_BPAV7]    = new SRegBPAV_N  (ctxt_id, pe, 7);
    m_srf[CF_SR_BPAV8]    = new SRegBPAV_N  (ctxt_id, pe, 8);
    m_srf[CF_SR_BPAV9]    = new SRegBPAV_N  (ctxt_id, pe, 9);
    m_srf[CF_SR_BPAV10]   = new SRegBPAV_N  (ctxt_id, pe, 10);
    m_srf[CF_SR_BPAV11]   = new SRegBPAV_N  (ctxt_id, pe, 11);
    // System register group 34
    m_srf[CF_SR_BPAM0]    = new SRegBPAM_N  (ctxt_id, pe, 0);
    m_srf[CF_SR_BPAM1]    = new SRegBPAM_N  (ctxt_id, pe, 1);
    m_srf[CF_SR_BPAM2]    = new SRegBPAM_N  (ctxt_id, pe, 2);
    m_srf[CF_SR_BPAM3]    = new SRegBPAM_N  (ctxt_id, pe, 3);
    m_srf[CF_SR_BPAM4]    = new SRegBPAM_N  (ctxt_id, pe, 4);
    m_srf[CF_SR_BPAM5]    = new SRegBPAM_N  (ctxt_id, pe, 5);
    m_srf[CF_SR_BPAM6]    = new SRegBPAM_N  (ctxt_id, pe, 6);
    m_srf[CF_SR_BPAM7]    = new SRegBPAM_N  (ctxt_id, pe, 7);
    m_srf[CF_SR_BPAM8]    = new SRegBPAM_N  (ctxt_id, pe, 8);
    m_srf[CF_SR_BPAM9]    = new SRegBPAM_N  (ctxt_id, pe, 9);
    m_srf[CF_SR_BPAM10]   = new SRegBPAM_N  (ctxt_id, pe, 10);
    m_srf[CF_SR_BPAM11]   = new SRegBPAM_N  (ctxt_id, pe, 11);
    // System register group 37
    m_srf[CF_SR_MPLA0]    = new SRegMPLA_N  (ctxt_id, pe, 0, 0);
    m_srf[CF_SR_MPLA1]    = new SRegMPLA_N  (ctxt_id, pe, 1, 0);
    m_srf[CF_SR_MPLA2]    = new SRegMPLA_N  (ctxt_id, pe, 2, 0);
    m_srf[CF_SR_MPLA3]    = new SRegMPLA_N  (ctxt_id, pe, 3, 0);
    m_srf[CF_SR_MPLA4]    = new SRegMPLA_N  (ctxt_id, pe, 4, 0);
    m_srf[CF_SR_MPLA5]    = new SRegMPLA_N  (ctxt_id, pe, 5, 0);
    m_srf[CF_SR_MPLA6]    = new SRegMPLA_N  (ctxt_id, pe, 6, 0);
    m_srf[CF_SR_MPLA7]    = new SRegMPLA_N  (ctxt_id, pe, 7, 0);
    m_srf[CF_SR_MPLA8]    = new SRegMPLA_N  (ctxt_id, pe, 8, 0);
    m_srf[CF_SR_MPLA9]    = new SRegMPLA_N  (ctxt_id, pe, 9, 0);
    m_srf[CF_SR_MPLA10]   = new SRegMPLA_N  (ctxt_id, pe, 10, 0);
    m_srf[CF_SR_MPLA11]   = new SRegMPLA_N  (ctxt_id, pe, 11, 0);
    m_srf[CF_SR_MPLA12]   = new SRegMPLA_N  (ctxt_id, pe, 12, 0);
    m_srf[CF_SR_MPLA13]   = new SRegMPLA_N  (ctxt_id, pe, 13, 0);
    m_srf[CF_SR_MPLA14]   = new SRegMPLA_N  (ctxt_id, pe, 14, 0);
    m_srf[CF_SR_MPLA15]   = new SRegMPLA_N  (ctxt_id, pe, 15, 0);
    m_srf[CF_SR_MPLA16]   = new SRegMPLA_N  (ctxt_id, pe, 16, 0);
    m_srf[CF_SR_MPLA17]   = new SRegMPLA_N  (ctxt_id, pe, 17, 0);
    m_srf[CF_SR_MPLA18]   = new SRegMPLA_N  (ctxt_id, pe, 18, 0);
    m_srf[CF_SR_MPLA19]   = new SRegMPLA_N  (ctxt_id, pe, 19, 0);
    m_srf[CF_SR_MPLA20]   = new SRegMPLA_N  (ctxt_id, pe, 20, 0);
    m_srf[CF_SR_MPLA21]   = new SRegMPLA_N  (ctxt_id, pe, 21, 0);
    m_srf[CF_SR_MPLA22]   = new SRegMPLA_N  (ctxt_id, pe, 22, 0);
    m_srf[CF_SR_MPLA23]   = new SRegMPLA_N  (ctxt_id, pe, 23, 0);
    m_srf[CF_SR_MPLA24]   = new SRegMPLA_N  (ctxt_id, pe, 24, 0);
    m_srf[CF_SR_MPLA25]   = new SRegMPLA_N  (ctxt_id, pe, 25, 0);
    m_srf[CF_SR_MPLA26]   = new SRegMPLA_N  (ctxt_id, pe, 26, 0);
    m_srf[CF_SR_MPLA27]   = new SRegMPLA_N  (ctxt_id, pe, 27, 0);
    m_srf[CF_SR_MPLA28]   = new SRegMPLA_N  (ctxt_id, pe, 28, 0);
    m_srf[CF_SR_MPLA29]   = new SRegMPLA_N  (ctxt_id, pe, 29, 0);
    m_srf[CF_SR_MPLA30]   = new SRegMPLA_N  (ctxt_id, pe, 30, 0);
    m_srf[CF_SR_MPLA31]   = new SRegMPLA_N  (ctxt_id, pe, 31, 0);
    // System register group 38
    m_srf[CF_SR_MPUA0]    = new SRegMPUA_N  (ctxt_id, pe, 0, 0);
    m_srf[CF_SR_MPUA1]    = new SRegMPUA_N  (ctxt_id, pe, 1, 0);
    m_srf[CF_SR_MPUA2]    = new SRegMPUA_N  (ctxt_id, pe, 2, 0);
    m_srf[CF_SR_MPUA3]    = new SRegMPUA_N  (ctxt_id, pe, 3, 0);
    m_srf[CF_SR_MPUA4]    = new SRegMPUA_N  (ctxt_id, pe, 4, 0);
    m_srf[CF_SR_MPUA5]    = new SRegMPUA_N  (ctxt_id, pe, 5, 0);
    m_srf[CF_SR_MPUA6]    = new SRegMPUA_N  (ctxt_id, pe, 6, 0);
    m_srf[CF_SR_MPUA7]    = new SRegMPUA_N  (ctxt_id, pe, 7, 0);
    m_srf[CF_SR_MPUA8]    = new SRegMPUA_N  (ctxt_id, pe, 8, 0);
    m_srf[CF_SR_MPUA9]    = new SRegMPUA_N  (ctxt_id, pe, 9, 0);
    m_srf[CF_SR_MPUA10]   = new SRegMPUA_N  (ctxt_id, pe, 10, 0);
    m_srf[CF_SR_MPUA11]   = new SRegMPUA_N  (ctxt_id, pe, 11, 0);
    m_srf[CF_SR_MPUA12]   = new SRegMPUA_N  (ctxt_id, pe, 12, 0);
    m_srf[CF_SR_MPUA13]   = new SRegMPUA_N  (ctxt_id, pe, 13, 0);
    m_srf[CF_SR_MPUA14]   = new SRegMPUA_N  (ctxt_id, pe, 14, 0);
    m_srf[CF_SR_MPUA15]   = new SRegMPUA_N  (ctxt_id, pe, 15, 0);
    m_srf[CF_SR_MPUA16]   = new SRegMPUA_N  (ctxt_id, pe, 16, 0);
    m_srf[CF_SR_MPUA17]   = new SRegMPUA_N  (ctxt_id, pe, 17, 0);
    m_srf[CF_SR_MPUA18]   = new SRegMPUA_N  (ctxt_id, pe, 18, 0);
    m_srf[CF_SR_MPUA19]   = new SRegMPUA_N  (ctxt_id, pe, 19, 0);
    m_srf[CF_SR_MPUA20]   = new SRegMPUA_N  (ctxt_id, pe, 20, 0);
    m_srf[CF_SR_MPUA21]   = new SRegMPUA_N  (ctxt_id, pe, 21, 0);
    m_srf[CF_SR_MPUA22]   = new SRegMPUA_N  (ctxt_id, pe, 22, 0);
    m_srf[CF_SR_MPUA23]   = new SRegMPUA_N  (ctxt_id, pe, 23, 0);
    m_srf[CF_SR_MPUA24]   = new SRegMPUA_N  (ctxt_id, pe, 24, 0);
    m_srf[CF_SR_MPUA25]   = new SRegMPUA_N  (ctxt_id, pe, 25, 0);
    m_srf[CF_SR_MPUA26]   = new SRegMPUA_N  (ctxt_id, pe, 26, 0);
    m_srf[CF_SR_MPUA27]   = new SRegMPUA_N  (ctxt_id, pe, 27, 0);
    m_srf[CF_SR_MPUA28]   = new SRegMPUA_N  (ctxt_id, pe, 28, 0);
    m_srf[CF_SR_MPUA29]   = new SRegMPUA_N  (ctxt_id, pe, 29, 0);
    m_srf[CF_SR_MPUA30]   = new SRegMPUA_N  (ctxt_id, pe, 30, 0);
    m_srf[CF_SR_MPUA31]   = new SRegMPUA_N  (ctxt_id, pe, 31, 0);
    // System register group 39
    m_srf[CF_SR_MPAT0]    = new SRegMPAT_N  (ctxt_id, pe, 0, 0);
    m_srf[CF_SR_MPAT1]    = new SRegMPAT_N  (ctxt_id, pe, 1, 0);
    m_srf[CF_SR_MPAT2]    = new SRegMPAT_N  (ctxt_id, pe, 2, 0);
    m_srf[CF_SR_MPAT3]    = new SRegMPAT_N  (ctxt_id, pe, 3, 0);
    m_srf[CF_SR_MPAT4]    = new SRegMPAT_N  (ctxt_id, pe, 4, 0);
    m_srf[CF_SR_MPAT5]    = new SRegMPAT_N  (ctxt_id, pe, 5, 0);
    m_srf[CF_SR_MPAT6]    = new SRegMPAT_N  (ctxt_id, pe, 6, 0);
    m_srf[CF_SR_MPAT7]    = new SRegMPAT_N  (ctxt_id, pe, 7, 0);
    m_srf[CF_SR_MPAT8]    = new SRegMPAT_N  (ctxt_id, pe, 8, 0);
    m_srf[CF_SR_MPAT9]    = new SRegMPAT_N  (ctxt_id, pe, 9, 0);
    m_srf[CF_SR_MPAT10]   = new SRegMPAT_N  (ctxt_id, pe, 10, 0);
    m_srf[CF_SR_MPAT11]   = new SRegMPAT_N  (ctxt_id, pe, 11, 0);
    m_srf[CF_SR_MPAT12]   = new SRegMPAT_N  (ctxt_id, pe, 12, 0);
    m_srf[CF_SR_MPAT13]   = new SRegMPAT_N  (ctxt_id, pe, 13, 0);
    m_srf[CF_SR_MPAT14]   = new SRegMPAT_N  (ctxt_id, pe, 14, 0);
    m_srf[CF_SR_MPAT15]   = new SRegMPAT_N  (ctxt_id, pe, 15, 0);
    m_srf[CF_SR_MPAT16]   = new SRegMPAT_N  (ctxt_id, pe, 16, 0);
    m_srf[CF_SR_MPAT17]   = new SRegMPAT_N  (ctxt_id, pe, 17, 0);
    m_srf[CF_SR_MPAT18]   = new SRegMPAT_N  (ctxt_id, pe, 18, 0);
    m_srf[CF_SR_MPAT19]   = new SRegMPAT_N  (ctxt_id, pe, 19, 0);
    m_srf[CF_SR_MPAT20]   = new SRegMPAT_N  (ctxt_id, pe, 20, 0);
    m_srf[CF_SR_MPAT21]   = new SRegMPAT_N  (ctxt_id, pe, 21, 0);
    m_srf[CF_SR_MPAT22]   = new SRegMPAT_N  (ctxt_id, pe, 22, 0);
    m_srf[CF_SR_MPAT23]   = new SRegMPAT_N  (ctxt_id, pe, 23, 0);
    m_srf[CF_SR_MPAT24]   = new SRegMPAT_N  (ctxt_id, pe, 24, 0);
    m_srf[CF_SR_MPAT25]   = new SRegMPAT_N  (ctxt_id, pe, 25, 0);
    m_srf[CF_SR_MPAT26]   = new SRegMPAT_N  (ctxt_id, pe, 26, 0);
    m_srf[CF_SR_MPAT27]   = new SRegMPAT_N  (ctxt_id, pe, 27, 0);
    m_srf[CF_SR_MPAT28]   = new SRegMPAT_N  (ctxt_id, pe, 28, 0);
    m_srf[CF_SR_MPAT29]   = new SRegMPAT_N  (ctxt_id, pe, 29, 0);
    m_srf[CF_SR_MPAT30]   = new SRegMPAT_N  (ctxt_id, pe, 30, 0);
    m_srf[CF_SR_MPAT31]   = new SRegMPAT_N  (ctxt_id, pe, 31, 0);
    // System register group 40
    m_srf[CF_SR_MPLA0_B1] = new SRegMPLA_N  (ctxt_id, pe, 0, 1);
    m_srf[CF_SR_MPLA1_B1] = new SRegMPLA_N  (ctxt_id, pe, 1, 1);
    m_srf[CF_SR_MPLA2_B1] = new SRegMPLA_N  (ctxt_id, pe, 2, 1);
    m_srf[CF_SR_MPLA3_B1] = new SRegMPLA_N  (ctxt_id, pe, 3, 1);
    m_srf[CF_SR_MPLA4_B1] = new SRegMPLA_N  (ctxt_id, pe, 4, 1);
    m_srf[CF_SR_MPLA5_B1] = new SRegMPLA_N  (ctxt_id, pe, 5, 1);
    m_srf[CF_SR_MPLA6_B1] = new SRegMPLA_N  (ctxt_id, pe, 6, 1);
    m_srf[CF_SR_MPLA7_B1] = new SRegMPLA_N  (ctxt_id, pe, 7, 1);
    m_srf[CF_SR_MPLA8_B1] = new SRegMPLA_N  (ctxt_id, pe, 8, 1);
    m_srf[CF_SR_MPLA9_B1] = new SRegMPLA_N  (ctxt_id, pe, 9, 1);
    m_srf[CF_SR_MPLA10_B1] = new SRegMPLA_N  (ctxt_id, pe, 10, 1);
    m_srf[CF_SR_MPLA11_B1] = new SRegMPLA_N  (ctxt_id, pe, 11, 1);
    m_srf[CF_SR_MPLA12_B1] = new SRegMPLA_N  (ctxt_id, pe, 12, 1);
    m_srf[CF_SR_MPLA13_B1] = new SRegMPLA_N  (ctxt_id, pe, 13, 1);
    m_srf[CF_SR_MPLA14_B1] = new SRegMPLA_N  (ctxt_id, pe, 14, 1);
    m_srf[CF_SR_MPLA15_B1] = new SRegMPLA_N  (ctxt_id, pe, 15, 1);
    m_srf[CF_SR_MPLA16_B1] = new SRegMPLA_N  (ctxt_id, pe, 16, 1);
    m_srf[CF_SR_MPLA17_B1] = new SRegMPLA_N  (ctxt_id, pe, 17, 1);
    m_srf[CF_SR_MPLA18_B1] = new SRegMPLA_N  (ctxt_id, pe, 18, 1);
    m_srf[CF_SR_MPLA19_B1] = new SRegMPLA_N  (ctxt_id, pe, 19, 1);
    m_srf[CF_SR_MPLA20_B1] = new SRegMPLA_N  (ctxt_id, pe, 20, 1);
    m_srf[CF_SR_MPLA21_B1] = new SRegMPLA_N  (ctxt_id, pe, 21, 1);
    m_srf[CF_SR_MPLA22_B1] = new SRegMPLA_N  (ctxt_id, pe, 22, 1);
    m_srf[CF_SR_MPLA23_B1] = new SRegMPLA_N  (ctxt_id, pe, 23, 1);
    m_srf[CF_SR_MPLA24_B1] = new SRegMPLA_N  (ctxt_id, pe, 24, 1);
    m_srf[CF_SR_MPLA25_B1] = new SRegMPLA_N  (ctxt_id, pe, 25, 1);
    m_srf[CF_SR_MPLA26_B1] = new SRegMPLA_N  (ctxt_id, pe, 26, 1);
    m_srf[CF_SR_MPLA27_B1] = new SRegMPLA_N  (ctxt_id, pe, 27, 1);
    m_srf[CF_SR_MPLA28_B1] = new SRegMPLA_N  (ctxt_id, pe, 28, 1);
    m_srf[CF_SR_MPLA29_B1] = new SRegMPLA_N  (ctxt_id, pe, 29, 1);
    m_srf[CF_SR_MPLA30_B1] = new SRegMPLA_N  (ctxt_id, pe, 30, 1);
    m_srf[CF_SR_MPLA31_B1] = new SRegMPLA_N  (ctxt_id, pe, 31, 1);
    // System register group 41
    m_srf[CF_SR_MPUA0_B1] = new SRegMPUA_N  (ctxt_id, pe, 0, 1);
    m_srf[CF_SR_MPUA1_B1] = new SRegMPUA_N  (ctxt_id, pe, 1, 1);
    m_srf[CF_SR_MPUA2_B1] = new SRegMPUA_N  (ctxt_id, pe, 2, 1);
    m_srf[CF_SR_MPUA3_B1] = new SRegMPUA_N  (ctxt_id, pe, 3, 1);
    m_srf[CF_SR_MPUA4_B1] = new SRegMPUA_N  (ctxt_id, pe, 4, 1);
    m_srf[CF_SR_MPUA5_B1] = new SRegMPUA_N  (ctxt_id, pe, 5, 1);
    m_srf[CF_SR_MPUA6_B1] = new SRegMPUA_N  (ctxt_id, pe, 6, 1);
    m_srf[CF_SR_MPUA7_B1] = new SRegMPUA_N  (ctxt_id, pe, 7, 1);
    m_srf[CF_SR_MPUA8_B1] = new SRegMPUA_N  (ctxt_id, pe, 8, 1);
    m_srf[CF_SR_MPUA9_B1] = new SRegMPUA_N  (ctxt_id, pe, 9, 1);
    m_srf[CF_SR_MPUA10_B1] = new SRegMPUA_N  (ctxt_id, pe, 10, 1);
    m_srf[CF_SR_MPUA11_B1] = new SRegMPUA_N  (ctxt_id, pe, 11, 1);
    m_srf[CF_SR_MPUA12_B1] = new SRegMPUA_N  (ctxt_id, pe, 12, 1);
    m_srf[CF_SR_MPUA13_B1] = new SRegMPUA_N  (ctxt_id, pe, 13, 1);
    m_srf[CF_SR_MPUA14_B1] = new SRegMPUA_N  (ctxt_id, pe, 14, 1);
    m_srf[CF_SR_MPUA15_B1] = new SRegMPUA_N  (ctxt_id, pe, 15, 1);
    m_srf[CF_SR_MPUA16_B1] = new SRegMPUA_N  (ctxt_id, pe, 16, 1);
    m_srf[CF_SR_MPUA17_B1] = new SRegMPUA_N  (ctxt_id, pe, 17, 1);
    m_srf[CF_SR_MPUA18_B1] = new SRegMPUA_N  (ctxt_id, pe, 18, 1);
    m_srf[CF_SR_MPUA19_B1] = new SRegMPUA_N  (ctxt_id, pe, 19, 1);
    m_srf[CF_SR_MPUA20_B1] = new SRegMPUA_N  (ctxt_id, pe, 20, 1);
    m_srf[CF_SR_MPUA21_B1] = new SRegMPUA_N  (ctxt_id, pe, 21, 1);
    m_srf[CF_SR_MPUA22_B1] = new SRegMPUA_N  (ctxt_id, pe, 22, 1);
    m_srf[CF_SR_MPUA23_B1] = new SRegMPUA_N  (ctxt_id, pe, 23, 1);
    m_srf[CF_SR_MPUA24_B1] = new SRegMPUA_N  (ctxt_id, pe, 24, 1);
    m_srf[CF_SR_MPUA25_B1] = new SRegMPUA_N  (ctxt_id, pe, 25, 1);
    m_srf[CF_SR_MPUA26_B1] = new SRegMPUA_N  (ctxt_id, pe, 26, 1);
    m_srf[CF_SR_MPUA27_B1] = new SRegMPUA_N  (ctxt_id, pe, 27, 1);
    m_srf[CF_SR_MPUA28_B1] = new SRegMPUA_N  (ctxt_id, pe, 28, 1);
    m_srf[CF_SR_MPUA29_B1] = new SRegMPUA_N  (ctxt_id, pe, 29, 1);
    m_srf[CF_SR_MPUA30_B1] = new SRegMPUA_N  (ctxt_id, pe, 30, 1);
    m_srf[CF_SR_MPUA31_B1] = new SRegMPUA_N  (ctxt_id, pe, 31, 1);
    // System register group 42
    m_srf[CF_SR_MPAT0_B1] = new SRegMPAT_N  (ctxt_id, pe, 0, 1);
    m_srf[CF_SR_MPAT1_B1] = new SRegMPAT_N  (ctxt_id, pe, 1, 1);
    m_srf[CF_SR_MPAT2_B1] = new SRegMPAT_N  (ctxt_id, pe, 2, 1);
    m_srf[CF_SR_MPAT3_B1] = new SRegMPAT_N  (ctxt_id, pe, 3, 1);
    m_srf[CF_SR_MPAT4_B1] = new SRegMPAT_N  (ctxt_id, pe, 4, 1);
    m_srf[CF_SR_MPAT5_B1] = new SRegMPAT_N  (ctxt_id, pe, 5, 1);
    m_srf[CF_SR_MPAT6_B1] = new SRegMPAT_N  (ctxt_id, pe, 6, 1);
    m_srf[CF_SR_MPAT7_B1] = new SRegMPAT_N  (ctxt_id, pe, 7, 1);
    m_srf[CF_SR_MPAT8_B1] = new SRegMPAT_N  (ctxt_id, pe, 8, 1);
    m_srf[CF_SR_MPAT9_B1] = new SRegMPAT_N  (ctxt_id, pe, 9, 1);
    m_srf[CF_SR_MPAT10_B1] = new SRegMPAT_N  (ctxt_id, pe, 10, 1);
    m_srf[CF_SR_MPAT11_B1] = new SRegMPAT_N  (ctxt_id, pe, 11, 1);
    m_srf[CF_SR_MPAT12_B1] = new SRegMPAT_N  (ctxt_id, pe, 12, 1);
    m_srf[CF_SR_MPAT13_B1] = new SRegMPAT_N  (ctxt_id, pe, 13, 1);
    m_srf[CF_SR_MPAT14_B1] = new SRegMPAT_N  (ctxt_id, pe, 14, 1);
    m_srf[CF_SR_MPAT15_B1] = new SRegMPAT_N  (ctxt_id, pe, 15, 1);
    m_srf[CF_SR_MPAT16_B1] = new SRegMPAT_N  (ctxt_id, pe, 16, 1);
    m_srf[CF_SR_MPAT17_B1] = new SRegMPAT_N  (ctxt_id, pe, 17, 1);
    m_srf[CF_SR_MPAT18_B1] = new SRegMPAT_N  (ctxt_id, pe, 18, 1);
    m_srf[CF_SR_MPAT19_B1] = new SRegMPAT_N  (ctxt_id, pe, 19, 1);
    m_srf[CF_SR_MPAT20_B1] = new SRegMPAT_N  (ctxt_id, pe, 20, 1);
    m_srf[CF_SR_MPAT21_B1] = new SRegMPAT_N  (ctxt_id, pe, 21, 1);
    m_srf[CF_SR_MPAT22_B1] = new SRegMPAT_N  (ctxt_id, pe, 22, 1);
    m_srf[CF_SR_MPAT23_B1] = new SRegMPAT_N  (ctxt_id, pe, 23, 1);
    m_srf[CF_SR_MPAT24_B1] = new SRegMPAT_N  (ctxt_id, pe, 24, 1);
    m_srf[CF_SR_MPAT25_B1] = new SRegMPAT_N  (ctxt_id, pe, 25, 1);
    m_srf[CF_SR_MPAT26_B1] = new SRegMPAT_N  (ctxt_id, pe, 26, 1);
    m_srf[CF_SR_MPAT27_B1] = new SRegMPAT_N  (ctxt_id, pe, 27, 1);
    m_srf[CF_SR_MPAT28_B1] = new SRegMPAT_N  (ctxt_id, pe, 28, 1);
    m_srf[CF_SR_MPAT29_B1] = new SRegMPAT_N  (ctxt_id, pe, 29, 1);
    m_srf[CF_SR_MPAT30_B1] = new SRegMPAT_N  (ctxt_id, pe, 30, 1);
    m_srf[CF_SR_MPAT31_B1] = new SRegMPAT_N  (ctxt_id, pe, 31, 1);
    break;

    case E3V5_S:
    // System register group 0
    m_srf[CF_SR_HMEIPC]   = new SRegHMEIPC  (ctxt_id, pe);
    m_srf[CF_SR_HMEIPSW]  = new SRegHMEIPSW (ctxt_id, pe);
    m_srf[CF_SR_HMFEPC]   = new SRegHMFEPC  (ctxt_id, pe);
    m_srf[CF_SR_HMFEPSW]  = new SRegHMFEPSW (ctxt_id, pe);
    m_srf[CF_SR_HMPSW]    = new SRegHMPSW   (ctxt_id, pe);
    m_srf[CF_SR_FPSR]     = new SRegFPSR    (ctxt_id, pe);
    m_srf[CF_SR_FPEPC]    = new SRegFPEPC   (ctxt_id, pe);
    m_srf[CF_SR_FPST]     = new SRegFPST    (ctxt_id, pe);
    m_srf[CF_SR_FPCC]     = new SRegFPCC    (ctxt_id, pe);
    m_srf[CF_SR_FPCFG]    = new SRegFPCFG   (ctxt_id, pe);
    m_srf[CF_SR_FPEC]     = new SRegFPEC    (ctxt_id, pe);
    m_srf[CF_SR_HMEIIC]   = new SRegHMEIIC  (ctxt_id, pe);
    m_srf[CF_SR_HMFEIC]   = new SRegHMFEIC  (ctxt_id, pe);
    m_srf[CF_SR_PSWH]     = new SRegPSWH    (ctxt_id, pe);
    m_srf[CF_SR_CTPC]     = new SRegCTPC    (ctxt_id, pe);
    m_srf[CF_SR_CTPSW]    = new SRegCTPSW   (ctxt_id, pe);
    m_srf[CF_SR_EIPSWH]   = new SRegEIPSWH  (ctxt_id, pe);
    m_srf[CF_SR_FEPSWH]   = new SRegFEPSWH  (ctxt_id, pe);
    m_srf[CF_SR_CTBP]     = new SRegCTBP    (ctxt_id, pe);
    m_srf[CF_SR_SNZCFG]   = new SRegSNZCFG  (ctxt_id, pe);
    m_srf[CF_SR_HMEIWR]   = new SRegHMEIWR  (ctxt_id, pe);
    m_srf[CF_SR_HMFEWR]   = new SRegHMFEWR  (ctxt_id, pe);
    // System register group 1
    m_srf[CF_SR_HMSPID]   = new SRegHMSPID  (ctxt_id, pe);
    m_srf[CF_SR_HMSPIDLIST] = new SRegHMSPIDLIST (ctxt_id, pe);
    m_srf[CF_SR_RBASE]    = new SRegRBASE   (ctxt_id, pe);
    m_srf[CF_SR_HMEBASE]  = new SRegHMEBASE (ctxt_id, pe);
    m_srf[CF_SR_HMINTBP]  = new SRegHMINTBP (ctxt_id, pe);
    m_srf[CF_SR_MCTL]     = new SRegMCTL    (ctxt_id, pe);
    m_srf[CF_SR_PID]      = new SRegPID     (ctxt_id, pe);
    m_srf[CF_SR_FPIPR]    = new SRegFPIPR   (ctxt_id, pe);
    m_srf[CF_SR_HMSVLOCK] = new SRegHMSVLOCK (ctxt_id, pe);
    m_srf[CF_SR_SCCFG]    = new SRegSCCFG   (ctxt_id, pe);
    m_srf[CF_SR_SCBP]     = new SRegSCBP    (ctxt_id, pe);
    m_srf[CF_SR_HVCFG]    = new SRegHVCFG   (ctxt_id, pe);
    m_srf[CF_SR_GMCFG]    = new SRegGMCFG   (ctxt_id, pe);
    m_srf[CF_SR_HVSB]     = new SRegHVSB    (ctxt_id, pe);
    // System register group 2
    m_srf[CF_SR_HMPEID]   = new SRegHMPEID  (ctxt_id, pe);
    m_srf[CF_SR_BMID]     = new SRegBMID    (ctxt_id, pe);
    m_srf[CF_SR_HMMEA]    = new SRegHMMEA   (ctxt_id, pe);
    m_srf[CF_SR_HMMEI]    = new SRegHMMEI   (ctxt_id, pe);
    m_srf[CF_SR_ISPR]     = new SRegISPR    (ctxt_id, pe);
    m_srf[CF_SR_IMSR]     = new SRegIMSR    (ctxt_id, pe);
    m_srf[CF_SR_ICSR]     = new SRegICSR    (ctxt_id, pe);
    m_srf[CF_SR_HMINTCFG] = new SRegHMINTCFG (ctxt_id, pe);
    m_srf[CF_SR_HMPLMR]   = new SRegHMPLMR  (ctxt_id, pe);
    m_srf[CF_SR_RBCR0]    = new SRegRBCR0   (ctxt_id, pe);
    m_srf[CF_SR_RBCR1]    = new SRegRBCR1   (ctxt_id, pe);
    m_srf[CF_SR_RBNR]     = new SRegRBNR    (ctxt_id, pe);
    m_srf[CF_SR_RBIP]     = new SRegRBIP    (ctxt_id, pe);
    // System register group 3
    m_srf[CF_SR_DBGEN]    = new SRegDBGEN   (ctxt_id, pe);
    m_srf[CF_SR_DBPSWH]   = new SRegDBPSWH  (ctxt_id, pe);
    m_srf[CF_SR_DBIC]     = new SRegDBIC    (ctxt_id, pe);
    m_srf[CF_SR_DBPC]     = new SRegDBPC    (ctxt_id, pe);
    m_srf[CF_SR_DBPSW]    = new SRegDBPSW   (ctxt_id, pe);
    m_srf[CF_SR_DIR0]     = new SRegDIR0    (ctxt_id, pe);
    m_srf[CF_SR_DIR1]     = new SRegDIR1    (ctxt_id, pe);
    m_srf[CF_SR_BPC]      = new SRegBPC     (ctxt_id, pe);
    m_srf[CF_SR_BPAV]     = new SRegBPAV    (ctxt_id, pe);
    m_srf[CF_SR_BPAM]     = new SRegBPAM    (ctxt_id, pe);
    m_srf[CF_SR_DBCFG]    = new SRegDBCFG   (ctxt_id, pe);
    m_srf[CF_SR_DBWR]     = new SRegDBWR    (ctxt_id, pe);
    // System register group 4
    m_srf[CF_SR_ICTAGL]   = new SRegICTAGL  (ctxt_id, pe);
    m_srf[CF_SR_ICTAGH]   = new SRegICTAGH  (ctxt_id, pe);
    m_srf[CF_SR_ICDATL]   = new SRegICDATL  (ctxt_id, pe);
    m_srf[CF_SR_ICDATH]   = new SRegICDATH  (ctxt_id, pe);
    m_srf[CF_SR_ICCTRL]   = new SRegICCTRL  (ctxt_id, pe);
    m_srf[CF_SR_ICCFG]    = new SRegICCFG   (ctxt_id, pe);
    m_srf[CF_SR_ICERR]    = new SRegICERR   (ctxt_id, pe);
    // System register group 5
    m_srf[CF_SR_HMMPM]    = new SRegHMMPM   (ctxt_id, pe);
    m_srf[CF_SR_MPCFG]    = new SRegMPCFG   (ctxt_id, pe);
    m_srf[CF_SR_MCA]      = new SRegMCA     (ctxt_id, pe);
    m_srf[CF_SR_MCS]      = new SRegMCS     (ctxt_id, pe);
    m_srf[CF_SR_MCC]      = new SRegMCC     (ctxt_id, pe);
    m_srf[CF_SR_MCR]      = new SRegMCR     (ctxt_id, pe);
    m_srf[CF_SR_MCI]      = new SRegMCI     (ctxt_id, pe);
    m_srf[CF_SR_MPIDX]    = new SRegMPIDX   (ctxt_id, pe);
    m_srf[CF_SR_MPBK]     = new SRegMPBK    (ctxt_id, pe);
    m_srf[CF_SR_MPLA]     = new SRegMPLA    (ctxt_id, pe);
    m_srf[CF_SR_MPUA]     = new SRegMPUA    (ctxt_id, pe);
    m_srf[CF_SR_MPAT]     = new SRegMPAT    (ctxt_id, pe);
    m_srf[CF_SR_MPID0]    = new SRegMPID    (ctxt_id, pe, 0);
    m_srf[CF_SR_MPID1]    = new SRegMPID    (ctxt_id, pe, 1);
    m_srf[CF_SR_MPID2]    = new SRegMPID    (ctxt_id, pe, 2);
    m_srf[CF_SR_MPID3]    = new SRegMPID    (ctxt_id, pe, 3);
    m_srf[CF_SR_MPID4]    = new SRegMPID    (ctxt_id, pe, 4);
    m_srf[CF_SR_MPID5]    = new SRegMPID    (ctxt_id, pe, 5);
    m_srf[CF_SR_MPID6]    = new SRegMPID    (ctxt_id, pe, 6);
    m_srf[CF_SR_MPID7]    = new SRegMPID    (ctxt_id, pe, 7);
    // System register group 9
    m_srf[CF_SR_GMEIPC]   = new SRegGMEIPC  (ctxt_id, pe);
    m_srf[CF_SR_GMEIPSW]  = new SRegGMEIPSW (ctxt_id, pe);
    m_srf[CF_SR_GMFEPC]   = new SRegGMFEPC  (ctxt_id, pe);
    m_srf[CF_SR_GMFEPSW]  = new SRegGMFEPSW (ctxt_id, pe);
    m_srf[CF_SR_GMPSW]    = new SRegGMPSW   (ctxt_id, pe);
    m_srf[CF_SR_GMMEA]    = new SRegGMMEA   (ctxt_id, pe);
    m_srf[CF_SR_GMMEI]    = new SRegGMMEI   (ctxt_id, pe);
    m_srf[CF_SR_GMEIIC]   = new SRegGMEIIC  (ctxt_id, pe);
    m_srf[CF_SR_GMFEIC]   = new SRegGMFEIC  (ctxt_id, pe);
    m_srf[CF_SR_GMSPID]   = new SRegGMSPID  (ctxt_id, pe);
    m_srf[CF_SR_GMSPIDLIST] = new SRegGMSPIDLIST (ctxt_id, pe);
    m_srf[CF_SR_GMEBASE]  = new SRegGMEBASE (ctxt_id, pe);
    m_srf[CF_SR_GMINTBP]  = new SRegGMINTBP (ctxt_id, pe);
    m_srf[CF_SR_GMINTCFG] = new SRegGMINTCFG (ctxt_id, pe);
    m_srf[CF_SR_GMPLMR]   = new SRegGMPLMR  (ctxt_id, pe);
    m_srf[CF_SR_GMSVLOCK] = new SRegGMSVLOCK (ctxt_id, pe);
    m_srf[CF_SR_GMMPM]    = new SRegGMMPM   (ctxt_id, pe);
    m_srf[CF_SR_GMEIWR]   = new SRegGMEIWR  (ctxt_id, pe);
    m_srf[CF_SR_GMFEWR]   = new SRegGMFEWR  (ctxt_id, pe);
    m_srf[CF_SR_GMPEID]   = new SRegGMPEID  (ctxt_id, pe);
    // System register group 10
    m_srf[CF_SR_FXSR]     = new SRegFXSR    (ctxt_id, pe);
    m_srf[CF_SR_FXST]     = new SRegFXST    (ctxt_id, pe);
    m_srf[CF_SR_FXINFO]   = new SRegFXINFO  (ctxt_id, pe);
    m_srf[CF_SR_FXCFG]    = new SRegFXCFG   (ctxt_id, pe);
    m_srf[CF_SR_FXXC]     = new SRegFXXC    (ctxt_id, pe);
    m_srf[CF_SR_FXXP]     = new SRegFXXP    (ctxt_id, pe);
    // System register group 11
    m_srf[CF_SR_TSCOUNTL] = new SRegTSCOUNTL (ctxt_id, pe);
    m_srf[CF_SR_TSCOUNTH] = new SRegTSCOUNTH (ctxt_id, pe);
    m_srf[CF_SR_TSCTRL]   = new SRegTSCTRL  (ctxt_id, pe);
    m_srf[CF_SR_PMUMCTRL] = new SRegPMUMCTRL (ctxt_id, pe);
    m_srf[CF_SR_PMGMCTRL] = new SRegPMGMCTRL (ctxt_id, pe);
    m_srf[CF_SR_PMCOUNT0_G4X1X] = new SRegPMCOUNT (ctxt_id, pe, 0);
    m_srf[CF_SR_PMCTRL0_G4X1X] = new SRegPMCTRL  (ctxt_id, pe, 0);
    m_srf[CF_SR_PMCOUNT1_G4X1X] = new SRegPMCOUNT (ctxt_id, pe, 1);
    m_srf[CF_SR_PMCTRL1_G4X1X] = new SRegPMCTRL  (ctxt_id, pe, 1);
    m_srf[CF_SR_PMCOUNT2_G4X1X] = new SRegPMCOUNT (ctxt_id, pe, 2);
    m_srf[CF_SR_PMCTRL2_G4X1X] = new SRegPMCTRL  (ctxt_id, pe, 2);
    m_srf[CF_SR_PMCOUNT3_G4X1X] = new SRegPMCOUNT (ctxt_id, pe, 3);
    m_srf[CF_SR_PMCTRL3_G4X1X] = new SRegPMCTRL  (ctxt_id, pe, 3);
    // System register group 12
    m_srf[CF_SR_LSTEST0]  = new SRegLSTEST0 (ctxt_id, pe);
    m_srf[CF_SR_LSTEST1]  = new SRegLSTEST1 (ctxt_id, pe);
    m_srf[CF_SR_LSCFG]    = new SRegLSCFG   (ctxt_id, pe);
    m_srf[CF_SR_ICBKEY]   = new SRegICBKEY  (ctxt_id, pe);
    m_srf[CF_SR_IFCR]     = new SRegIFCR    (ctxt_id, pe);
    m_srf[CF_SR_IFCR1]    = new SRegIFCR1   (ctxt_id, pe);
    m_srf[CF_SR_BRPCTRL0] = new SRegBRPCTRL0 (ctxt_id, pe);
    m_srf[CF_SR_BRPCTRL1] = new SRegBRPCTRL1 (ctxt_id, pe);
    m_srf[CF_SR_BRPCFG]   = new SRegBRPCFG  (ctxt_id, pe);
    m_srf[CF_SR_BRPACTRL] = new SRegBRPACTRL (ctxt_id, pe);
    m_srf[CF_SR_BRPDATA]  = new SRegBRPDATA (ctxt_id, pe);
    // System register group 13
    m_srf[CF_SR_DCBKEY]   = new SRegDCBKEY  (ctxt_id, pe);
    m_srf[CF_SR_LSUCR]    = new SRegLSUCR   (ctxt_id, pe);
    m_srf[CF_SR_LSULNK0]  = new SRegLSULNK0 (ctxt_id, pe);
    m_srf[CF_SR_LSULNK1]  = new SRegLSULNK1 (ctxt_id, pe);
    m_srf[CF_SR_L1RLCR]   = new SRegL1RLCR  (ctxt_id, pe);
    m_srf[CF_SR_L1RLNK0]  = new SRegL1RLNK0 (ctxt_id, pe);
    m_srf[CF_SR_L1RLNK1]  = new SRegL1RLNK1 (ctxt_id, pe);
    m_srf[CF_SR_L1RCFG]   = new SRegL1RCFG  (ctxt_id, pe);
    m_srf[CF_SR_DECFG]    = new SRegDECFG   (ctxt_id, pe);
    m_srf[CF_SR_DECTRL]   = new SRegDECTRL  (ctxt_id, pe);
    m_srf[CF_SR_DEVDS]    = new SRegDEVDS   (ctxt_id, pe);
    m_srf[CF_SR_RDBCR]    = new SRegRDBCR   (ctxt_id, pe);
    m_srf[CF_SR_RDBACR]   = new SRegRDBACR  (ctxt_id, pe);
    m_srf[CF_SR_RDBATAG]  = new SRegRDBATAG (ctxt_id, pe);
    m_srf[CF_SR_RDBADAT0] = new SRegRDBADAT0 (ctxt_id, pe);
    m_srf[CF_SR_RDBADAT1] = new SRegRDBADAT1 (ctxt_id, pe);
    m_srf[CF_SR_RDBADAT2] = new SRegRDBADAT2 (ctxt_id, pe);
    m_srf[CF_SR_RDBADAT3] = new SRegRDBADAT3 (ctxt_id, pe);
    m_srf[CF_SR_RDBSTAT]  = new SRegRDBSTAT (ctxt_id, pe);
    // System register group 14
    m_srf[CF_SR_PMCTRL0_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 0);
    m_srf[CF_SR_PMCTRL1_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 1);
    m_srf[CF_SR_PMCTRL2_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 2);
    m_srf[CF_SR_PMCTRL3_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 3);
    m_srf[CF_SR_PMCTRL4_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 4);
    m_srf[CF_SR_PMCTRL5_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 5);
    m_srf[CF_SR_PMCTRL6_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 6);
    m_srf[CF_SR_PMCTRL7_G4MH20] = new SRegPMCTRL  (ctxt_id, pe, 7);
    m_srf[CF_SR_PMCOUNT0_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 0);
    m_srf[CF_SR_PMCOUNT1_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 1);
    m_srf[CF_SR_PMCOUNT2_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 2);
    m_srf[CF_SR_PMCOUNT3_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 3);
    m_srf[CF_SR_PMCOUNT4_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 4);
    m_srf[CF_SR_PMCOUNT5_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 5);
    m_srf[CF_SR_PMCOUNT6_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 6);
    m_srf[CF_SR_PMCOUNT7_G4MH20] = new SRegPMCOUNT (ctxt_id, pe, 7);
    // System register group 15
    m_srf[CF_SR_PMSUBCND0] = new SRegPMSUBCND (ctxt_id, pe, 0);
    m_srf[CF_SR_PMSUBCND1] = new SRegPMSUBCND (ctxt_id, pe, 1);
    m_srf[CF_SR_PMSUBCND2] = new SRegPMSUBCND (ctxt_id, pe, 2);
    m_srf[CF_SR_PMSUBCND3] = new SRegPMSUBCND (ctxt_id, pe, 3);
    m_srf[CF_SR_PMSUBCND4] = new SRegPMSUBCND (ctxt_id, pe, 4);
    m_srf[CF_SR_PMSUBCND5] = new SRegPMSUBCND (ctxt_id, pe, 5);
    m_srf[CF_SR_PMSUBCND6] = new SRegPMSUBCND (ctxt_id, pe, 6);
    m_srf[CF_SR_PMSUBCND7] = new SRegPMSUBCND (ctxt_id, pe, 7);
    // System register group 32
    m_srf[CF_SR_BPC0]     = new SRegBPC_N   (ctxt_id, pe, 0);
    m_srf[CF_SR_BPC1]     = new SRegBPC_N   (ctxt_id, pe, 1);
    m_srf[CF_SR_BPC2]     = new SRegBPC_N   (ctxt_id, pe, 2);
    m_srf[CF_SR_BPC3]     = new SRegBPC_N   (ctxt_id, pe, 3);
    m_srf[CF_SR_BPC4]     = new SRegBPC_N   (ctxt_id, pe, 4);
    m_srf[CF_SR_BPC5]     = new SRegBPC_N   (ctxt_id, pe, 5);
    m_srf[CF_SR_BPC6]     = new SRegBPC_N   (ctxt_id, pe, 6);
    m_srf[CF_SR_BPC7]     = new SRegBPC_N   (ctxt_id, pe, 7);
    m_srf[CF_SR_BPC8]     = new SRegBPC_N   (ctxt_id, pe, 8);
    m_srf[CF_SR_BPC9]     = new SRegBPC_N   (ctxt_id, pe, 9);
    m_srf[CF_SR_BPC10]    = new SRegBPC_N   (ctxt_id, pe, 10);
    m_srf[CF_SR_BPC11]    = new SRegBPC_N   (ctxt_id, pe, 11);
    // System register group 33
    m_srf[CF_SR_BPAV0]    = new SRegBPAV_N  (ctxt_id, pe, 0);
    m_srf[CF_SR_BPAV1]    = new SRegBPAV_N  (ctxt_id, pe, 1);
    m_srf[CF_SR_BPAV2]    = new SRegBPAV_N  (ctxt_id, pe, 2);
    m_srf[CF_SR_BPAV3]    = new SRegBPAV_N  (ctxt_id, pe, 3);
    m_srf[CF_SR_BPAV4]    = new SRegBPAV_N  (ctxt_id, pe, 4);
    m_srf[CF_SR_BPAV5]    = new SRegBPAV_N  (ctxt_id, pe, 5);
    m_srf[CF_SR_BPAV6]    = new SRegBPAV_N  (ctxt_id, pe, 6);
    m_srf[CF_SR_BPAV7]    = new SRegBPAV_N  (ctxt_id, pe, 7);
    m_srf[CF_SR_BPAV8]    = new SRegBPAV_N  (ctxt_id, pe, 8);
    m_srf[CF_SR_BPAV9]    = new SRegBPAV_N  (ctxt_id, pe, 9);
    m_srf[CF_SR_BPAV10]   = new SRegBPAV_N  (ctxt_id, pe, 10);
    m_srf[CF_SR_BPAV11]   = new SRegBPAV_N  (ctxt_id, pe, 11);
    // System register group 34
    m_srf[CF_SR_BPAM0]    = new SRegBPAM_N  (ctxt_id, pe, 0);
    m_srf[CF_SR_BPAM1]    = new SRegBPAM_N  (ctxt_id, pe, 1);
    m_srf[CF_SR_BPAM2]    = new SRegBPAM_N  (ctxt_id, pe, 2);
    m_srf[CF_SR_BPAM3]    = new SRegBPAM_N  (ctxt_id, pe, 3);
    m_srf[CF_SR_BPAM4]    = new SRegBPAM_N  (ctxt_id, pe, 4);
    m_srf[CF_SR_BPAM5]    = new SRegBPAM_N  (ctxt_id, pe, 5);
    m_srf[CF_SR_BPAM6]    = new SRegBPAM_N  (ctxt_id, pe, 6);
    m_srf[CF_SR_BPAM7]    = new SRegBPAM_N  (ctxt_id, pe, 7);
    m_srf[CF_SR_BPAM8]    = new SRegBPAM_N  (ctxt_id, pe, 8);
    m_srf[CF_SR_BPAM9]    = new SRegBPAM_N  (ctxt_id, pe, 9);
    m_srf[CF_SR_BPAM10]   = new SRegBPAM_N  (ctxt_id, pe, 10);
    m_srf[CF_SR_BPAM11]   = new SRegBPAM_N  (ctxt_id, pe, 11);
    // System register group 37
    m_srf[CF_SR_MPLA0]    = new SRegMPLA_N  (ctxt_id, pe, 0, 0);
    m_srf[CF_SR_MPLA1]    = new SRegMPLA_N  (ctxt_id, pe, 1, 0);
    m_srf[CF_SR_MPLA2]    = new SRegMPLA_N  (ctxt_id, pe, 2, 0);
    m_srf[CF_SR_MPLA3]    = new SRegMPLA_N  (ctxt_id, pe, 3, 0);
    m_srf[CF_SR_MPLA4]    = new SRegMPLA_N  (ctxt_id, pe, 4, 0);
    m_srf[CF_SR_MPLA5]    = new SRegMPLA_N  (ctxt_id, pe, 5, 0);
    m_srf[CF_SR_MPLA6]    = new SRegMPLA_N  (ctxt_id, pe, 6, 0);
    m_srf[CF_SR_MPLA7]    = new SRegMPLA_N  (ctxt_id, pe, 7, 0);
    m_srf[CF_SR_MPLA8]    = new SRegMPLA_N  (ctxt_id, pe, 8, 0);
    m_srf[CF_SR_MPLA9]    = new SRegMPLA_N  (ctxt_id, pe, 9, 0);
    m_srf[CF_SR_MPLA10]   = new SRegMPLA_N  (ctxt_id, pe, 10, 0);
    m_srf[CF_SR_MPLA11]   = new SRegMPLA_N  (ctxt_id, pe, 11, 0);
    m_srf[CF_SR_MPLA12]   = new SRegMPLA_N  (ctxt_id, pe, 12, 0);
    m_srf[CF_SR_MPLA13]   = new SRegMPLA_N  (ctxt_id, pe, 13, 0);
    m_srf[CF_SR_MPLA14]   = new SRegMPLA_N  (ctxt_id, pe, 14, 0);
    m_srf[CF_SR_MPLA15]   = new SRegMPLA_N  (ctxt_id, pe, 15, 0);
    m_srf[CF_SR_MPLA16]   = new SRegMPLA_N  (ctxt_id, pe, 16, 0);
    m_srf[CF_SR_MPLA17]   = new SRegMPLA_N  (ctxt_id, pe, 17, 0);
    m_srf[CF_SR_MPLA18]   = new SRegMPLA_N  (ctxt_id, pe, 18, 0);
    m_srf[CF_SR_MPLA19]   = new SRegMPLA_N  (ctxt_id, pe, 19, 0);
    m_srf[CF_SR_MPLA20]   = new SRegMPLA_N  (ctxt_id, pe, 20, 0);
    m_srf[CF_SR_MPLA21]   = new SRegMPLA_N  (ctxt_id, pe, 21, 0);
    m_srf[CF_SR_MPLA22]   = new SRegMPLA_N  (ctxt_id, pe, 22, 0);
    m_srf[CF_SR_MPLA23]   = new SRegMPLA_N  (ctxt_id, pe, 23, 0);
    m_srf[CF_SR_MPLA24]   = new SRegMPLA_N  (ctxt_id, pe, 24, 0);
    m_srf[CF_SR_MPLA25]   = new SRegMPLA_N  (ctxt_id, pe, 25, 0);
    m_srf[CF_SR_MPLA26]   = new SRegMPLA_N  (ctxt_id, pe, 26, 0);
    m_srf[CF_SR_MPLA27]   = new SRegMPLA_N  (ctxt_id, pe, 27, 0);
    m_srf[CF_SR_MPLA28]   = new SRegMPLA_N  (ctxt_id, pe, 28, 0);
    m_srf[CF_SR_MPLA29]   = new SRegMPLA_N  (ctxt_id, pe, 29, 0);
    m_srf[CF_SR_MPLA30]   = new SRegMPLA_N  (ctxt_id, pe, 30, 0);
    m_srf[CF_SR_MPLA31]   = new SRegMPLA_N  (ctxt_id, pe, 31, 0);
    // System register group 38
    m_srf[CF_SR_MPUA0]    = new SRegMPUA_N  (ctxt_id, pe, 0, 0);
    m_srf[CF_SR_MPUA1]    = new SRegMPUA_N  (ctxt_id, pe, 1, 0);
    m_srf[CF_SR_MPUA2]    = new SRegMPUA_N  (ctxt_id, pe, 2, 0);
    m_srf[CF_SR_MPUA3]    = new SRegMPUA_N  (ctxt_id, pe, 3, 0);
    m_srf[CF_SR_MPUA4]    = new SRegMPUA_N  (ctxt_id, pe, 4, 0);
    m_srf[CF_SR_MPUA5]    = new SRegMPUA_N  (ctxt_id, pe, 5, 0);
    m_srf[CF_SR_MPUA6]    = new SRegMPUA_N  (ctxt_id, pe, 6, 0);
    m_srf[CF_SR_MPUA7]    = new SRegMPUA_N  (ctxt_id, pe, 7, 0);
    m_srf[CF_SR_MPUA8]    = new SRegMPUA_N  (ctxt_id, pe, 8, 0);
    m_srf[CF_SR_MPUA9]    = new SRegMPUA_N  (ctxt_id, pe, 9, 0);
    m_srf[CF_SR_MPUA10]   = new SRegMPUA_N  (ctxt_id, pe, 10, 0);
    m_srf[CF_SR_MPUA11]   = new SRegMPUA_N  (ctxt_id, pe, 11, 0);
    m_srf[CF_SR_MPUA12]   = new SRegMPUA_N  (ctxt_id, pe, 12, 0);
    m_srf[CF_SR_MPUA13]   = new SRegMPUA_N  (ctxt_id, pe, 13, 0);
    m_srf[CF_SR_MPUA14]   = new SRegMPUA_N  (ctxt_id, pe, 14, 0);
    m_srf[CF_SR_MPUA15]   = new SRegMPUA_N  (ctxt_id, pe, 15, 0);
    m_srf[CF_SR_MPUA16]   = new SRegMPUA_N  (ctxt_id, pe, 16, 0);
    m_srf[CF_SR_MPUA17]   = new SRegMPUA_N  (ctxt_id, pe, 17, 0);
    m_srf[CF_SR_MPUA18]   = new SRegMPUA_N  (ctxt_id, pe, 18, 0);
    m_srf[CF_SR_MPUA19]   = new SRegMPUA_N  (ctxt_id, pe, 19, 0);
    m_srf[CF_SR_MPUA20]   = new SRegMPUA_N  (ctxt_id, pe, 20, 0);
    m_srf[CF_SR_MPUA21]   = new SRegMPUA_N  (ctxt_id, pe, 21, 0);
    m_srf[CF_SR_MPUA22]   = new SRegMPUA_N  (ctxt_id, pe, 22, 0);
    m_srf[CF_SR_MPUA23]   = new SRegMPUA_N  (ctxt_id, pe, 23, 0);
    m_srf[CF_SR_MPUA24]   = new SRegMPUA_N  (ctxt_id, pe, 24, 0);
    m_srf[CF_SR_MPUA25]   = new SRegMPUA_N  (ctxt_id, pe, 25, 0);
    m_srf[CF_SR_MPUA26]   = new SRegMPUA_N  (ctxt_id, pe, 26, 0);
    m_srf[CF_SR_MPUA27]   = new SRegMPUA_N  (ctxt_id, pe, 27, 0);
    m_srf[CF_SR_MPUA28]   = new SRegMPUA_N  (ctxt_id, pe, 28, 0);
    m_srf[CF_SR_MPUA29]   = new SRegMPUA_N  (ctxt_id, pe, 29, 0);
    m_srf[CF_SR_MPUA30]   = new SRegMPUA_N  (ctxt_id, pe, 30, 0);
    m_srf[CF_SR_MPUA31]   = new SRegMPUA_N  (ctxt_id, pe, 31, 0);
    // System register group 39
    m_srf[CF_SR_MPAT0]    = new SRegMPAT_N  (ctxt_id, pe, 0, 0);
    m_srf[CF_SR_MPAT1]    = new SRegMPAT_N  (ctxt_id, pe, 1, 0);
    m_srf[CF_SR_MPAT2]    = new SRegMPAT_N  (ctxt_id, pe, 2, 0);
    m_srf[CF_SR_MPAT3]    = new SRegMPAT_N  (ctxt_id, pe, 3, 0);
    m_srf[CF_SR_MPAT4]    = new SRegMPAT_N  (ctxt_id, pe, 4, 0);
    m_srf[CF_SR_MPAT5]    = new SRegMPAT_N  (ctxt_id, pe, 5, 0);
    m_srf[CF_SR_MPAT6]    = new SRegMPAT_N  (ctxt_id, pe, 6, 0);
    m_srf[CF_SR_MPAT7]    = new SRegMPAT_N  (ctxt_id, pe, 7, 0);
    m_srf[CF_SR_MPAT8]    = new SRegMPAT_N  (ctxt_id, pe, 8, 0);
    m_srf[CF_SR_MPAT9]    = new SRegMPAT_N  (ctxt_id, pe, 9, 0);
    m_srf[CF_SR_MPAT10]   = new SRegMPAT_N  (ctxt_id, pe, 10, 0);
    m_srf[CF_SR_MPAT11]   = new SRegMPAT_N  (ctxt_id, pe, 11, 0);
    m_srf[CF_SR_MPAT12]   = new SRegMPAT_N  (ctxt_id, pe, 12, 0);
    m_srf[CF_SR_MPAT13]   = new SRegMPAT_N  (ctxt_id, pe, 13, 0);
    m_srf[CF_SR_MPAT14]   = new SRegMPAT_N  (ctxt_id, pe, 14, 0);
    m_srf[CF_SR_MPAT15]   = new SRegMPAT_N  (ctxt_id, pe, 15, 0);
    m_srf[CF_SR_MPAT16]   = new SRegMPAT_N  (ctxt_id, pe, 16, 0);
    m_srf[CF_SR_MPAT17]   = new SRegMPAT_N  (ctxt_id, pe, 17, 0);
    m_srf[CF_SR_MPAT18]   = new SRegMPAT_N  (ctxt_id, pe, 18, 0);
    m_srf[CF_SR_MPAT19]   = new SRegMPAT_N  (ctxt_id, pe, 19, 0);
    m_srf[CF_SR_MPAT20]   = new SRegMPAT_N  (ctxt_id, pe, 20, 0);
    m_srf[CF_SR_MPAT21]   = new SRegMPAT_N  (ctxt_id, pe, 21, 0);
    m_srf[CF_SR_MPAT22]   = new SRegMPAT_N  (ctxt_id, pe, 22, 0);
    m_srf[CF_SR_MPAT23]   = new SRegMPAT_N  (ctxt_id, pe, 23, 0);
    m_srf[CF_SR_MPAT24]   = new SRegMPAT_N  (ctxt_id, pe, 24, 0);
    m_srf[CF_SR_MPAT25]   = new SRegMPAT_N  (ctxt_id, pe, 25, 0);
    m_srf[CF_SR_MPAT26]   = new SRegMPAT_N  (ctxt_id, pe, 26, 0);
    m_srf[CF_SR_MPAT27]   = new SRegMPAT_N  (ctxt_id, pe, 27, 0);
    m_srf[CF_SR_MPAT28]   = new SRegMPAT_N  (ctxt_id, pe, 28, 0);
    m_srf[CF_SR_MPAT29]   = new SRegMPAT_N  (ctxt_id, pe, 29, 0);
    m_srf[CF_SR_MPAT30]   = new SRegMPAT_N  (ctxt_id, pe, 30, 0);
    m_srf[CF_SR_MPAT31]   = new SRegMPAT_N  (ctxt_id, pe, 31, 0);
    // System register group 40
    m_srf[CF_SR_MPLA0_B1] = new SRegMPLA_N  (ctxt_id, pe, 0, 1);
    m_srf[CF_SR_MPLA1_B1] = new SRegMPLA_N  (ctxt_id, pe, 1, 1);
    m_srf[CF_SR_MPLA2_B1] = new SRegMPLA_N  (ctxt_id, pe, 2, 1);
    m_srf[CF_SR_MPLA3_B1] = new SRegMPLA_N  (ctxt_id, pe, 3, 1);
    m_srf[CF_SR_MPLA4_B1] = new SRegMPLA_N  (ctxt_id, pe, 4, 1);
    m_srf[CF_SR_MPLA5_B1] = new SRegMPLA_N  (ctxt_id, pe, 5, 1);
    m_srf[CF_SR_MPLA6_B1] = new SRegMPLA_N  (ctxt_id, pe, 6, 1);
    m_srf[CF_SR_MPLA7_B1] = new SRegMPLA_N  (ctxt_id, pe, 7, 1);
    m_srf[CF_SR_MPLA8_B1] = new SRegMPLA_N  (ctxt_id, pe, 8, 1);
    m_srf[CF_SR_MPLA9_B1] = new SRegMPLA_N  (ctxt_id, pe, 9, 1);
    m_srf[CF_SR_MPLA10_B1] = new SRegMPLA_N  (ctxt_id, pe, 10, 1);
    m_srf[CF_SR_MPLA11_B1] = new SRegMPLA_N  (ctxt_id, pe, 11, 1);
    m_srf[CF_SR_MPLA12_B1] = new SRegMPLA_N  (ctxt_id, pe, 12, 1);
    m_srf[CF_SR_MPLA13_B1] = new SRegMPLA_N  (ctxt_id, pe, 13, 1);
    m_srf[CF_SR_MPLA14_B1] = new SRegMPLA_N  (ctxt_id, pe, 14, 1);
    m_srf[CF_SR_MPLA15_B1] = new SRegMPLA_N  (ctxt_id, pe, 15, 1);
    m_srf[CF_SR_MPLA16_B1] = new SRegMPLA_N  (ctxt_id, pe, 16, 1);
    m_srf[CF_SR_MPLA17_B1] = new SRegMPLA_N  (ctxt_id, pe, 17, 1);
    m_srf[CF_SR_MPLA18_B1] = new SRegMPLA_N  (ctxt_id, pe, 18, 1);
    m_srf[CF_SR_MPLA19_B1] = new SRegMPLA_N  (ctxt_id, pe, 19, 1);
    m_srf[CF_SR_MPLA20_B1] = new SRegMPLA_N  (ctxt_id, pe, 20, 1);
    m_srf[CF_SR_MPLA21_B1] = new SRegMPLA_N  (ctxt_id, pe, 21, 1);
    m_srf[CF_SR_MPLA22_B1] = new SRegMPLA_N  (ctxt_id, pe, 22, 1);
    m_srf[CF_SR_MPLA23_B1] = new SRegMPLA_N  (ctxt_id, pe, 23, 1);
    m_srf[CF_SR_MPLA24_B1] = new SRegMPLA_N  (ctxt_id, pe, 24, 1);
    m_srf[CF_SR_MPLA25_B1] = new SRegMPLA_N  (ctxt_id, pe, 25, 1);
    m_srf[CF_SR_MPLA26_B1] = new SRegMPLA_N  (ctxt_id, pe, 26, 1);
    m_srf[CF_SR_MPLA27_B1] = new SRegMPLA_N  (ctxt_id, pe, 27, 1);
    m_srf[CF_SR_MPLA28_B1] = new SRegMPLA_N  (ctxt_id, pe, 28, 1);
    m_srf[CF_SR_MPLA29_B1] = new SRegMPLA_N  (ctxt_id, pe, 29, 1);
    m_srf[CF_SR_MPLA30_B1] = new SRegMPLA_N  (ctxt_id, pe, 30, 1);
    m_srf[CF_SR_MPLA31_B1] = new SRegMPLA_N  (ctxt_id, pe, 31, 1);
    // System register group 41
    m_srf[CF_SR_MPUA0_B1] = new SRegMPUA_N  (ctxt_id, pe, 0, 1);
    m_srf[CF_SR_MPUA1_B1] = new SRegMPUA_N  (ctxt_id, pe, 1, 1);
    m_srf[CF_SR_MPUA2_B1] = new SRegMPUA_N  (ctxt_id, pe, 2, 1);
    m_srf[CF_SR_MPUA3_B1] = new SRegMPUA_N  (ctxt_id, pe, 3, 1);
    m_srf[CF_SR_MPUA4_B1] = new SRegMPUA_N  (ctxt_id, pe, 4, 1);
    m_srf[CF_SR_MPUA5_B1] = new SRegMPUA_N  (ctxt_id, pe, 5, 1);
    m_srf[CF_SR_MPUA6_B1] = new SRegMPUA_N  (ctxt_id, pe, 6, 1);
    m_srf[CF_SR_MPUA7_B1] = new SRegMPUA_N  (ctxt_id, pe, 7, 1);
    m_srf[CF_SR_MPUA8_B1] = new SRegMPUA_N  (ctxt_id, pe, 8, 1);
    m_srf[CF_SR_MPUA9_B1] = new SRegMPUA_N  (ctxt_id, pe, 9, 1);
    m_srf[CF_SR_MPUA10_B1] = new SRegMPUA_N  (ctxt_id, pe, 10, 1);
    m_srf[CF_SR_MPUA11_B1] = new SRegMPUA_N  (ctxt_id, pe, 11, 1);
    m_srf[CF_SR_MPUA12_B1] = new SRegMPUA_N  (ctxt_id, pe, 12, 1);
    m_srf[CF_SR_MPUA13_B1] = new SRegMPUA_N  (ctxt_id, pe, 13, 1);
    m_srf[CF_SR_MPUA14_B1] = new SRegMPUA_N  (ctxt_id, pe, 14, 1);
    m_srf[CF_SR_MPUA15_B1] = new SRegMPUA_N  (ctxt_id, pe, 15, 1);
    m_srf[CF_SR_MPUA16_B1] = new SRegMPUA_N  (ctxt_id, pe, 16, 1);
    m_srf[CF_SR_MPUA17_B1] = new SRegMPUA_N  (ctxt_id, pe, 17, 1);
    m_srf[CF_SR_MPUA18_B1] = new SRegMPUA_N  (ctxt_id, pe, 18, 1);
    m_srf[CF_SR_MPUA19_B1] = new SRegMPUA_N  (ctxt_id, pe, 19, 1);
    m_srf[CF_SR_MPUA20_B1] = new SRegMPUA_N  (ctxt_id, pe, 20, 1);
    m_srf[CF_SR_MPUA21_B1] = new SRegMPUA_N  (ctxt_id, pe, 21, 1);
    m_srf[CF_SR_MPUA22_B1] = new SRegMPUA_N  (ctxt_id, pe, 22, 1);
    m_srf[CF_SR_MPUA23_B1] = new SRegMPUA_N  (ctxt_id, pe, 23, 1);
    m_srf[CF_SR_MPUA24_B1] = new SRegMPUA_N  (ctxt_id, pe, 24, 1);
    m_srf[CF_SR_MPUA25_B1] = new SRegMPUA_N  (ctxt_id, pe, 25, 1);
    m_srf[CF_SR_MPUA26_B1] = new SRegMPUA_N  (ctxt_id, pe, 26, 1);
    m_srf[CF_SR_MPUA27_B1] = new SRegMPUA_N  (ctxt_id, pe, 27, 1);
    m_srf[CF_SR_MPUA28_B1] = new SRegMPUA_N  (ctxt_id, pe, 28, 1);
    m_srf[CF_SR_MPUA29_B1] = new SRegMPUA_N  (ctxt_id, pe, 29, 1);
    m_srf[CF_SR_MPUA30_B1] = new SRegMPUA_N  (ctxt_id, pe, 30, 1);
    m_srf[CF_SR_MPUA31_B1] = new SRegMPUA_N  (ctxt_id, pe, 31, 1);
    // System register group 42
    m_srf[CF_SR_MPAT0_B1] = new SRegMPAT_N  (ctxt_id, pe, 0, 1);
    m_srf[CF_SR_MPAT1_B1] = new SRegMPAT_N  (ctxt_id, pe, 1, 1);
    m_srf[CF_SR_MPAT2_B1] = new SRegMPAT_N  (ctxt_id, pe, 2, 1);
    m_srf[CF_SR_MPAT3_B1] = new SRegMPAT_N  (ctxt_id, pe, 3, 1);
    m_srf[CF_SR_MPAT4_B1] = new SRegMPAT_N  (ctxt_id, pe, 4, 1);
    m_srf[CF_SR_MPAT5_B1] = new SRegMPAT_N  (ctxt_id, pe, 5, 1);
    m_srf[CF_SR_MPAT6_B1] = new SRegMPAT_N  (ctxt_id, pe, 6, 1);
    m_srf[CF_SR_MPAT7_B1] = new SRegMPAT_N  (ctxt_id, pe, 7, 1);
    m_srf[CF_SR_MPAT8_B1] = new SRegMPAT_N  (ctxt_id, pe, 8, 1);
    m_srf[CF_SR_MPAT9_B1] = new SRegMPAT_N  (ctxt_id, pe, 9, 1);
    m_srf[CF_SR_MPAT10_B1] = new SRegMPAT_N  (ctxt_id, pe, 10, 1);
    m_srf[CF_SR_MPAT11_B1] = new SRegMPAT_N  (ctxt_id, pe, 11, 1);
    m_srf[CF_SR_MPAT12_B1] = new SRegMPAT_N  (ctxt_id, pe, 12, 1);
    m_srf[CF_SR_MPAT13_B1] = new SRegMPAT_N  (ctxt_id, pe, 13, 1);
    m_srf[CF_SR_MPAT14_B1] = new SRegMPAT_N  (ctxt_id, pe, 14, 1);
    m_srf[CF_SR_MPAT15_B1] = new SRegMPAT_N  (ctxt_id, pe, 15, 1);
    m_srf[CF_SR_MPAT16_B1] = new SRegMPAT_N  (ctxt_id, pe, 16, 1);
    m_srf[CF_SR_MPAT17_B1] = new SRegMPAT_N  (ctxt_id, pe, 17, 1);
    m_srf[CF_SR_MPAT18_B1] = new SRegMPAT_N  (ctxt_id, pe, 18, 1);
    m_srf[CF_SR_MPAT19_B1] = new SRegMPAT_N  (ctxt_id, pe, 19, 1);
    m_srf[CF_SR_MPAT20_B1] = new SRegMPAT_N  (ctxt_id, pe, 20, 1);
    m_srf[CF_SR_MPAT21_B1] = new SRegMPAT_N  (ctxt_id, pe, 21, 1);
    m_srf[CF_SR_MPAT22_B1] = new SRegMPAT_N  (ctxt_id, pe, 22, 1);
    m_srf[CF_SR_MPAT23_B1] = new SRegMPAT_N  (ctxt_id, pe, 23, 1);
    m_srf[CF_SR_MPAT24_B1] = new SRegMPAT_N  (ctxt_id, pe, 24, 1);
    m_srf[CF_SR_MPAT25_B1] = new SRegMPAT_N  (ctxt_id, pe, 25, 1);
    m_srf[CF_SR_MPAT26_B1] = new SRegMPAT_N  (ctxt_id, pe, 26, 1);
    m_srf[CF_SR_MPAT27_B1] = new SRegMPAT_N  (ctxt_id, pe, 27, 1);
    m_srf[CF_SR_MPAT28_B1] = new SRegMPAT_N  (ctxt_id, pe, 28, 1);
    m_srf[CF_SR_MPAT29_B1] = new SRegMPAT_N  (ctxt_id, pe, 29, 1);
    m_srf[CF_SR_MPAT30_B1] = new SRegMPAT_N  (ctxt_id, pe, 30, 1);
    m_srf[CF_SR_MPAT31_B1] = new SRegMPAT_N  (ctxt_id, pe, 31, 1);
    break;

    default:
        break;
    }
}


void RegID::InitIdMap (void)
{
    if (m_cfsrid_map.size() != 0) return;

    // System register group 0
    AddSRegIdMap ( 0,  0, CF_SR_HMEIPC);
    AddSRegIdMap ( 0,  1, CF_SR_HMEIPSW);
    AddSRegIdMap ( 0,  2, CF_SR_HMFEPC);
    AddSRegIdMap ( 0,  3, CF_SR_HMFEPSW);
    AddSRegIdMap ( 0,  5, CF_SR_HMPSW);
    AddSRegIdMap ( 0,  6, CF_SR_FPSR);
    AddSRegIdMap ( 0,  7, CF_SR_FPEPC);
    AddSRegIdMap ( 0,  8, CF_SR_FPST);
    AddSRegIdMap ( 0,  9, CF_SR_FPCC);
    AddSRegIdMap ( 0, 10, CF_SR_FPCFG);
    AddSRegIdMap ( 0, 11, CF_SR_FPEC);
    AddSRegIdMap ( 0, 13, CF_SR_HMEIIC);
    AddSRegIdMap ( 0, 14, CF_SR_HMFEIC);
    AddSRegIdMap ( 0, 15, CF_SR_PSWH);
    AddSRegIdMap ( 0, 16, CF_SR_CTPC);
    AddSRegIdMap ( 0, 17, CF_SR_CTPSW);
    AddSRegIdMap ( 0, 18, CF_SR_EIPSWH);
    AddSRegIdMap ( 0, 19, CF_SR_FEPSWH);
    AddSRegIdMap ( 0, 20, CF_SR_CTBP);
    AddSRegIdMap ( 0, 21, CF_SR_SNZCFG);
    AddSRegIdMap ( 0, 28, CF_SR_HMEIWR);
    AddSRegIdMap ( 0, 29, CF_SR_HMFEWR);
    // System register group 1
    AddSRegIdMap ( 1,  0, CF_SR_HMSPID);
    AddSRegIdMap ( 1,  1, CF_SR_HMSPIDLIST);
    AddSRegIdMap ( 1,  2, CF_SR_RBASE);
    AddSRegIdMap ( 1,  3, CF_SR_HMEBASE);
    AddSRegIdMap ( 1,  4, CF_SR_HMINTBP);
    AddSRegIdMap ( 1,  5, CF_SR_MCTL);
    AddSRegIdMap ( 1,  6, CF_SR_PID);
    AddSRegIdMap ( 1,  7, CF_SR_FPIPR);
    AddSRegIdMap ( 1,  8, CF_SR_HMSVLOCK);
    AddSRegIdMap ( 1, 11, CF_SR_SCCFG);
    AddSRegIdMap ( 1, 12, CF_SR_SCBP);
    AddSRegIdMap ( 1, 16, CF_SR_HVCFG);
    AddSRegIdMap ( 1, 17, CF_SR_GMCFG);
    AddSRegIdMap ( 1, 20, CF_SR_HVSB);
    // System register group 2
    AddSRegIdMap ( 2,  0, CF_SR_HMPEID);
    AddSRegIdMap ( 2,  1, CF_SR_BMID);
    AddSRegIdMap ( 2,  6, CF_SR_HMMEA);
    AddSRegIdMap ( 2,  8, CF_SR_HMMEI);
    AddSRegIdMap ( 2, 10, CF_SR_ISPR);
    AddSRegIdMap ( 2, 11, CF_SR_IMSR);
    AddSRegIdMap ( 2, 12, CF_SR_ICSR);
    AddSRegIdMap ( 2, 13, CF_SR_HMINTCFG);
    AddSRegIdMap ( 2, 14, CF_SR_HMPLMR);
    AddSRegIdMap ( 2, 15, CF_SR_RBCR0);
    AddSRegIdMap ( 2, 16, CF_SR_RBCR1);
    AddSRegIdMap ( 2, 17, CF_SR_RBNR);
    AddSRegIdMap ( 2, 18, CF_SR_RBIP);
    // System register group 3
    AddSRegIdMap ( 3,  0, CF_SR_DBGEN);
    AddSRegIdMap ( 3, 13, CF_SR_DBPSWH);
    AddSRegIdMap ( 3, 15, CF_SR_DBIC);
    AddSRegIdMap ( 3, 18, CF_SR_DBPC);
    AddSRegIdMap ( 3, 19, CF_SR_DBPSW);
    AddSRegIdMap ( 3, 20, CF_SR_DIR0);
    AddSRegIdMap ( 3, 21, CF_SR_DIR1);
    AddSRegIdMap ( 3, 22, CF_SR_BPC);
    AddSRegIdMap ( 3, 24, CF_SR_BPAV);
    AddSRegIdMap ( 3, 25, CF_SR_BPAM);
    AddSRegIdMap ( 3, 28, CF_SR_DBCFG);
    AddSRegIdMap ( 3, 30, CF_SR_DBWR);
    // System register group 4
    AddSRegIdMap ( 4, 16, CF_SR_ICTAGL);
    AddSRegIdMap ( 4, 17, CF_SR_ICTAGH);
    AddSRegIdMap ( 4, 18, CF_SR_ICDATL);
    AddSRegIdMap ( 4, 19, CF_SR_ICDATH);
    AddSRegIdMap ( 4, 24, CF_SR_ICCTRL);
    AddSRegIdMap ( 4, 26, CF_SR_ICCFG);
    AddSRegIdMap ( 4, 28, CF_SR_ICERR);
    // System register group 5
    AddSRegIdMap ( 5,  0, CF_SR_HMMPM);
    AddSRegIdMap ( 5,  2, CF_SR_MPCFG);
    AddSRegIdMap ( 5,  8, CF_SR_MCA);
    AddSRegIdMap ( 5,  9, CF_SR_MCS);
    AddSRegIdMap ( 5, 10, CF_SR_MCC);
    AddSRegIdMap ( 5, 11, CF_SR_MCR);
    AddSRegIdMap ( 5, 12, CF_SR_MCI);
    AddSRegIdMap ( 5, 16, CF_SR_MPIDX);
    AddSRegIdMap ( 5, 17, CF_SR_MPBK);
    AddSRegIdMap ( 5, 20, CF_SR_MPLA);
    AddSRegIdMap ( 5, 21, CF_SR_MPUA);
    AddSRegIdMap ( 5, 22, CF_SR_MPAT);
    AddSRegIdMap ( 5, 24, CF_SR_MPID0);
    AddSRegIdMap ( 5, 25, CF_SR_MPID1);
    AddSRegIdMap ( 5, 26, CF_SR_MPID2);
    AddSRegIdMap ( 5, 27, CF_SR_MPID3);
    AddSRegIdMap ( 5, 28, CF_SR_MPID4);
    AddSRegIdMap ( 5, 29, CF_SR_MPID5);
    AddSRegIdMap ( 5, 30, CF_SR_MPID6);
    AddSRegIdMap ( 5, 31, CF_SR_MPID7);
    // System register group 9
    AddSRegIdMap ( 9,  0, CF_SR_GMEIPC);
    AddSRegIdMap ( 9,  1, CF_SR_GMEIPSW);
    AddSRegIdMap ( 9,  2, CF_SR_GMFEPC);
    AddSRegIdMap ( 9,  3, CF_SR_GMFEPSW);
    AddSRegIdMap ( 9,  5, CF_SR_GMPSW);
    AddSRegIdMap ( 9,  6, CF_SR_GMMEA);
    AddSRegIdMap ( 9,  8, CF_SR_GMMEI);
    AddSRegIdMap ( 9, 13, CF_SR_GMEIIC);
    AddSRegIdMap ( 9, 14, CF_SR_GMFEIC);
    AddSRegIdMap ( 9, 16, CF_SR_GMSPID);
    AddSRegIdMap ( 9, 17, CF_SR_GMSPIDLIST);
    AddSRegIdMap ( 9, 19, CF_SR_GMEBASE);
    AddSRegIdMap ( 9, 20, CF_SR_GMINTBP);
    AddSRegIdMap ( 9, 21, CF_SR_GMINTCFG);
    AddSRegIdMap ( 9, 22, CF_SR_GMPLMR);
    AddSRegIdMap ( 9, 24, CF_SR_GMSVLOCK);
    AddSRegIdMap ( 9, 25, CF_SR_GMMPM);
    AddSRegIdMap ( 9, 28, CF_SR_GMEIWR);
    AddSRegIdMap ( 9, 29, CF_SR_GMFEWR);
    AddSRegIdMap ( 9, 30, CF_SR_GMPEID);
    // System register group 10
    AddSRegIdMap (10,  6, CF_SR_FXSR);
    AddSRegIdMap (10,  8, CF_SR_FXST);
    AddSRegIdMap (10,  9, CF_SR_FXINFO);
    AddSRegIdMap (10, 10, CF_SR_FXCFG);
    AddSRegIdMap (10, 12, CF_SR_FXXC);
    AddSRegIdMap (10, 13, CF_SR_FXXP);
    // System register group 11
    AddSRegIdMap (11,  0, CF_SR_TSCOUNTL);
    AddSRegIdMap (11,  1, CF_SR_TSCOUNTH);
    AddSRegIdMap (11,  2, CF_SR_TSCTRL);
    AddSRegIdMap (11,  8, CF_SR_PMUMCTRL);
    AddSRegIdMap (11,  9, CF_SR_PMGMCTRL);
    AddSRegIdMap (11, 16, CF_SR_PMCOUNT0_G4X1X);
    AddSRegIdMap (11, 17, CF_SR_PMCTRL0_G4X1X);
    AddSRegIdMap (11, 18, CF_SR_PMCOUNT1_G4X1X);
    AddSRegIdMap (11, 19, CF_SR_PMCTRL1_G4X1X);
    AddSRegIdMap (11, 20, CF_SR_PMCOUNT2_G4X1X);
    AddSRegIdMap (11, 21, CF_SR_PMCTRL2_G4X1X);
    AddSRegIdMap (11, 22, CF_SR_PMCOUNT3_G4X1X);
    AddSRegIdMap (11, 23, CF_SR_PMCTRL3_G4X1X);
    // System register group 12
    AddSRegIdMap (12,  0, CF_SR_LSTEST0);
    AddSRegIdMap (12,  1, CF_SR_LSTEST1);
    AddSRegIdMap (12,  2, CF_SR_LSCFG);
    AddSRegIdMap (12,  4, CF_SR_ICBKEY);
    AddSRegIdMap (12,  5, CF_SR_IFCR);
    AddSRegIdMap (12,  6, CF_SR_IFCR1);
    AddSRegIdMap (12,  8, CF_SR_BRPCTRL0);
    AddSRegIdMap (12,  9, CF_SR_BRPCTRL1);
    AddSRegIdMap (12, 10, CF_SR_BRPCFG);
    AddSRegIdMap (12, 11, CF_SR_BRPACTRL);
    AddSRegIdMap (12, 12, CF_SR_BRPDATA);
    // System register group 13
    AddSRegIdMap (13,  0, CF_SR_DCBKEY);
    AddSRegIdMap (13,  1, CF_SR_LSUCR);
    AddSRegIdMap (13,  2, CF_SR_LSULNK0);
    AddSRegIdMap (13,  3, CF_SR_LSULNK1);
    AddSRegIdMap (13,  8, CF_SR_L1RLCR);
    AddSRegIdMap (13,  9, CF_SR_L1RLNK0);
    AddSRegIdMap (13, 10, CF_SR_L1RLNK1);
    AddSRegIdMap (13, 12, CF_SR_L1RCFG);
    AddSRegIdMap (13, 16, CF_SR_DECFG);
    AddSRegIdMap (13, 17, CF_SR_DECTRL);
    AddSRegIdMap (13, 18, CF_SR_DEVDS);
    AddSRegIdMap (13, 24, CF_SR_RDBCR);
    AddSRegIdMap (13, 25, CF_SR_RDBACR);
    AddSRegIdMap (13, 26, CF_SR_RDBATAG);
    AddSRegIdMap (13, 27, CF_SR_RDBADAT0);
    AddSRegIdMap (13, 28, CF_SR_RDBADAT1);
    AddSRegIdMap (13, 29, CF_SR_RDBADAT2);
    AddSRegIdMap (13, 30, CF_SR_RDBADAT3);
    AddSRegIdMap (13, 31, CF_SR_RDBSTAT);
    // System register group 14
    AddSRegIdMap (14,  0, CF_SR_PMCTRL0_G4MH20);
    AddSRegIdMap (14,  1, CF_SR_PMCTRL1_G4MH20);
    AddSRegIdMap (14,  2, CF_SR_PMCTRL2_G4MH20);
    AddSRegIdMap (14,  3, CF_SR_PMCTRL3_G4MH20);
    AddSRegIdMap (14,  4, CF_SR_PMCTRL4_G4MH20);
    AddSRegIdMap (14,  5, CF_SR_PMCTRL5_G4MH20);
    AddSRegIdMap (14,  6, CF_SR_PMCTRL6_G4MH20);
    AddSRegIdMap (14,  7, CF_SR_PMCTRL7_G4MH20);
    AddSRegIdMap (14, 16, CF_SR_PMCOUNT0_G4MH20);
    AddSRegIdMap (14, 17, CF_SR_PMCOUNT1_G4MH20);
    AddSRegIdMap (14, 18, CF_SR_PMCOUNT2_G4MH20);
    AddSRegIdMap (14, 19, CF_SR_PMCOUNT3_G4MH20);
    AddSRegIdMap (14, 20, CF_SR_PMCOUNT4_G4MH20);
    AddSRegIdMap (14, 21, CF_SR_PMCOUNT5_G4MH20);
    AddSRegIdMap (14, 22, CF_SR_PMCOUNT6_G4MH20);
    AddSRegIdMap (14, 23, CF_SR_PMCOUNT7_G4MH20);
    // System register group 15
    AddSRegIdMap (15,  0, CF_SR_PMSUBCND0);
    AddSRegIdMap (15,  1, CF_SR_PMSUBCND1);
    AddSRegIdMap (15,  2, CF_SR_PMSUBCND2);
    AddSRegIdMap (15,  3, CF_SR_PMSUBCND3);
    AddSRegIdMap (15,  4, CF_SR_PMSUBCND4);
    AddSRegIdMap (15,  5, CF_SR_PMSUBCND5);
    AddSRegIdMap (15,  6, CF_SR_PMSUBCND6);
    AddSRegIdMap (15,  7, CF_SR_PMSUBCND7);
    // System register group 32
    AddSRegIdMap (32,  0, CF_SR_BPC0);
    AddSRegIdMap (32,  1, CF_SR_BPC1);
    AddSRegIdMap (32,  2, CF_SR_BPC2);
    AddSRegIdMap (32,  3, CF_SR_BPC3);
    AddSRegIdMap (32,  4, CF_SR_BPC4);
    AddSRegIdMap (32,  5, CF_SR_BPC5);
    AddSRegIdMap (32,  6, CF_SR_BPC6);
    AddSRegIdMap (32,  7, CF_SR_BPC7);
    AddSRegIdMap (32,  8, CF_SR_BPC8);
    AddSRegIdMap (32,  9, CF_SR_BPC9);
    AddSRegIdMap (32, 10, CF_SR_BPC10);
    AddSRegIdMap (32, 11, CF_SR_BPC11);
    // System register group 33
    AddSRegIdMap (33,  0, CF_SR_BPAV0);
    AddSRegIdMap (33,  1, CF_SR_BPAV1);
    AddSRegIdMap (33,  2, CF_SR_BPAV2);
    AddSRegIdMap (33,  3, CF_SR_BPAV3);
    AddSRegIdMap (33,  4, CF_SR_BPAV4);
    AddSRegIdMap (33,  5, CF_SR_BPAV5);
    AddSRegIdMap (33,  6, CF_SR_BPAV6);
    AddSRegIdMap (33,  7, CF_SR_BPAV7);
    AddSRegIdMap (33,  8, CF_SR_BPAV8);
    AddSRegIdMap (33,  9, CF_SR_BPAV9);
    AddSRegIdMap (33, 10, CF_SR_BPAV10);
    AddSRegIdMap (33, 11, CF_SR_BPAV11);
    // System register group 34
    AddSRegIdMap (34,  0, CF_SR_BPAM0);
    AddSRegIdMap (34,  1, CF_SR_BPAM1);
    AddSRegIdMap (34,  2, CF_SR_BPAM2);
    AddSRegIdMap (34,  3, CF_SR_BPAM3);
    AddSRegIdMap (34,  4, CF_SR_BPAM4);
    AddSRegIdMap (34,  5, CF_SR_BPAM5);
    AddSRegIdMap (34,  6, CF_SR_BPAM6);
    AddSRegIdMap (34,  7, CF_SR_BPAM7);
    AddSRegIdMap (34,  8, CF_SR_BPAM8);
    AddSRegIdMap (34,  9, CF_SR_BPAM9);
    AddSRegIdMap (34, 10, CF_SR_BPAM10);
    AddSRegIdMap (34, 11, CF_SR_BPAM11);
    // System register group 37
    AddSRegIdMap (37,  0, CF_SR_MPLA0);
    AddSRegIdMap (37,  1, CF_SR_MPLA1);
    AddSRegIdMap (37,  2, CF_SR_MPLA2);
    AddSRegIdMap (37,  3, CF_SR_MPLA3);
    AddSRegIdMap (37,  4, CF_SR_MPLA4);
    AddSRegIdMap (37,  5, CF_SR_MPLA5);
    AddSRegIdMap (37,  6, CF_SR_MPLA6);
    AddSRegIdMap (37,  7, CF_SR_MPLA7);
    AddSRegIdMap (37,  8, CF_SR_MPLA8);
    AddSRegIdMap (37,  9, CF_SR_MPLA9);
    AddSRegIdMap (37, 10, CF_SR_MPLA10);
    AddSRegIdMap (37, 11, CF_SR_MPLA11);
    AddSRegIdMap (37, 12, CF_SR_MPLA12);
    AddSRegIdMap (37, 13, CF_SR_MPLA13);
    AddSRegIdMap (37, 14, CF_SR_MPLA14);
    AddSRegIdMap (37, 15, CF_SR_MPLA15);
    AddSRegIdMap (37, 16, CF_SR_MPLA16);
    AddSRegIdMap (37, 17, CF_SR_MPLA17);
    AddSRegIdMap (37, 18, CF_SR_MPLA18);
    AddSRegIdMap (37, 19, CF_SR_MPLA19);
    AddSRegIdMap (37, 20, CF_SR_MPLA20);
    AddSRegIdMap (37, 21, CF_SR_MPLA21);
    AddSRegIdMap (37, 22, CF_SR_MPLA22);
    AddSRegIdMap (37, 23, CF_SR_MPLA23);
    AddSRegIdMap (37, 24, CF_SR_MPLA24);
    AddSRegIdMap (37, 25, CF_SR_MPLA25);
    AddSRegIdMap (37, 26, CF_SR_MPLA26);
    AddSRegIdMap (37, 27, CF_SR_MPLA27);
    AddSRegIdMap (37, 28, CF_SR_MPLA28);
    AddSRegIdMap (37, 29, CF_SR_MPLA29);
    AddSRegIdMap (37, 30, CF_SR_MPLA30);
    AddSRegIdMap (37, 31, CF_SR_MPLA31);
    // System register group 38
    AddSRegIdMap (38,  0, CF_SR_MPUA0);
    AddSRegIdMap (38,  1, CF_SR_MPUA1);
    AddSRegIdMap (38,  2, CF_SR_MPUA2);
    AddSRegIdMap (38,  3, CF_SR_MPUA3);
    AddSRegIdMap (38,  4, CF_SR_MPUA4);
    AddSRegIdMap (38,  5, CF_SR_MPUA5);
    AddSRegIdMap (38,  6, CF_SR_MPUA6);
    AddSRegIdMap (38,  7, CF_SR_MPUA7);
    AddSRegIdMap (38,  8, CF_SR_MPUA8);
    AddSRegIdMap (38,  9, CF_SR_MPUA9);
    AddSRegIdMap (38, 10, CF_SR_MPUA10);
    AddSRegIdMap (38, 11, CF_SR_MPUA11);
    AddSRegIdMap (38, 12, CF_SR_MPUA12);
    AddSRegIdMap (38, 13, CF_SR_MPUA13);
    AddSRegIdMap (38, 14, CF_SR_MPUA14);
    AddSRegIdMap (38, 15, CF_SR_MPUA15);
    AddSRegIdMap (38, 16, CF_SR_MPUA16);
    AddSRegIdMap (38, 17, CF_SR_MPUA17);
    AddSRegIdMap (38, 18, CF_SR_MPUA18);
    AddSRegIdMap (38, 19, CF_SR_MPUA19);
    AddSRegIdMap (38, 20, CF_SR_MPUA20);
    AddSRegIdMap (38, 21, CF_SR_MPUA21);
    AddSRegIdMap (38, 22, CF_SR_MPUA22);
    AddSRegIdMap (38, 23, CF_SR_MPUA23);
    AddSRegIdMap (38, 24, CF_SR_MPUA24);
    AddSRegIdMap (38, 25, CF_SR_MPUA25);
    AddSRegIdMap (38, 26, CF_SR_MPUA26);
    AddSRegIdMap (38, 27, CF_SR_MPUA27);
    AddSRegIdMap (38, 28, CF_SR_MPUA28);
    AddSRegIdMap (38, 29, CF_SR_MPUA29);
    AddSRegIdMap (38, 30, CF_SR_MPUA30);
    AddSRegIdMap (38, 31, CF_SR_MPUA31);
    // System register group 39
    AddSRegIdMap (39,  0, CF_SR_MPAT0);
    AddSRegIdMap (39,  1, CF_SR_MPAT1);
    AddSRegIdMap (39,  2, CF_SR_MPAT2);
    AddSRegIdMap (39,  3, CF_SR_MPAT3);
    AddSRegIdMap (39,  4, CF_SR_MPAT4);
    AddSRegIdMap (39,  5, CF_SR_MPAT5);
    AddSRegIdMap (39,  6, CF_SR_MPAT6);
    AddSRegIdMap (39,  7, CF_SR_MPAT7);
    AddSRegIdMap (39,  8, CF_SR_MPAT8);
    AddSRegIdMap (39,  9, CF_SR_MPAT9);
    AddSRegIdMap (39, 10, CF_SR_MPAT10);
    AddSRegIdMap (39, 11, CF_SR_MPAT11);
    AddSRegIdMap (39, 12, CF_SR_MPAT12);
    AddSRegIdMap (39, 13, CF_SR_MPAT13);
    AddSRegIdMap (39, 14, CF_SR_MPAT14);
    AddSRegIdMap (39, 15, CF_SR_MPAT15);
    AddSRegIdMap (39, 16, CF_SR_MPAT16);
    AddSRegIdMap (39, 17, CF_SR_MPAT17);
    AddSRegIdMap (39, 18, CF_SR_MPAT18);
    AddSRegIdMap (39, 19, CF_SR_MPAT19);
    AddSRegIdMap (39, 20, CF_SR_MPAT20);
    AddSRegIdMap (39, 21, CF_SR_MPAT21);
    AddSRegIdMap (39, 22, CF_SR_MPAT22);
    AddSRegIdMap (39, 23, CF_SR_MPAT23);
    AddSRegIdMap (39, 24, CF_SR_MPAT24);
    AddSRegIdMap (39, 25, CF_SR_MPAT25);
    AddSRegIdMap (39, 26, CF_SR_MPAT26);
    AddSRegIdMap (39, 27, CF_SR_MPAT27);
    AddSRegIdMap (39, 28, CF_SR_MPAT28);
    AddSRegIdMap (39, 29, CF_SR_MPAT29);
    AddSRegIdMap (39, 30, CF_SR_MPAT30);
    AddSRegIdMap (39, 31, CF_SR_MPAT31);
    // System register group 40
    AddSRegIdMap (40,  0, CF_SR_MPLA0_B1);
    AddSRegIdMap (40,  1, CF_SR_MPLA1_B1);
    AddSRegIdMap (40,  2, CF_SR_MPLA2_B1);
    AddSRegIdMap (40,  3, CF_SR_MPLA3_B1);
    AddSRegIdMap (40,  4, CF_SR_MPLA4_B1);
    AddSRegIdMap (40,  5, CF_SR_MPLA5_B1);
    AddSRegIdMap (40,  6, CF_SR_MPLA6_B1);
    AddSRegIdMap (40,  7, CF_SR_MPLA7_B1);
    AddSRegIdMap (40,  8, CF_SR_MPLA8_B1);
    AddSRegIdMap (40,  9, CF_SR_MPLA9_B1);
    AddSRegIdMap (40, 10, CF_SR_MPLA10_B1);
    AddSRegIdMap (40, 11, CF_SR_MPLA11_B1);
    AddSRegIdMap (40, 12, CF_SR_MPLA12_B1);
    AddSRegIdMap (40, 13, CF_SR_MPLA13_B1);
    AddSRegIdMap (40, 14, CF_SR_MPLA14_B1);
    AddSRegIdMap (40, 15, CF_SR_MPLA15_B1);
    AddSRegIdMap (40, 16, CF_SR_MPLA16_B1);
    AddSRegIdMap (40, 17, CF_SR_MPLA17_B1);
    AddSRegIdMap (40, 18, CF_SR_MPLA18_B1);
    AddSRegIdMap (40, 19, CF_SR_MPLA19_B1);
    AddSRegIdMap (40, 20, CF_SR_MPLA20_B1);
    AddSRegIdMap (40, 21, CF_SR_MPLA21_B1);
    AddSRegIdMap (40, 22, CF_SR_MPLA22_B1);
    AddSRegIdMap (40, 23, CF_SR_MPLA23_B1);
    AddSRegIdMap (40, 24, CF_SR_MPLA24_B1);
    AddSRegIdMap (40, 25, CF_SR_MPLA25_B1);
    AddSRegIdMap (40, 26, CF_SR_MPLA26_B1);
    AddSRegIdMap (40, 27, CF_SR_MPLA27_B1);
    AddSRegIdMap (40, 28, CF_SR_MPLA28_B1);
    AddSRegIdMap (40, 29, CF_SR_MPLA29_B1);
    AddSRegIdMap (40, 30, CF_SR_MPLA30_B1);
    AddSRegIdMap (40, 31, CF_SR_MPLA31_B1);
    // System register group 41
    AddSRegIdMap (41,  0, CF_SR_MPUA0_B1);
    AddSRegIdMap (41,  1, CF_SR_MPUA1_B1);
    AddSRegIdMap (41,  2, CF_SR_MPUA2_B1);
    AddSRegIdMap (41,  3, CF_SR_MPUA3_B1);
    AddSRegIdMap (41,  4, CF_SR_MPUA4_B1);
    AddSRegIdMap (41,  5, CF_SR_MPUA5_B1);
    AddSRegIdMap (41,  6, CF_SR_MPUA6_B1);
    AddSRegIdMap (41,  7, CF_SR_MPUA7_B1);
    AddSRegIdMap (41,  8, CF_SR_MPUA8_B1);
    AddSRegIdMap (41,  9, CF_SR_MPUA9_B1);
    AddSRegIdMap (41, 10, CF_SR_MPUA10_B1);
    AddSRegIdMap (41, 11, CF_SR_MPUA11_B1);
    AddSRegIdMap (41, 12, CF_SR_MPUA12_B1);
    AddSRegIdMap (41, 13, CF_SR_MPUA13_B1);
    AddSRegIdMap (41, 14, CF_SR_MPUA14_B1);
    AddSRegIdMap (41, 15, CF_SR_MPUA15_B1);
    AddSRegIdMap (41, 16, CF_SR_MPUA16_B1);
    AddSRegIdMap (41, 17, CF_SR_MPUA17_B1);
    AddSRegIdMap (41, 18, CF_SR_MPUA18_B1);
    AddSRegIdMap (41, 19, CF_SR_MPUA19_B1);
    AddSRegIdMap (41, 20, CF_SR_MPUA20_B1);
    AddSRegIdMap (41, 21, CF_SR_MPUA21_B1);
    AddSRegIdMap (41, 22, CF_SR_MPUA22_B1);
    AddSRegIdMap (41, 23, CF_SR_MPUA23_B1);
    AddSRegIdMap (41, 24, CF_SR_MPUA24_B1);
    AddSRegIdMap (41, 25, CF_SR_MPUA25_B1);
    AddSRegIdMap (41, 26, CF_SR_MPUA26_B1);
    AddSRegIdMap (41, 27, CF_SR_MPUA27_B1);
    AddSRegIdMap (41, 28, CF_SR_MPUA28_B1);
    AddSRegIdMap (41, 29, CF_SR_MPUA29_B1);
    AddSRegIdMap (41, 30, CF_SR_MPUA30_B1);
    AddSRegIdMap (41, 31, CF_SR_MPUA31_B1);
    // System register group 42
    AddSRegIdMap (42,  0, CF_SR_MPAT0_B1);
    AddSRegIdMap (42,  1, CF_SR_MPAT1_B1);
    AddSRegIdMap (42,  2, CF_SR_MPAT2_B1);
    AddSRegIdMap (42,  3, CF_SR_MPAT3_B1);
    AddSRegIdMap (42,  4, CF_SR_MPAT4_B1);
    AddSRegIdMap (42,  5, CF_SR_MPAT5_B1);
    AddSRegIdMap (42,  6, CF_SR_MPAT6_B1);
    AddSRegIdMap (42,  7, CF_SR_MPAT7_B1);
    AddSRegIdMap (42,  8, CF_SR_MPAT8_B1);
    AddSRegIdMap (42,  9, CF_SR_MPAT9_B1);
    AddSRegIdMap (42, 10, CF_SR_MPAT10_B1);
    AddSRegIdMap (42, 11, CF_SR_MPAT11_B1);
    AddSRegIdMap (42, 12, CF_SR_MPAT12_B1);
    AddSRegIdMap (42, 13, CF_SR_MPAT13_B1);
    AddSRegIdMap (42, 14, CF_SR_MPAT14_B1);
    AddSRegIdMap (42, 15, CF_SR_MPAT15_B1);
    AddSRegIdMap (42, 16, CF_SR_MPAT16_B1);
    AddSRegIdMap (42, 17, CF_SR_MPAT17_B1);
    AddSRegIdMap (42, 18, CF_SR_MPAT18_B1);
    AddSRegIdMap (42, 19, CF_SR_MPAT19_B1);
    AddSRegIdMap (42, 20, CF_SR_MPAT20_B1);
    AddSRegIdMap (42, 21, CF_SR_MPAT21_B1);
    AddSRegIdMap (42, 22, CF_SR_MPAT22_B1);
    AddSRegIdMap (42, 23, CF_SR_MPAT23_B1);
    AddSRegIdMap (42, 24, CF_SR_MPAT24_B1);
    AddSRegIdMap (42, 25, CF_SR_MPAT25_B1);
    AddSRegIdMap (42, 26, CF_SR_MPAT26_B1);
    AddSRegIdMap (42, 27, CF_SR_MPAT27_B1);
    AddSRegIdMap (42, 28, CF_SR_MPAT28_B1);
    AddSRegIdMap (42, 29, CF_SR_MPAT29_B1);
    AddSRegIdMap (42, 30, CF_SR_MPAT30_B1);
    AddSRegIdMap (42, 31, CF_SR_MPAT31_B1);
}
