# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_7Z "")
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_IFW "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TXZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENTS_ALL "headers;libraries")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "TBZ2")
SET(CPACK_INSTALL_CMAKE_PROJECTS "/shsv/MobAP2/prj_VPF/99_Work/thiepnguyen/DTSG_U2_Output/ENV/tb/SCHEAPG4/scheapCompile/models/iss/cforestg4x;PRODUCT_SCHEAP;ALL;/")
SET(CPACK_INSTALL_PREFIX "/usr/local")
SET(CPACK_MODULE_PATH "/shsv/MobAP2/prj_VPF/99_Work/thiepnguyen/DTSG_U2_Output/ENV/tb/SCHEAPG4/scheapCompile/models/iss/cforestg4x/cmake")
SET(CPACK_NSIS_DISPLAY_NAME "libforestg4x_scheap 20200306_g4mh20_scheap-7c57fe9-Linux")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "libforestg4x_scheap 20200306_g4mh20_scheap-7c57fe9-Linux")
SET(CPACK_OUTPUT_CONFIG_FILE "/shsv/MobAP2/prj_VPF/99_Work/thiepnguyen/DTSG_U2_Output/ENV/tb/SCHEAPG4/scheapCompile/models/iss/cforestg4x/CPackConfig.cmake")
SET(CPACK_PACKAGE_CONTACT "Hiroyuki Ono <hiroyuki.ono.jc@renesas.com>")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/common/appl/cmake/cmake-3.4.3-RHEL6/share/cmake-3.4/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "libforestg4x_scheap.a is the RH850 cycle accurate simulator for SC_HEAP.")
SET(CPACK_PACKAGE_EXECUTABLES "cforestg4x;RH850 cycle accurate simulator")
SET(CPACK_PACKAGE_FILE_NAME "libforestg4x_scheap-20200306_g4mh20_scheap-7c57fe9-Linux")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "libforestg4x_scheap 20200306_g4mh20_scheap-7c57fe9-Linux")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "libforestg4x_scheap 20200306_g4mh20_scheap-7c57fe9-Linux")
SET(CPACK_PACKAGE_NAME "libforestg4x_scheap")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "Renesas Corp.")
SET(CPACK_PACKAGE_VERSION "20200306_g4mh20_scheap-7c57fe9-Linux")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "1")
SET(CPACK_RESOURCE_FILE_LICENSE "/common/appl/cmake/cmake-3.4.3-RHEL6/share/cmake-3.4/Templates/CPack.GenericLicense.txt")
SET(CPACK_RESOURCE_FILE_README "/common/appl/cmake/cmake-3.4.3-RHEL6/share/cmake-3.4/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/common/appl/cmake/cmake-3.4.3-RHEL6/share/cmake-3.4/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_7Z "")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/shsv/MobAP2/prj_VPF/99_Work/thiepnguyen/DTSG_U2_Output/ENV/tb/SCHEAPG4/scheapCompile/models/iss/cforestg4x/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_STRIP_FILES "")
SET(CPACK_SOURCE_TBZ2 "ON")
SET(CPACK_SOURCE_TGZ "ON")
SET(CPACK_SOURCE_TXZ "ON")
SET(CPACK_SOURCE_TZ "ON")
SET(CPACK_SOURCE_ZIP "OFF")
SET(CPACK_STRIP_FILES "bin/cforestg4x")
SET(CPACK_SYSTEM_NAME "Linux")
SET(CPACK_TOPLEVEL_TAG "Linux")
SET(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/shsv/MobAP2/prj_VPF/99_Work/thiepnguyen/DTSG_U2_Output/ENV/tb/SCHEAPG4/scheapCompile/models/iss/cforestg4x/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
