// -----------------------------------------------------------------------------
// $Id: $
//
// Copyright(c) 2012-2018 Renesas Electronics Corporation
// Copyright(c) 2012-2018 Renesas Design Vietnam Co., Ltd.
// RENESAS ELECTRONICS CONFIDENTIAL AND PROPRIETARY.
// This program must be used solely for the purpose for which
// it was furnished by Renesas Electronics Corporation. No part of this
// program may be reproduced or disclosed to others, in any
// form, without the prior written permission of Renesas Electronics
// Corporation.
// -----------------------------------------------------------------------------
// This file is generated by Register I/F generator
//    gen_regif.py
//    gen_regif_class.py
//    regif_h.skl
//
// Input file : /shsv/sld/ipp/project/2018/rel/ipd2_sld_12006_rlin3/02_Output/DATA/src/rlin3_regif.txt
////////////////////////////////////////////////////////////////////////////////
// # ---------------------------------------------------------------------
// # $Id: $
// #
// # Copyright(c) 2012-2018 Renesas Electronics Corporation
// # Copyright(c) 2012-2018 Renesas Design Vietnam Co., Ltd.
// # RENESAS ELECTRONICS CONFIDENTIAL AND PROPRIETARY.
// # This program must be used solely for the purpose for which
// # it was furnished by Renesas Electronics Corporation. No part of this
// # program may be reproduced or disclosed to others, in any
// # form, without the prior written permission of Renesas Electronics
// # Corporation.
// # ---------------------------------------------------------------------
// 
//  %MODULE RLIN3 
//     #              name     offset_size
//     %%REG_INSTANCE reg_def  6
// 
// %REG_CHANNEL reg_def
//     %%TITLE    name       reg_name       size       length  offset    access  init     support  callback
//     %%REG      LWBR       LWBR           8|16|32    8       0x01      -       0        TRUE     -
//     %%REG      LBRP0      LBRP0          8|16|32    8       0x02      -       0        TRUE     -  
//     %%REG      LBRP1      LBRP1          8|16|32    8       0x03      -       0        TRUE     -
//     %%REG      LSTC       LSTC           8|16|32    8       0x04      -       0        TRUE     -
//     %%REG      LMD        LMD            8|16|32    8       0x08      -       0        TRUE     -
//     %%REG      LBFC       LBFC           8|16|32    8       0x09      -       0        TRUE     -
//     %%REG      LSC        LSC            8|16|32    8       0x0A      -       0        TRUE     -
//     %%REG      LWUP       LWUP           8|16|32    8       0x0B      -       0        TRUE     -
//     %%REG      LIE        LIE            8|16|32    8       0x0C      -       0        TRUE     -
//     %%REG      LEDE       LEDE           8|16|32    8       0x0D      -       0        TRUE     -
//     %%REG      LCUC       LCUC           8|16|32    8       0x0E      -       0        TRUE     -
//     %%REG      LTRC       LTRC           8|16|32    8       0x10      -       0        TRUE     -
//     %%REG      LMST       LMST           8|16|32    8       0x11      -       0        TRUE     -
//     %%REG      LST        LST            8|16|32    8       0x12      -       0        TRUE     -
//     %%REG      LEST       LEST           8|16|32    8       0x13      -       0        TRUE     -
//     %%REG      LDFC       LDFC           8|16|32    8       0x14      -       0        TRUE     -
//     %%REG      LIDB       LIDB           8|16|32    8       0x15      -       0        TRUE     -
//     %%REG      LCBR       LCBR           8|16|32    8       0x16      -       0        TRUE     -
//     %%REG      LUDB0      LUDB0          8|16|32    8       0x17      -       0        TRUE     -
//     %%REG      LDB1       LDB1           8|16|32    8       0x18      -       0        TRUE     -
//     %%REG      LDB2       LDB2           8|16|32    8       0x19      -       0        TRUE     -
//     %%REG      LDB3       LDB3           8|16|32    8       0x1A      -       0        TRUE     -
//     %%REG      LDB4       LDB4           8|16|32    8       0x1B      -       0        TRUE     -
//     %%REG      LDB5       LDB5           8|16|32    8       0x1C      -       0        TRUE     -
//     %%REG      LDB6       LDB6           8|16|32    8       0x1D      -       0        TRUE     -
//     %%REG      LDB7       LDB7           8|16|32    8       0x1E      -       0        TRUE     -
//     %%REG      LDB8       LDB8           8|16|32    8       0x1F      -       0        TRUE     -
//     %%REG      LUOER      LUOER          8|16|32    8       0x20      -       0        TRUE     -
//     %%REG      LUOR1      LUOR1          8|16|32    8       0x21      -       0        TRUE     -
//     %%REG      LUOR2      LUOR2          8|16|32    8       0x22      -       0        FALSE    -
//     %%REG      LUTDCR     LUTDCR         8|16|32    8       0x23      -       0        FALSE    -
//     %%REG      LUTDR      LUTDR          8|16       16      0x24      -       0        TRUE     -
//     %%REG      LURDR      LURDR          8|16       16      0x26      -       0        TRUE     -
//     %%REG      LUWTDR     LUWTDR         8|16       16      0x28      -       0        TRUE     -
//     %%REG      LURDE      LURDE          8|16       16      0x2A      -       0        TRUE     -
//     %%REG      LBSS       LBSS           8|16|32    8       0x30      -       0        TRUE     -
//     %%REG      LRSS       LRSS           8|16|32    8       0x34      -       0        TRUE     -
////////////////////////////////////////////////////////////////////////////////
/// @file rlin3_regif.h
/// @brief Register IF class of model RLIN3
/// $Id$
/// $Date$
/// $Revison$
/// $Author$
////////////////////////////////////////////////////////////////////////////////
#ifndef __RLIN3_REGIF_H__
#define __RLIN3_REGIF_H__
#include <string>
#include <map>
#include <list>
#include <cstdarg>
#include <cerrno>
#include <iomanip>
#include <sstream>
#include <cassert>
#ifndef REGIF_NOT_USE_SYSTEMC
#include "systemc.h"
#endif
#include "re_register.h"
#ifdef USE_CWR_SYSTEMC
#include "scml2.h"
#endif

/// Register IF class of RLIN3 model
class Crlin3_regif
: public vpcl::reg_super
{
protected:
    typedef const unsigned int cuint;
    typedef unsigned int uint;
#ifdef USE_CWR_SYSTEMC
    typedef unsigned short REG_TYPE;
#endif

    enum eRegGroup {
        emNum_of_gr
    }; ///< Enumeration for register group index

#ifdef USE_WEB_SIM
    enum eRegValIDConstant {
        emBitNum       = 0,
        emRegIDNum     = 0,
        emNumOfChannel = 1
    };
#endif

    struct RegCBstr {
        uint channel;
        bool is_wr;
        uint size;
        uint pre_data;
        uint data;
        RegCBstr (uint channel, bool is_wr, uint size, uint pre_data, uint data)
        {
            this-> channel  = channel;
            this-> is_wr    = is_wr;
            this-> size     = size;
            this-> pre_data = pre_data;
            this-> data     = data;
        }
    };
    struct SRegList {
        vpcl::re_register *my_p;
        SRegList *prev;
        uint channel;
        uint length;
        std::string wacc_size;
        std::string racc_size;
        bool block;
#ifdef USE_CWR_SYSTEMC
        scml2::memory<REG_TYPE> *mcwmem;
        scml2::reg<REG_TYPE> *my_cw_p;
        SRegList( vpcl::re_register *_my_p, SRegList *_prev, uint _channel, uint _length, std::string _wacc_size, std::string _racc_size, bool _block = false, scml2::memory<REG_TYPE> *_cwmem=NULL) {
            this->my_cw_p = NULL;
            if (_cwmem != NULL) {
                mcwmem = _cwmem;
            } else {
                assert(_prev != NULL && _prev->mcwmem != NULL) ;
                mcwmem = _prev->mcwmem;
            }
            this->my_cw_p = new scml2::reg<REG_TYPE> (_my_p->name(), *mcwmem , _my_p->addr());
#else
        SRegList( vpcl::re_register *_my_p, SRegList *_prev, uint _channel, uint _length, std::string _wacc_size, std::string _racc_size, bool _block = false) {
#endif
            this->my_p = NULL;
            if (_my_p != NULL) {
                this->my_p = _my_p;
            }
            this->prev = NULL;
            if (_prev != NULL) {
                this->prev = _prev;
            }
            this->channel   = _channel;
            this->length    = _length;
            this->wacc_size = _wacc_size;
            this->racc_size = _racc_size;
            this->block     = _block;
        }
        ~SRegList() {
#ifdef USE_CWR_SYSTEMC
            delete my_cw_p;
#endif
        }
    } *mRegList, *mCurReg, **mRegArray;

    uint *mRegMap;
    uint mTotalRegNum;
#ifdef USE_WEB_SIM
    struct strRegValueID {
        int  BitVal[emBitNum];
        std::string RegValueID;
        strRegValueID(void) {
            for (unsigned int i = 0; i < emBitNum; i++) {
                BitVal[i] = 0;
            }
            RegValueID = "";
        }
        strRegValueID(int bitval[emBitNum], std::string reg_value_id) {
            for (unsigned int i = 0; i < emBitNum; i++) {
                this->BitVal[i] = bitval[i];
            }
            this->RegValueID = reg_value_id;
        }
    };
    
    vpcl::bit_info* mBitInfoPtr[emBitNum];
    uint mTargetRegVal[emBitNum];
    strRegValueID mRegValueIDLib[emRegIDNum];
    
    void InitializeRegValueID();
    void CalcTargetRegVal(void);
    void IssueRegValueID();

    typedef void (Crlin3_regif::* ptrRegValueIDFunc) (std::string);
    ptrRegValueIDFunc mNotifyRegValueIDAPI;
    virtual void NotifyRegValueID(const std::string reg_val_id) = 0;
#endif

public:
    Crlin3_regif(std::string name, uint buswidth);
    ~Crlin3_regif();

protected:
    vpcl::re_register *LWBR  ;
    vpcl::re_register *LBRP0 ;
    vpcl::re_register *LBRP1 ;
    vpcl::re_register *LSTC  ;
    vpcl::re_register *LMD   ;
    vpcl::re_register *LBFC  ;
    vpcl::re_register *LSC   ;
    vpcl::re_register *LWUP  ;
    vpcl::re_register *LIE   ;
    vpcl::re_register *LEDE  ;
    vpcl::re_register *LCUC  ;
    vpcl::re_register *LTRC  ;
    vpcl::re_register *LMST  ;
    vpcl::re_register *LST   ;
    vpcl::re_register *LEST  ;
    vpcl::re_register *LDFC  ;
    vpcl::re_register *LIDB  ;
    vpcl::re_register *LCBR  ;
    vpcl::re_register *LUDB0 ;
    vpcl::re_register *LDB1  ;
    vpcl::re_register *LDB2  ;
    vpcl::re_register *LDB3  ;
    vpcl::re_register *LDB4  ;
    vpcl::re_register *LDB5  ;
    vpcl::re_register *LDB6  ;
    vpcl::re_register *LDB7  ;
    vpcl::re_register *LDB8  ;
    vpcl::re_register *LUOER ;
    vpcl::re_register *LUOR1 ;
    vpcl::re_register *LUOR2 ;
    vpcl::re_register *LUTDCR;
    vpcl::re_register *LUTDR ;
    vpcl::re_register *LURDR ;
    vpcl::re_register *LUWTDR;
    vpcl::re_register *LURDE ;
    vpcl::re_register *LBSS  ;
    vpcl::re_register *LRSS  ;

    #ifdef USE_CWR_SYSTEMC
    scml2::memory<REG_TYPE> cwmem;
    #endif

    uint LWBR_LWBR;
    uint LBRP0_LBRP0;
    uint LBRP1_LBRP1;
    uint LSTC_LSTC;
    uint LMD_LMD;
    uint LBFC_LBFC;
    uint LSC_LSC;
    uint LWUP_LWUP;
    uint LIE_LIE;
    uint LEDE_LEDE;
    uint LCUC_LCUC;
    uint LTRC_LTRC;
    uint LMST_LMST;
    uint LST_LST;
    uint LEST_LEST;
    uint LDFC_LDFC;
    uint LIDB_LIDB;
    uint LCBR_LCBR;
    uint LUDB0_LUDB0;
    uint LDB1_LDB1;
    uint LDB2_LDB2;
    uint LDB3_LDB3;
    uint LDB4_LDB4;
    uint LDB5_LDB5;
    uint LDB6_LDB6;
    uint LDB7_LDB7;
    uint LDB8_LDB8;
    uint LUOER_LUOER;
    uint LUOR1_LUOR1;
    uint LUOR2_LUOR2;
    uint LUTDCR_LUTDCR;
    uint LUTDR_LUTDR;
    uint LURDR_LURDR;
    uint LUWTDR_LUWTDR;
    uint LURDE_LURDE;
    uint LBSS_LBSS;
    uint LRSS_LRSS;

    void EnableReset(const bool is_active);
    uint bit_select(cuint val, cuint start, cuint end);
    bool reg_wr(cuint addr, const unsigned char *p_data, cuint size);
    bool reg_rd(cuint addr, unsigned char *p_data, cuint size);
    bool reg_wr_dbg(cuint addr, const unsigned char *p_data, cuint size);
    bool reg_rd_dbg(cuint addr, unsigned char *p_data, cuint size);
    std::string reg_handle_command(const std::vector<std::string>& args);
    int get_reg_index(cuint addr);
    vpcl::re_register *first_reg_object();
    vpcl::re_register *next_reg_object();

    void wr_cb(cuint addr, uint data);
    uint rd_cb(cuint addr);


    void set_instance_name(std::string InstName);

    uint mBusByteWidth;
    uint mBusWidth;
    bool mIsReset;
    bool mDumpRegisterRW;
    bool mAPBAccessMode;
    bool mDumpBitInfo;
    std::map<std::string, bool> mMessageLevel;
    std::map<std::string, std::map<std::string, void (Crlin3_regif::*) (RegCBstr)> > mWrCbAPI;
    std::map<std::string, std::map<std::string, void (Crlin3_regif::*) (RegCBstr)> > mRdCbAPI;
    std::string mFileName;
    std::string mInstName;
    int mLineNum;

    bool reg_wr_process(cuint addr, const unsigned char *p_data, cuint size, bool IsDbgFunc);
    bool reg_rd_process(cuint addr, unsigned char *p_data, cuint size, bool IsDbgFunc);
    bool reg_wr_func(cuint addr, const unsigned char *p_data, cuint size, cuint reg_index, bool IsDbgFunc);
    bool reg_rd_func(cuint addr, unsigned char *p_data, cuint size, cuint reg_index, bool IsDbgFunc);
    void _re_printf(const std::string msg_level, const char *format, ...);
    void get_fileline(std::string filename, int line_number);
    void CommandInit();
    bool ChkSize(std::string expect_size, cuint detect_size, cuint addr, bool is_wr);
    std::vector<std::string> Str2Vec(std::string str, const char sep);
    std::string Num2HexStr(cuint num, cuint num_length, bool space_strip, bool is_data, uint acc_size);
    void DumpRegMsg(const std::string operation, const std::string RegName, const std::string BitName, cuint size, cuint addr, cuint wr_data, cuint pre_data, cuint data, cuint reg_length);
    std::string AccessRegCommand(const std::vector<std::string>& args, vpcl::re_register *Register, bool &BlockReg);
    void InitLocalVal();
    void UpdateLocalVal(cuint addr);
    void UpdateRegVal(cuint addr);

    #ifdef USE_CWR_SYSTEMC
    unsigned short cw_rd_cb(tlm::tlm_generic_payload& trans, int tag);
    unsigned short cw_wr_cb(tlm::tlm_generic_payload& trans, int tag);
    virtual void cw_set_callback_reg(scml2::reg<REG_TYPE> * reg, int offset);
    void cw_set_all_callback_reg(void);
    #endif
};
#endif //__RLIN3_REG_DEF_H__
