cmake_minimum_required( VERSION 3.2 )

project( PRODUCT_CFORESTG4X )

add_subdirectory( Device/COMMON )

add_subdirectory( Device/API/CFORESTG4X )
if( NOT MSVC )
  add_subdirectory( Device/API/GDB )
endif( )
if( USE_UNIT_TEST )
  add_definitions( -DMAKE_FP_UNIT_TEST )
endif( )
add_subdirectory( Device/API/PYTHON )

add_subdirectory( Device/Bus/FSBUS )

add_subdirectory( Device/Core/BTB )
add_subdirectory( Device/Core/CEDAR )
add_subdirectory( Device/Core/COREGUARD )
add_subdirectory( Device/Core/COUNTERBASE )
add_subdirectory( Device/Core/CYCLESIM )
add_subdirectory( Device/Core/DEBUGBREAK )
add_subdirectory( Device/Core/EXCEP )
add_subdirectory( Device/Core/ICACHE )
add_subdirectory( Device/Core/INST )
add_subdirectory( Device/Core/LLSC )
add_subdirectory( Device/Core/LSU )
add_subdirectory( Device/Core/MICROARCHDB )
add_subdirectory( Device/Core/MISR )
add_subdirectory( Device/Core/MPU )
add_subdirectory( Device/Core/PE )
add_subdirectory( Device/Core/REG )
add_subdirectory( Device/Core/SIMBREAK )
add_subdirectory( Device/Core/STATISTICS )
add_subdirectory( Device/Core/TRACE )

add_subdirectory( Device/Peripheral/DEBUGAREA )
add_subdirectory( Device/Peripheral/ERRORAREA )
add_subdirectory( Device/Peripheral/GUARD )
add_subdirectory( Device/Peripheral/GUARD_BASE )
add_subdirectory( Device/Peripheral/INTC )
add_subdirectory( Device/Peripheral/INTC2 )
add_subdirectory( Device/Peripheral/INVALIDLRAM )
add_subdirectory( Device/Peripheral/IPIR )
add_subdirectory( Device/Peripheral/LATENCYINFO )
add_subdirectory( Device/Peripheral/MECNT )
add_subdirectory( Device/Peripheral/MEM )
add_subdirectory( Device/Peripheral/OSTM )
add_subdirectory( Device/Peripheral/PERFCNT )
add_subdirectory( Device/Peripheral/SIMIO )
add_subdirectory( Device/Peripheral/TARGETREG )
add_subdirectory( Device/Peripheral/TMU )
if( NOT MSVC )
  add_subdirectory( Device/Peripheral/UART )
endif( )
add_subdirectory( Device/Peripheral/BAR )

add_subdirectory( Device/Utility )
add_subdirectory( Samples )

# Package
set( CPACK_CMAKE_GENERATOR ${CMAKE_GENERATOR} )
set( CPACK_PACKAGE_DESCRIPTION_SUMMARY "CForestG4X is the RH850 cycle accurate simulator." )
set( CPACK_PACKAGE_NAME "cforestg4x" )
set( CPACK_PACKAGE_VENDOR "Renesas Corp." )
set( CPACK_PACKAGE_VERSION "${CFOREST_VERSION}-${CFOREST_REVISION}-${CMAKE_SYSTEM_NAME}" )
set( CPACK_PACKAGE_FILE_NAME "cforestg4x-${CPACK_PACKAGE_VERSION}" )

set( CPACK_STRIP_FILES "bin/cforestg4x" )
set( CPACK_SOURCE_STRIP_FILES "" )
set( CPACK_PACKAGE_CONTACT "Hiroyuki Ono <hiroyuki.ono.jc@renesas.com>" )
set( CPACK_PACKAGE_EXECUTABLES "cforestg4x" "RH850 cycle accurate simulator" )

set( CPACK_CMAKE_GENERATOR ${CMAKE_GENERATOR} )
if( CYGWIN )
  set( CPACK_GENERATOR "CygwinBinary" )
elseif( WIN32 )
  set( CPACK_GENERATOR "ZIP" )
else( )
  set( CPACK_GENERATOR "TBZ2" )
endif( )

include( CPack )
