#!/usr/bin/env python

#------------------------------------------------------------------------------
# Copyright (C) Australian Semiconductor Technology Company. 2019.
# All Rights Reserved.
#
# This is unpublished proprietary source code of the Australian Semiconductor
# Technology Company (ASTC).  The copyright notice does not evidence any actual
# or intended publication of such source code.
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Imports
#------------------------------------------------------------------------------

import vlab

vlab.properties(doc="rh850 FastISS Core Model",
                kind="core",
                module="rh850.core",
                bit_endianness="lsb0",
                extensions={
                  "disassemblers": ["rh850e3"],
                  "memory_spaces": ["default", "physical"],
                  "physical_memory_space": "physical",
                  "physical_memory_at_zero": True})

vlab.register(name='r0', width=32, extensions={'id': 0}, groups=['GR'])
vlab.register(name='r1', width=32, extensions={'id': 1}, groups=['GR'])
vlab.register(name='r2', width=32, extensions={'id': 2}, groups=['GR'])
vlab.register(name='r3', width=32, extensions={'id': 3}, groups=['GR'])
vlab.register(name='r4', width=32, extensions={'id': 4}, groups=['GR'])
vlab.register(name='r5', width=32, extensions={'id': 5}, groups=['GR'])
vlab.register(name='r6', width=32, extensions={'id': 6}, groups=['GR'])
vlab.register(name='r7', width=32, extensions={'id': 7}, groups=['GR'])
vlab.register(name='r8', width=32, extensions={'id': 8}, groups=['GR'])
vlab.register(name='r9', width=32, extensions={'id': 9}, groups=['GR'])
vlab.register(name='r10', width=32, extensions={'id': 10}, groups=['GR'])
vlab.register(name='r11', width=32, extensions={'id': 11}, groups=['GR'])
vlab.register(name='r12', width=32, extensions={'id': 12}, groups=['GR'])
vlab.register(name='r13', width=32, extensions={'id': 13}, groups=['GR'])
vlab.register(name='r14', width=32, extensions={'id': 14}, groups=['GR'])
vlab.register(name='r15', width=32, extensions={'id': 15}, groups=['GR'])
vlab.register(name='r16', width=32, extensions={'id': 16}, groups=['GR'])
vlab.register(name='r17', width=32, extensions={'id': 17}, groups=['GR'])
vlab.register(name='r18', width=32, extensions={'id': 18}, groups=['GR'])
vlab.register(name='r19', width=32, extensions={'id': 19}, groups=['GR'])
vlab.register(name='r20', width=32, extensions={'id': 20}, groups=['GR'])
vlab.register(name='r21', width=32, extensions={'id': 21}, groups=['GR'])
vlab.register(name='r22', width=32, extensions={'id': 22}, groups=['GR'])
vlab.register(name='r23', width=32, extensions={'id': 23}, groups=['GR'])
vlab.register(name='r24', width=32, extensions={'id': 24}, groups=['GR'])
vlab.register(name='r25', width=32, extensions={'id': 25}, groups=['GR'])
vlab.register(name='r26', width=32, extensions={'id': 26}, groups=['GR'])
vlab.register(name='r27', width=32, extensions={'id': 27}, groups=['GR'])
vlab.register(name='r28', width=32, extensions={'id': 28}, groups=['GR'])
vlab.register(name='r29', width=32, extensions={'id': 29}, groups=['GR'])
vlab.register(name='r30', width=32, extensions={'id': 30}, groups=['GR'])
vlab.register(name='r31', width=32, extensions={'id': 31}, groups=['GR'])
vlab.register(name='PC', width=32, extensions={'id': 32, 'is_pc': True})
vlab.register(name='EIPC', width=32, extensions={'id': 33}, groups=['SR_SELID_0'])
vlab.register(name='EIPSW', width=32, extensions={'id': 34}, groups=['SR_SELID_0'])
vlab.register(name='FEPC', width=32, extensions={'id': 35}, groups=['SR_SELID_0'])
vlab.register(name='FEPSW', width=32, extensions={'id': 36}, groups=['SR_SELID_0'])
vlab.register(name='PSW', width=32, extensions={'id': 37}, groups=['SR_SELID_0'])
vlab.field(name='PSW_Z', register='PSW', offset=0, width=1)
vlab.field(name='PSW_S', register='PSW', offset=1, width=1)
vlab.field(name='PSW_OV', register='PSW', offset=2, width=1)
vlab.field(name='PSW_CY', register='PSW', offset=3, width=1)
vlab.field(name='PSW_SAT', register='PSW', offset=4, width=1)
vlab.field(name='PSW_ID', register='PSW', offset=5, width=1)
vlab.field(name='PSW_EP', register='PSW', offset=6, width=1)
vlab.field(name='PSW_NP', register='PSW', offset=7, width=1)
vlab.field(name='PSW_CM', register='PSW', offset=9, width=1)
vlab.field(name='PSW_SS', register='PSW', offset=11, width=1)
vlab.field(name='PSW_EBV', register='PSW', offset=15, width=1)
vlab.field(name='PSW_CU0', register='PSW', offset=16, width=1)
vlab.field(name='PSW_CU1', register='PSW', offset=17, width=1)
vlab.field(name='PSW_CU2', register='PSW', offset=18, width=1)
vlab.field(name='PSW_HVC', register='PSW', offset=19, width=1)
vlab.field(name='PSW_UM', register='PSW', offset=30, width=1)
vlab.register(name='FPSR', width=32, extensions={'id': 38}, groups=['SR_SELID_0'])
vlab.field(name='FPSR_CC', register='FPSR', offset=24, width=8)
vlab.field(name='FPSR_FN', register='FPSR', offset=23, width=1)
vlab.field(name='FPSR_IF', register='FPSR', offset=22, width=1)
vlab.field(name='FPSR_PEM', register='FPSR', offset=21, width=1)
vlab.field(name='FPSR_RM', register='FPSR', offset=18, width=2)
vlab.field(name='FPSR_FS', register='FPSR', offset=17, width=1)
vlab.field(name='FPSR_XC', register='FPSR', offset=10, width=6)
vlab.field(name='FPSR_XE', register='FPSR', offset=5, width=5)
vlab.field(name='FPSR_XP', register='FPSR', offset=0, width=5)
vlab.register(name='FPEPC', width=32, extensions={'id': 39}, groups=['SR_SELID_0'])
vlab.register(name='FPST', width=32, extensions={'id': 40}, groups=['SR_SELID_0'])
vlab.field(name='FPST_XC', register='FPST', offset=8, width=6)
vlab.field(name='FPST_IF', register='FPST', offset=5, width=1)
vlab.field(name='FPST_XP', register='FPST', offset=0, width=5)
vlab.register(name='FPCC', width=32, extensions={'id': 41}, groups=['SR_SELID_0'])
vlab.field(name='FPCC_CC', register='FPCC', offset=0, width=8)
vlab.register(name='FPCFG', width=32, extensions={'id': 42}, groups=['SR_SELID_0'])
vlab.field(name='FPCFG_RM', register='FPCFG', offset=8, width=2)
vlab.field(name='FPCFG_XE', register='FPCFG', offset=0, width=5)
vlab.register(name='FPEC', width=32, extensions={'id': 43}, groups=['SR_SELID_0'])
vlab.register(name='EIIC', width=32, extensions={'id': 44}, groups=['SR_SELID_0'])
vlab.register(name='FEIC', width=32, extensions={'id': 45}, groups=['SR_SELID_0'])
vlab.register(name='CTPC', width=32, extensions={'id': 46}, groups=['SR_SELID_0'])
vlab.register(name='CTPSW', width=32, extensions={'id': 47}, groups=['SR_SELID_0'])
vlab.register(name='CTBP', width=32, extensions={'id': 48}, groups=['SR_SELID_0'])
vlab.register(name='EIWR', width=32, extensions={'id': 49}, groups=['SR_SELID_0'])
vlab.register(name='FEWR', width=32, extensions={'id': 50}, groups=['SR_SELID_0'])
vlab.register(name='BSEL', width=32, extensions={'id': 51}, groups=['SR_SELID_0'])
vlab.register(name='MCFG0', width=32, extensions={'id': 52}, groups=['SR_SELID_1'])
vlab.field(name='MCFG0_SPID', register='MCFG0', offset=16, width=8)
vlab.field(name='MCFG0_HVP', register='MCFG0', offset=2, width=1)
vlab.register(name='RBASE', width=32, extensions={'id': 53}, groups=['SR_SELID_1'])
vlab.field(name='RBASE_RBASE', register='RBASE', offset=9, width=23)
vlab.field(name='RBASE_RINT', register='RBASE', offset=0, width=1)
vlab.register(name='EBASE', width=32, extensions={'id': 54}, groups=['SR_SELID_1'])
vlab.field(name='EBASE_EBASE', register='EBASE', offset=9, width=23)
vlab.field(name='EBASE_RINT', register='EBASE', offset=0, width=1)
vlab.register(name='INTBP', width=32, extensions={'id': 55}, groups=['SR_SELID_1'])
vlab.register(name='MCTL', width=32, extensions={'id': 56}, groups=['SR_SELID_1'])
vlab.field(name='MCTL_EN', register='MCTL', offset=31, width=1)
vlab.field(name='MCTL_MT', register='MCTL', offset=30, width=1)
vlab.field(name='MCTL_STID', register='MCTL', offset=16, width=6)
vlab.field(name='MCTL_MA', register='MCTL', offset=1, width=1)
vlab.field(name='MCTL_UIC', register='MCTL', offset=0, width=1)
vlab.register(name='PID', width=32, extensions={'id': 57}, groups=['SR_SELID_1'])
vlab.register(name='FPIPR', width=32, extensions={'id': 58}, groups=['SR_SELID_1'])
vlab.field(name='FPIPR_FPIPR', register='FPIPR', offset=0, width=5)
vlab.register(name='SCCFG', width=32, extensions={'id': 59}, groups=['SR_SELID_1'])
vlab.field(name='SCCFG_SIZE', register='SCCFG', offset=0, width=8)
vlab.register(name='SCBP', width=32, extensions={'id': 60}, groups=['SR_SELID_1'])
vlab.register(name='HTCFG0', width=32, extensions={'id': 61}, groups=['SR_SELID_2'])
vlab.field(name='HTCFG0_PEID', register='HTCFG0', offset=16, width=3)
vlab.field(name='HTCFG0_NC', register='HTCFG0', offset=15, width=1)
vlab.field(name='HTCFG0_TCID', register='HTCFG0', offset=0, width=8)
vlab.register(name='HVCCFG', width=32, extensions={'id': 62}, groups=['SR_SELID_1'])
vlab.register(name='HVCBP', width=32, extensions={'id': 63}, groups=['SR_SELID_1'])
vlab.register(name='MEA', width=32, extensions={'id': 64}, groups=['SR_SELID_2'])
vlab.register(name='ASID', width=32, extensions={'id': 65}, groups=['SR_SELID_2'])
vlab.field(name='ASID_ASID', register='ASID', offset=0, width=10)
vlab.register(name='MEI', width=32, extensions={'id': 66}, groups=['SR_SELID_2'])
vlab.field(name='MEI_REG', register='MEI', offset=16, width=5)
vlab.field(name='MEI_DS', register='MEI', offset=9, width=2)
vlab.field(name='MEI_U', register='MEI', offset=8, width=1)
vlab.field(name='MEI_ITYPE', register='MEI', offset=1, width=5)
vlab.field(name='MEI_RW', register='MEI', offset=0, width=1)
vlab.register(name='ISPR', width=32, extensions={'id': 67}, groups=['SR_SELID_2'])
vlab.field(name='ISPR_ISP', register='ISPR', offset=0, width=8)
vlab.register(name='PMR', width=32, extensions={'id': 68}, groups=['SR_SELID_2'])
vlab.field(name='PMR_PM', register='PMR', offset=0, width=8)
vlab.register(name='ICSR', width=32, extensions={'id': 69}, groups=['SR_SELID_2'])
vlab.field(name='ICSR_PMEI', register='ICSR', offset=0, width=1)
vlab.register(name='INTCFG', width=32, extensions={'id': 70}, groups=['SR_SELID_2'])
vlab.field(name='INTCFG_ISPC', register='INTCFG', offset=0, width=1)
vlab.register(name='DBIC', width=32, extensions={'id': 71}, groups=['SR_SELID_3'])
vlab.register(name='DBCMC', width=32, extensions={'id': 72}, groups=['SR_SELID_3'])
vlab.register(name='DBPC', width=32, extensions={'id': 73}, groups=['SR_SELID_3'])
vlab.register(name='DBPSW', width=32, extensions={'id': 74}, groups=['SR_SELID_3'])
vlab.register(name='DIR0', width=32, extensions={'id': 75}, groups=['SR_SELID_3'])
vlab.register(name='DIR1', width=32, extensions={'id': 76}, groups=['SR_SELID_3'])
vlab.register(name='BPC', width=32, extensions={'id': 77}, groups=['SR_SELID_3'])
vlab.register(name='BPAV', width=32, extensions={'id': 78}, groups=['SR_SELID_3'])
vlab.register(name='BPAM', width=32, extensions={'id': 79}, groups=['SR_SELID_3'])
vlab.register(name='BPDV', width=32, extensions={'id': 80}, groups=['SR_SELID_3'])
vlab.register(name='BPDM', width=32, extensions={'id': 81}, groups=['SR_SELID_3'])
vlab.register(name='DBWR', width=32, extensions={'id': 82}, groups=['SR_SELID_3'])
vlab.register(name='MPM', width=32, extensions={'id': 83}, groups=['SR_SELID_5'])
vlab.field(name='MPM_DX', register='MPM', offset=10, width=1)
vlab.field(name='MPM_DW', register='MPM', offset=9, width=1)
vlab.field(name='MPM_DR', register='MPM', offset=8, width=1)
vlab.field(name='MPM_SVP', register='MPM', offset=1, width=1)
vlab.field(name='MPM_MPE', register='MPM', offset=0, width=1)
vlab.register(name='MPRC', width=32, extensions={'id': 84}, groups=['SR_SELID_5'])
vlab.field(name='MPRC_E15', register='MPRC', offset=15, width=1)
vlab.field(name='MPRC_E14', register='MPRC', offset=14, width=1)
vlab.field(name='MPRC_E13', register='MPRC', offset=13, width=1)
vlab.field(name='MPRC_E12', register='MPRC', offset=12, width=1)
vlab.field(name='MPRC_E11', register='MPRC', offset=11, width=1)
vlab.field(name='MPRC_E10', register='MPRC', offset=10, width=1)
vlab.field(name='MPRC_E9', register='MPRC', offset=9, width=1)
vlab.field(name='MPRC_E8', register='MPRC', offset=8, width=1)
vlab.field(name='MPRC_E7', register='MPRC', offset=7, width=1)
vlab.field(name='MPRC_E6', register='MPRC', offset=6, width=1)
vlab.field(name='MPRC_E5', register='MPRC', offset=5, width=1)
vlab.field(name='MPRC_E4', register='MPRC', offset=4, width=1)
vlab.field(name='MPRC_E3', register='MPRC', offset=3, width=1)
vlab.field(name='MPRC_E2', register='MPRC', offset=2, width=1)
vlab.field(name='MPRC_E1', register='MPRC', offset=1, width=1)
vlab.field(name='MPRC_E0', register='MPRC', offset=0, width=1)
vlab.register(name='MPBRGN', width=32, extensions={'id': 85}, groups=['SR_SELID_5'])
vlab.field(name='MPBRGN_MPBRGN', register='MPBRGN', offset=0, width=5)
vlab.register(name='MPTRGN', width=32, extensions={'id': 86}, groups=['SR_SELID_5'])
vlab.field(name='MPTRGN_MPTRGN', register='MPTRGN', offset=0, width=5)
vlab.register(name='MCR', width=32, extensions={'id': 87}, groups=['SR_SELID_5'])
vlab.field(name='MCR_SXE', register='MCR', offset=5, width=1)
vlab.field(name='MCR_SWE', register='MCR', offset=4, width=1)
vlab.field(name='MCR_SRE', register='MCR', offset=3, width=1)
vlab.field(name='MCR_UXE', register='MCR', offset=2, width=1)
vlab.field(name='MCR_UWE', register='MCR', offset=1, width=1)
vlab.field(name='MCR_URE', register='MCR', offset=0, width=1)
vlab.register(name='MPLA0', width=32, extensions={'id': 88}, groups=['SR_SELID_6'])
vlab.register(name='MPUA0', width=32, extensions={'id': 89}, groups=['SR_SELID_6'])
vlab.register(name='MPAT0', width=32, extensions={'id': 90}, groups=['SR_SELID_6'])
vlab.field(name='MPAT0_ASID', register='MPAT0', offset=16, width=10)
vlab.field(name='MPAT0_E', register='MPAT0', offset=7, width=1)
vlab.field(name='MPAT0_G', register='MPAT0', offset=6, width=1)
vlab.field(name='MPAT0_SX', register='MPAT0', offset=5, width=1)
vlab.field(name='MPAT0_SW', register='MPAT0', offset=4, width=1)
vlab.field(name='MPAT0_SR', register='MPAT0', offset=3, width=1)
vlab.field(name='MPAT0_UX', register='MPAT0', offset=2, width=1)
vlab.field(name='MPAT0_UW', register='MPAT0', offset=1, width=1)
vlab.field(name='MPAT0_UR', register='MPAT0', offset=0, width=1)
vlab.register(name='MPLA1', width=32, extensions={'id': 91}, groups=['SR_SELID_6'])
vlab.register(name='MPUA1', width=32, extensions={'id': 92}, groups=['SR_SELID_6'])
vlab.register(name='MPAT1', width=32, extensions={'id': 93}, groups=['SR_SELID_6'])
vlab.field(name='MPAT1_ASID', register='MPAT1', offset=16, width=10)
vlab.field(name='MPAT1_E', register='MPAT1', offset=7, width=1)
vlab.field(name='MPAT1_G', register='MPAT1', offset=6, width=1)
vlab.field(name='MPAT1_SX', register='MPAT1', offset=5, width=1)
vlab.field(name='MPAT1_SW', register='MPAT1', offset=4, width=1)
vlab.field(name='MPAT1_SR', register='MPAT1', offset=3, width=1)
vlab.field(name='MPAT1_UX', register='MPAT1', offset=2, width=1)
vlab.field(name='MPAT1_UW', register='MPAT1', offset=1, width=1)
vlab.field(name='MPAT1_UR', register='MPAT1', offset=0, width=1)
vlab.register(name='MPLA2', width=32, extensions={'id': 94}, groups=['SR_SELID_6'])
vlab.register(name='MPUA2', width=32, extensions={'id': 95}, groups=['SR_SELID_6'])
vlab.register(name='MPAT2', width=32, extensions={'id': 96}, groups=['SR_SELID_6'])
vlab.field(name='MPAT2_ASID', register='MPAT2', offset=16, width=10)
vlab.field(name='MPAT2_E', register='MPAT2', offset=7, width=1)
vlab.field(name='MPAT2_G', register='MPAT2', offset=6, width=1)
vlab.field(name='MPAT2_SX', register='MPAT2', offset=5, width=1)
vlab.field(name='MPAT2_SW', register='MPAT2', offset=4, width=1)
vlab.field(name='MPAT2_SR', register='MPAT2', offset=3, width=1)
vlab.field(name='MPAT2_UX', register='MPAT2', offset=2, width=1)
vlab.field(name='MPAT2_UW', register='MPAT2', offset=1, width=1)
vlab.field(name='MPAT2_UR', register='MPAT2', offset=0, width=1)
vlab.register(name='MPLA3', width=32, extensions={'id': 97}, groups=['SR_SELID_6'])
vlab.register(name='MPUA3', width=32, extensions={'id': 98}, groups=['SR_SELID_6'])
vlab.register(name='MPAT3', width=32, extensions={'id': 99}, groups=['SR_SELID_6'])
vlab.field(name='MPAT3_ASID', register='MPAT3', offset=16, width=10)
vlab.field(name='MPAT3_E', register='MPAT3', offset=7, width=1)
vlab.field(name='MPAT3_G', register='MPAT3', offset=6, width=1)
vlab.field(name='MPAT3_SX', register='MPAT3', offset=5, width=1)
vlab.field(name='MPAT3_SW', register='MPAT3', offset=4, width=1)
vlab.field(name='MPAT3_SR', register='MPAT3', offset=3, width=1)
vlab.field(name='MPAT3_UX', register='MPAT3', offset=2, width=1)
vlab.field(name='MPAT3_UW', register='MPAT3', offset=1, width=1)
vlab.field(name='MPAT3_UR', register='MPAT3', offset=0, width=1)
vlab.register(name='MPLA4', width=32, extensions={'id': 100}, groups=['SR_SELID_6'])
vlab.register(name='MPUA4', width=32, extensions={'id': 101}, groups=['SR_SELID_6'])
vlab.register(name='MPAT4', width=32, extensions={'id': 102}, groups=['SR_SELID_6'])
vlab.field(name='MPAT4_ASID', register='MPAT4', offset=16, width=10)
vlab.field(name='MPAT4_E', register='MPAT4', offset=7, width=1)
vlab.field(name='MPAT4_G', register='MPAT4', offset=6, width=1)
vlab.field(name='MPAT4_SX', register='MPAT4', offset=5, width=1)
vlab.field(name='MPAT4_SW', register='MPAT4', offset=4, width=1)
vlab.field(name='MPAT4_SR', register='MPAT4', offset=3, width=1)
vlab.field(name='MPAT4_UX', register='MPAT4', offset=2, width=1)
vlab.field(name='MPAT4_UW', register='MPAT4', offset=1, width=1)
vlab.field(name='MPAT4_UR', register='MPAT4', offset=0, width=1)
vlab.register(name='MPLA5', width=32, extensions={'id': 103}, groups=['SR_SELID_6'])
vlab.register(name='MPUA5', width=32, extensions={'id': 104}, groups=['SR_SELID_6'])
vlab.register(name='MPAT5', width=32, extensions={'id': 105}, groups=['SR_SELID_6'])
vlab.field(name='MPAT5_ASID', register='MPAT5', offset=16, width=10)
vlab.field(name='MPAT5_E', register='MPAT5', offset=7, width=1)
vlab.field(name='MPAT5_G', register='MPAT5', offset=6, width=1)
vlab.field(name='MPAT5_SX', register='MPAT5', offset=5, width=1)
vlab.field(name='MPAT5_SW', register='MPAT5', offset=4, width=1)
vlab.field(name='MPAT5_SR', register='MPAT5', offset=3, width=1)
vlab.field(name='MPAT5_UX', register='MPAT5', offset=2, width=1)
vlab.field(name='MPAT5_UW', register='MPAT5', offset=1, width=1)
vlab.field(name='MPAT5_UR', register='MPAT5', offset=0, width=1)
vlab.register(name='MPLA6', width=32, extensions={'id': 106}, groups=['SR_SELID_6'])
vlab.register(name='MPUA6', width=32, extensions={'id': 107}, groups=['SR_SELID_6'])
vlab.register(name='MPAT6', width=32, extensions={'id': 108}, groups=['SR_SELID_6'])
vlab.field(name='MPAT6_ASID', register='MPAT6', offset=16, width=10)
vlab.field(name='MPAT6_E', register='MPAT6', offset=7, width=1)
vlab.field(name='MPAT6_G', register='MPAT6', offset=6, width=1)
vlab.field(name='MPAT6_SX', register='MPAT6', offset=5, width=1)
vlab.field(name='MPAT6_SW', register='MPAT6', offset=4, width=1)
vlab.field(name='MPAT6_SR', register='MPAT6', offset=3, width=1)
vlab.field(name='MPAT6_UX', register='MPAT6', offset=2, width=1)
vlab.field(name='MPAT6_UW', register='MPAT6', offset=1, width=1)
vlab.field(name='MPAT6_UR', register='MPAT6', offset=0, width=1)
vlab.register(name='MPLA7', width=32, extensions={'id': 109}, groups=['SR_SELID_6'])
vlab.register(name='MPUA7', width=32, extensions={'id': 110}, groups=['SR_SELID_6'])
vlab.register(name='MPAT7', width=32, extensions={'id': 111}, groups=['SR_SELID_6'])
vlab.field(name='MPAT7_ASID', register='MPAT7', offset=16, width=10)
vlab.field(name='MPAT7_E', register='MPAT7', offset=7, width=1)
vlab.field(name='MPAT7_G', register='MPAT7', offset=6, width=1)
vlab.field(name='MPAT7_SX', register='MPAT7', offset=5, width=1)
vlab.field(name='MPAT7_SW', register='MPAT7', offset=4, width=1)
vlab.field(name='MPAT7_SR', register='MPAT7', offset=3, width=1)
vlab.field(name='MPAT7_UX', register='MPAT7', offset=2, width=1)
vlab.field(name='MPAT7_UW', register='MPAT7', offset=1, width=1)
vlab.field(name='MPAT7_UR', register='MPAT7', offset=0, width=1)
vlab.register(name='MPLA8', width=32, extensions={'id': 112}, groups=['SR_SELID_7'])
vlab.register(name='MPUA8', width=32, extensions={'id': 113}, groups=['SR_SELID_7'])
vlab.register(name='MPAT8', width=32, extensions={'id': 114}, groups=['SR_SELID_7'])
vlab.field(name='MPAT8_ASID', register='MPAT8', offset=16, width=10)
vlab.field(name='MPAT8_E', register='MPAT8', offset=7, width=1)
vlab.field(name='MPAT8_G', register='MPAT8', offset=6, width=1)
vlab.field(name='MPAT8_SX', register='MPAT8', offset=5, width=1)
vlab.field(name='MPAT8_SW', register='MPAT8', offset=4, width=1)
vlab.field(name='MPAT8_SR', register='MPAT8', offset=3, width=1)
vlab.field(name='MPAT8_UX', register='MPAT8', offset=2, width=1)
vlab.field(name='MPAT8_UW', register='MPAT8', offset=1, width=1)
vlab.field(name='MPAT8_UR', register='MPAT8', offset=0, width=1)
vlab.register(name='MPLA9', width=32, extensions={'id': 115}, groups=['SR_SELID_7'])
vlab.register(name='MPUA9', width=32, extensions={'id': 116}, groups=['SR_SELID_7'])
vlab.register(name='MPAT9', width=32, extensions={'id': 117}, groups=['SR_SELID_7'])
vlab.field(name='MPAT9_ASID', register='MPAT9', offset=16, width=10)
vlab.field(name='MPAT9_E', register='MPAT9', offset=7, width=1)
vlab.field(name='MPAT9_G', register='MPAT9', offset=6, width=1)
vlab.field(name='MPAT9_SX', register='MPAT9', offset=5, width=1)
vlab.field(name='MPAT9_SW', register='MPAT9', offset=4, width=1)
vlab.field(name='MPAT9_SR', register='MPAT9', offset=3, width=1)
vlab.field(name='MPAT9_UX', register='MPAT9', offset=2, width=1)
vlab.field(name='MPAT9_UW', register='MPAT9', offset=1, width=1)
vlab.field(name='MPAT9_UR', register='MPAT9', offset=0, width=1)
vlab.register(name='MPLA10', width=32, extensions={'id': 118}, groups=['SR_SELID_7'])
vlab.register(name='MPUA10', width=32, extensions={'id': 119}, groups=['SR_SELID_7'])
vlab.register(name='MPAT10', width=32, extensions={'id': 120}, groups=['SR_SELID_7'])
vlab.field(name='MPAT10_ASID', register='MPAT10', offset=16, width=10)
vlab.field(name='MPAT10_E', register='MPAT10', offset=7, width=1)
vlab.field(name='MPAT10_G', register='MPAT10', offset=6, width=1)
vlab.field(name='MPAT10_SX', register='MPAT10', offset=5, width=1)
vlab.field(name='MPAT10_SW', register='MPAT10', offset=4, width=1)
vlab.field(name='MPAT10_SR', register='MPAT10', offset=3, width=1)
vlab.field(name='MPAT10_UX', register='MPAT10', offset=2, width=1)
vlab.field(name='MPAT10_UW', register='MPAT10', offset=1, width=1)
vlab.field(name='MPAT10_UR', register='MPAT10', offset=0, width=1)
vlab.register(name='MPLA11', width=32, extensions={'id': 121}, groups=['SR_SELID_7'])
vlab.register(name='MPUA11', width=32, extensions={'id': 122}, groups=['SR_SELID_7'])
vlab.register(name='MPAT11', width=32, extensions={'id': 123}, groups=['SR_SELID_7'])
vlab.field(name='MPAT11_ASID', register='MPAT11', offset=16, width=10)
vlab.field(name='MPAT11_E', register='MPAT11', offset=7, width=1)
vlab.field(name='MPAT11_G', register='MPAT11', offset=6, width=1)
vlab.field(name='MPAT11_SX', register='MPAT11', offset=5, width=1)
vlab.field(name='MPAT11_SW', register='MPAT11', offset=4, width=1)
vlab.field(name='MPAT11_SR', register='MPAT11', offset=3, width=1)
vlab.field(name='MPAT11_UX', register='MPAT11', offset=2, width=1)
vlab.field(name='MPAT11_UW', register='MPAT11', offset=1, width=1)
vlab.field(name='MPAT11_UR', register='MPAT11', offset=0, width=1)
vlab.register(name='MPLA12', width=32, extensions={'id': 124}, groups=['SR_SELID_7'])
vlab.register(name='MPUA12', width=32, extensions={'id': 125}, groups=['SR_SELID_7'])
vlab.register(name='MPAT12', width=32, extensions={'id': 126}, groups=['SR_SELID_7'])
vlab.field(name='MPAT12_ASID', register='MPAT12', offset=16, width=10)
vlab.field(name='MPAT12_E', register='MPAT12', offset=7, width=1)
vlab.field(name='MPAT12_G', register='MPAT12', offset=6, width=1)
vlab.field(name='MPAT12_SX', register='MPAT12', offset=5, width=1)
vlab.field(name='MPAT12_SW', register='MPAT12', offset=4, width=1)
vlab.field(name='MPAT12_SR', register='MPAT12', offset=3, width=1)
vlab.field(name='MPAT12_UX', register='MPAT12', offset=2, width=1)
vlab.field(name='MPAT12_UW', register='MPAT12', offset=1, width=1)
vlab.field(name='MPAT12_UR', register='MPAT12', offset=0, width=1)
vlab.register(name='MPLA13', width=32, extensions={'id': 127}, groups=['SR_SELID_7'])
vlab.register(name='MPUA13', width=32, extensions={'id': 128}, groups=['SR_SELID_7'])
vlab.register(name='MPAT13', width=32, extensions={'id': 129}, groups=['SR_SELID_7'])
vlab.field(name='MPAT13_ASID', register='MPAT13', offset=16, width=10)
vlab.field(name='MPAT13_E', register='MPAT13', offset=7, width=1)
vlab.field(name='MPAT13_G', register='MPAT13', offset=6, width=1)
vlab.field(name='MPAT13_SX', register='MPAT13', offset=5, width=1)
vlab.field(name='MPAT13_SW', register='MPAT13', offset=4, width=1)
vlab.field(name='MPAT13_SR', register='MPAT13', offset=3, width=1)
vlab.field(name='MPAT13_UX', register='MPAT13', offset=2, width=1)
vlab.field(name='MPAT13_UW', register='MPAT13', offset=1, width=1)
vlab.field(name='MPAT13_UR', register='MPAT13', offset=0, width=1)
vlab.register(name='MPLA14', width=32, extensions={'id': 130}, groups=['SR_SELID_7'])
vlab.register(name='MPUA14', width=32, extensions={'id': 131}, groups=['SR_SELID_7'])
vlab.register(name='MPAT14', width=32, extensions={'id': 132}, groups=['SR_SELID_7'])
vlab.field(name='MPAT14_ASID', register='MPAT14', offset=16, width=10)
vlab.field(name='MPAT14_E', register='MPAT14', offset=7, width=1)
vlab.field(name='MPAT14_G', register='MPAT14', offset=6, width=1)
vlab.field(name='MPAT14_SX', register='MPAT14', offset=5, width=1)
vlab.field(name='MPAT14_SW', register='MPAT14', offset=4, width=1)
vlab.field(name='MPAT14_SR', register='MPAT14', offset=3, width=1)
vlab.field(name='MPAT14_UX', register='MPAT14', offset=2, width=1)
vlab.field(name='MPAT14_UW', register='MPAT14', offset=1, width=1)
vlab.field(name='MPAT14_UR', register='MPAT14', offset=0, width=1)
vlab.register(name='MPLA15', width=32, extensions={'id': 133}, groups=['SR_SELID_7'])
vlab.register(name='MPUA15', width=32, extensions={'id': 134}, groups=['SR_SELID_7'])
vlab.register(name='MPAT15', width=32, extensions={'id': 135}, groups=['SR_SELID_7'])
vlab.field(name='MPAT15_ASID', register='MPAT15', offset=16, width=10)
vlab.field(name='MPAT15_E', register='MPAT15', offset=7, width=1)
vlab.field(name='MPAT15_G', register='MPAT15', offset=6, width=1)
vlab.field(name='MPAT15_SX', register='MPAT15', offset=5, width=1)
vlab.field(name='MPAT15_SW', register='MPAT15', offset=4, width=1)
vlab.field(name='MPAT15_SR', register='MPAT15', offset=3, width=1)
vlab.field(name='MPAT15_UX', register='MPAT15', offset=2, width=1)
vlab.field(name='MPAT15_UW', register='MPAT15', offset=1, width=1)
vlab.field(name='MPAT15_UR', register='MPAT15', offset=0, width=1)
vlab.register(name='mpu_entry', width=8, extensions={'id': 136})
vlab.register(name='mpat_g_support', width=8, extensions={'id': 137})
vlab.register(name='swd0pcad_exec_count', width=32, extensions={'id': 138})
vlab.register(name='swd0pcad_val', width=32, extensions={'id': 139})
vlab.register(name='mem_acc_type', width=32, extensions={'id': 140})

#------------------------------------------------------------------------------
# End of file
#------------------------------------------------------------------------------
