// -----------------------------------------------------------------------------
// $Id: ecccom_regif.h,v 1.1 2013/08/19 02:33:28 dungvannguyen Exp $
//
// Copyright(c) 2010-2013 Renesas Electronics Corporation
// Copyright(c) 2010-2013 Renesas Design Vietnam Co., Ltd.
// RENESAS ELECTRONICS CONFIDENTIAL AND PROPRIETARY.
// This program must be used solely for the purpose for which
// it was furnished by Renesas Electronics Corporation. No part of this
// program may be reproduced or disclosed to others, in any
// form, without the prior written permission of Renesas Electronics
// Corporation.
// -----------------------------------------------------------------------------
// This file is generated by Register I/F generator
//    gen_regif.py 1.9 2013/12/04 09:51:36 sontran
//    gen_regif_class.py 1.59 2014/05/19 02:28:17 sontran
//    regif_h.skl 1.29 2014/05/09 02:57:13 sontran
//
// Input file : ecccom_regif.txt
////////////////////////////////////////////////////////////////////////////////
// %MODULE ECCCom
//     #                 name       offset_size
//     %%REG_INSTANCE    reg_def        8
// 
// %REG_CHANNEL reg_def
//     %%TITLE     group   name        reg_name     wsize    rsize    length   offset  factor_start  factor_end  factor_index  access   init  support  callback
//     %%REG       -       ECCCTL      ECCCTL      16|32    8|16|32   32       0x0         -           -             -         W|R       0     TRUE     -
//     %%REG       -       ERRINT      ERRINT      8|16|32  8|16|32   32       0x4         -           -             -         W|R       0     TRUE     -
//     %%REG       -       SSTCLR      SSTCLR      8|16|32  8|16|32   32       0x8         -           -             -         W         0     TRUE     -
//     %%REG       -       DSTCLR      DSTCLR      8|16|32  8|16|32   32       0xC         -           -             -         W         0     TRUE     -
//     %%REG       -       OVFSTR      OVFSTR      8|16|32  8|16|32   32       0x10        -           -             -         R         0     TRUE     -
//     %%REG       -       S1STERSTR   S1STERSTR   8|16|32  8|16|32   32       0x20        -           -             -         R         0     TRUE     -
//     %%REG       -       S2NDERSTR   S2NDERSTR   8|16|32  8|16|32   32       0x24        -           -             -         R         0     TRUE     -
//     %%REG       -       S3RDERSTR   S3RDERSTR   8|16|32  8|16|32   32       0x28        -           -             -         R         0     TRUE     -
//     %%REG       -       S4THERSTR   S4THERSTR   8|16|32  8|16|32   32       0x2C        -           -             -         R         0     TRUE     -
//     %%REG       -       S5THERSTR   S5THERSTR   8|16|32  8|16|32   32       0x30        -           -             -         R         0     TRUE     -
//     %%REG       -       S6THERSTR   S6THERSTR   8|16|32  8|16|32   32       0x34        -           -             -         R         0     TRUE     -
//     %%REG       -       S7THERSTR   S7THERSTR   8|16|32  8|16|32   32       0x38        -           -             -         R         0     TRUE     -
//     %%REG       -       S8THERSTR   S8THERSTR   8|16|32  8|16|32   32       0x3C        -           -             -         R         0     TRUE     -
//     %%REG       -       SEDERSTR    SEDERSTR    8|16|32  8|16|32   32       0x40        -           -             -         R         0     TRUE     -
//     %%REG       -       D1STERSTR   D1STERSTR   8|16|32  8|16|32   32       0x50        -           -             -         R         0     TRUE     -
//     %%REG       -       S1STEADR    S1STEADR    32       8|16|32   32       0x60        0           3             -         R         0     TRUE     -
//     %%REG       -       S2NDEADR    S2NDEADR    32       8|16|32   32       0x70        0           3             -         R         0     TRUE     -
//     %%REG       -       S3RDEADR    S3RDEADR    32       8|16|32   32       0x80        0           3             -         R         0     TRUE     -
//     %%REG       -       S4THEADR    S4THEADR    32       8|16|32   32       0x90        0           3             -         R         0     TRUE     -
//     %%REG       -       S5THEADR    S5THEADR    32       8|16|32   32       0xA0        0           3             -         R         0     TRUE     -
//     %%REG       -       S6THEADR    S6THEADR    32       8|16|32   32       0xB0        0           3             -         R         0     TRUE     -
//     %%REG       -       S7THEADR    S7THEADR    32       8|16|32   32       0xC0        0           3             -         R         0     TRUE     -
//     %%REG       -       S8THEADR    S8THEADR    32       8|16|32   32       0xD0        0           3             -         R         0     TRUE     -
//     %%REG       -       D1STEADR    D1STEADR    32       8|16|32   32       0xE0        0           3             -         R         0     TRUE     -
//     %%REG       -       STSTCTL     STSTCTL     16|32    8|16|32   32       0xF0        -           -             -         W|R       0     TRUE     -
// 
// %REG_NAME ECCCTL
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    ECCDIS      0      0      0     W|R      TRUE     W
//     %%BIT    SECDIS      1      1      0     W|R      TRUE     -
//     %%BIT    AECCDIS     2      2      0     W|R      TRUE     -
//     %%BIT    ASECDIS     3      3      0     W|R      TRUE     -
//     %%BIT    PROT0       14     14     0     W|R      TRUE     -
//     %%BIT    PROT1       15     15     0     W|R      TRUE     -
// 
// %REG_NAME ERRINT
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEDIE       0      0      0     W|R      TRUE     -
//     %%BIT    DEDIE       1      1      0     W|R      TRUE     -
//     %%BIT    APEIE       2      2      0     W|R      TRUE     -
//     %%BIT    PBEIE       3      3      0     W|R      TRUE     -
//     %%BIT    ASEDIE      4      4      0     W|R      TRUE     -
//     %%BIT    ADEDIE      5      5      0     W|R      TRUE     -
//     %%BIT    SEOVFIE     6      6      0     W|R      TRUE     -
// 
// %REG_NAME SSTCLR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SSTCLR10    0      0      0     W        TRUE     W
//     %%BIT    SSTCLR11    1      1      0     W        TRUE     -
//     %%BIT    SSTCLR12    2      2      0     W        TRUE     -
//     %%BIT    SSTCLR13    3      3      0     W        TRUE     -
//     %%BIT    SSTCLR20    4      4      0     W        TRUE     -
//     %%BIT    SSTCLR21    5      5      0     W        TRUE     -
//     %%BIT    SSTCLR22    6      6      0     W        TRUE     -
//     %%BIT    SSTCLR23    7      7      0     W        TRUE     -
//     %%BIT    SSTCLR30    8      8      0     W        TRUE     -
//     %%BIT    SSTCLR31    9      9      0     W        TRUE     -
//     %%BIT    SSTCLR32    10     10     0     W        TRUE     -
//     %%BIT    SSTCLR33    11     11     0     W        TRUE     -
//     %%BIT    SSTCLR40    12     12     0     W        TRUE     -
//     %%BIT    SSTCLR41    13     13     0     W        TRUE     -
//     %%BIT    SSTCLR42    14     14     0     W        TRUE     -
//     %%BIT    SSTCLR43    15     15     0     W        TRUE     -
//     %%BIT    SSTCLR50    16     16     0     W        TRUE     -
//     %%BIT    SSTCLR51    17     17     0     W        TRUE     -
//     %%BIT    SSTCLR52    18     18     0     W        TRUE     -
//     %%BIT    SSTCLR53    19     19     0     W        TRUE     -
//     %%BIT    SSTCLR60    20     20     0     W        TRUE     -
//     %%BIT    SSTCLR61    21     21     0     W        TRUE     -
//     %%BIT    SSTCLR62    22     22     0     W        TRUE     -
//     %%BIT    SSTCLR63    23     23     0     W        TRUE     -
//     %%BIT    SSTCLR70    24     24     0     W        TRUE     -
//     %%BIT    SSTCLR71    25     25     0     W        TRUE     -
//     %%BIT    SSTCLR72    26     26     0     W        TRUE     -
//     %%BIT    SSTCLR73    27     27     0     W        TRUE     -
//     %%BIT    SSTCLR80    28     28     0     W        TRUE     -
//     %%BIT    SSTCLR81    29     29     0     W        TRUE     -
//     %%BIT    SSTCLR82    30     30     0     W        TRUE     -
//     %%BIT    SSTCLR83    31     31     0     W        TRUE     -
// 
// %REG_NAME DSTCLR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    DSTCLR0     0      0      0     W        TRUE     W
//     %%BIT    DSTCLR1     1      1      0     W        TRUE     -
//     %%BIT    DSTCLR2     2      2      0     W        TRUE     -
//     %%BIT    DSTCLR3     3      3      0     W        TRUE     -
// 
// %REG_NAME OVFSTR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SERROVF0     0      0      0    R        TRUE    -
//     %%BIT    SERROVF1     1      1      0    R        TRUE    -
//     %%BIT    SERROVF2     2      2      0    R        TRUE    -
//     %%BIT    SERROVF3     3      3      0    R        TRUE    -
//     %%BIT    DERROVF0     4      4      0    R        TRUE    -
//     %%BIT    DERROVF1     5      5      0    R        TRUE    -
//     %%BIT    DERROVF2     6      6      0    R        TRUE    -
//     %%BIT    DERROVF3     7      7      0    R        TRUE    -
// 
// %REG_NAME S1STERSTR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEDF10       0      0      0    R        TRUE    -
//     %%BIT    PBEF10       3      3      0    R        TRUE    -
//     %%BIT    EXSEDF10     4      4      0    R        TRUE    -
//     %%BIT    AECSEDF10    6      6      0    R        TRUE    -
//     %%BIT    SEDF11       8      8      0    R        TRUE    -
//     %%BIT    PBEF11       11     11     0    R        TRUE    -
//     %%BIT    EXSEDF11     12     12     0    R        TRUE    -
//     %%BIT    AECSEDF11    14     14     0    R        TRUE    -
//     %%BIT    SEDF12       16     16     0    R        TRUE    -
//     %%BIT    PBEF12       19     19     0    R        TRUE    -
//     %%BIT    EXSEDF12     20     20     0    R        TRUE    -
//     %%BIT    AECSEDF12    22     22     0    R        TRUE    -
//     %%BIT    SEDF13       24     24     0    R        TRUE    -
//     %%BIT    PBEF13       27     27     0    R        TRUE    -
//     %%BIT    EXSEDF13     28     28     0    R        TRUE    -
//     %%BIT    AECSEDF13    30     30     0    R        TRUE    -
// 
// %REG_NAME S2NDERSTR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEDF20       0      0      0    R        TRUE    -
//     %%BIT    PBEF20       3      3      0    R        TRUE    -
//     %%BIT    EXSEDF20     4      4      0    R        TRUE    -
//     %%BIT    AECSEDF20    6      6      0    R        TRUE    -
//     %%BIT    SEDF21       8      8      0    R        TRUE    -
//     %%BIT    PBEF21       11     11     0    R        TRUE    -
//     %%BIT    EXSEDF21     12     12     0    R        TRUE    -
//     %%BIT    AECSEDF21    14     14     0    R        TRUE    -
//     %%BIT    SEDF22       16     16     0    R        TRUE    -
//     %%BIT    PBEF22       19     19     0    R        TRUE    -
//     %%BIT    EXSEDF22     20     20     0    R        TRUE    -
//     %%BIT    AECSEDF22    22     22     0    R        TRUE    -
//     %%BIT    SEDF23       24     24     0    R        TRUE    -
//     %%BIT    PBEF23       27     27     0    R        TRUE    -
//     %%BIT    EXSEDF23     28     28     0    R        TRUE    -
//     %%BIT    AECSEDF23    30     30     0    R        TRUE    -
// 
// %REG_NAME S3RDERSTR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEDF30       0      0      0    R        TRUE    -
//     %%BIT    PBEF30       3      3      0    R        TRUE    -
//     %%BIT    EXSEDF30     4      4      0    R        TRUE    -
//     %%BIT    AECSEDF30    6      6      0    R        TRUE    -
//     %%BIT    SEDF31       8      8      0    R        TRUE    -
//     %%BIT    PBEF31       11     11     0    R        TRUE    -
//     %%BIT    EXSEDF31     12     12     0    R        TRUE    -
//     %%BIT    AECSEDF31    14     14     0    R        TRUE    -
//     %%BIT    SEDF32       16     16     0    R        TRUE    -
//     %%BIT    PBEF32       19     19     0    R        TRUE    -
//     %%BIT    EXSEDF32     20     20     0    R        TRUE    -
//     %%BIT    AECSEDF32    22     22     0    R        TRUE    -
//     %%BIT    SEDF33       24     24     0    R        TRUE    -
//     %%BIT    PBEF33       27     27     0    R        TRUE    -
//     %%BIT    EXSEDF33     28     28     0    R        TRUE    -
//     %%BIT    AECSEDF33    30     30     0    R        TRUE    -
// 
// %REG_NAME S4THERSTR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEDF40       0      0      0    R        TRUE    -
//     %%BIT    PBEF40       3      3      0    R        TRUE    -
//     %%BIT    EXSEDF40     4      4      0    R        TRUE    -
//     %%BIT    AECSEDF40    6      6      0    R        TRUE    -
//     %%BIT    SEDF41       8      8      0    R        TRUE    -
//     %%BIT    PBEF41       11     11     0    R        TRUE    -
//     %%BIT    EXSEDF41     12     12     0    R        TRUE    -
//     %%BIT    AECSEDF41    14     14     0    R        TRUE    -
//     %%BIT    SEDF42       16     16     0    R        TRUE    -
//     %%BIT    PBEF42       19     19     0    R        TRUE    -
//     %%BIT    EXSEDF42     20     20     0    R        TRUE    -
//     %%BIT    AECSEDF42    22     22     0    R        TRUE    -
//     %%BIT    SEDF43       24     24     0    R        TRUE    -
//     %%BIT    PBEF43       27     27     0    R        TRUE    -
//     %%BIT    EXSEDF43     28     28     0    R        TRUE    -
//     %%BIT    AECSEDF43    30     30     0    R        TRUE    -
// 
// %REG_NAME S5THERSTR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEDF50       0      0      0    R        TRUE    -
//     %%BIT    PBEF50       3      3      0    R        TRUE    -
//     %%BIT    EXSEDF50     4      4      0    R        TRUE    -
//     %%BIT    AECSEDF50    6      6      0    R        TRUE    -
//     %%BIT    SEDF51       8      8      0    R        TRUE    -
//     %%BIT    PBEF51       11     11     0    R        TRUE    -
//     %%BIT    EXSEDF51     12     12     0    R        TRUE    -
//     %%BIT    AECSEDF51    14     14     0    R        TRUE    -
//     %%BIT    SEDF52       16     16     0    R        TRUE    -
//     %%BIT    PBEF52       19     19     0    R        TRUE    -
//     %%BIT    EXSEDF52     20     20     0    R        TRUE    -
//     %%BIT    AECSEDF52    22     22     0    R        TRUE    -
//     %%BIT    SEDF53       24     24     0    R        TRUE    -
//     %%BIT    PBEF53       27     27     0    R        TRUE    -
//     %%BIT    EXSEDF53     28     28     0    R        TRUE    -
//     %%BIT    AECSEDF53    30     30     0    R        TRUE    -
// 
// %REG_NAME S6THERSTR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEDF60       0      0      0    R        TRUE    -
//     %%BIT    PBEF60       3      3      0    R        TRUE    -
//     %%BIT    EXSEDF60     4      4      0    R        TRUE    -
//     %%BIT    AECSEDF60    6      6      0    R        TRUE    -
//     %%BIT    SEDF61       8      8      0    R        TRUE    -
//     %%BIT    PBEF61       11     11     0    R        TRUE    -
//     %%BIT    EXSEDF61     12     12     0    R        TRUE    -
//     %%BIT    AECSEDF61    14     14     0    R        TRUE    -
//     %%BIT    SEDF62       16     16     0    R        TRUE    -
//     %%BIT    PBEF62       19     19     0    R        TRUE    -
//     %%BIT    EXSEDF62     20     20     0    R        TRUE    -
//     %%BIT    AECSEDF62    22     22     0    R        TRUE    -
//     %%BIT    SEDF63       24     24     0    R        TRUE    -
//     %%BIT    PBEF63       27     27     0    R        TRUE    -
//     %%BIT    EXSEDF63     28     28     0    R        TRUE    -
//     %%BIT    AECSEDF63    30     30     0    R        TRUE    -
// 
// %REG_NAME S7THERSTR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEDF70       0      0      0    R        TRUE    -
//     %%BIT    PBEF70       3      3      0    R        TRUE    -
//     %%BIT    EXSEDF70     4      4      0    R        TRUE    -
//     %%BIT    AECSEDF70    6      6      0    R        TRUE    -
//     %%BIT    SEDF71       8      8      0    R        TRUE    -
//     %%BIT    PBEF71       11     11     0    R        TRUE    -
//     %%BIT    EXSEDF71     12     12     0    R        TRUE    -
//     %%BIT    AECSEDF71    14     14     0    R        TRUE    -
//     %%BIT    SEDF72       16     16     0    R        TRUE    -
//     %%BIT    PBEF72       19     19     0    R        TRUE    -
//     %%BIT    EXSEDF72     20     20     0    R        TRUE    -
//     %%BIT    AECSEDF72    22     22     0    R        TRUE    -
//     %%BIT    SEDF73       24     24     0    R        TRUE    -
//     %%BIT    PBEF73       27     27     0    R        TRUE    -
//     %%BIT    EXSEDF73     28     28     0    R        TRUE    -
//     %%BIT    AECSEDF73    30     30     0    R        TRUE    -
// 
// %REG_NAME S8THERSTR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEDF80       0      0      0    R        TRUE    -
//     %%BIT    PBEF80       3      3      0    R        TRUE    -
//     %%BIT    EXSEDF80     4      4      0    R        TRUE    -
//     %%BIT    AECSEDF80    6      6      0    R        TRUE    -
//     %%BIT    SEDF81       8      8      0    R        TRUE    -
//     %%BIT    PBEF81       11     11     0    R        TRUE    -
//     %%BIT    EXSEDF81     12     12     0    R        TRUE    -
//     %%BIT    AECSEDF81    14     14     0    R        TRUE    -
//     %%BIT    SEDF82       16     16     0    R        TRUE    -
//     %%BIT    PBEF82       19     19     0    R        TRUE    -
//     %%BIT    EXSEDF82     20     20     0    R        TRUE    -
//     %%BIT    AECSEDF82    22     22     0    R        TRUE    -
//     %%BIT    SEDF83       24     24     0    R        TRUE    -
//     %%BIT    PBEF83       27     27     0    R        TRUE    -
//     %%BIT    EXSEDF83     28     28     0    R        TRUE    -
//     %%BIT    AECSEDF83    30     30     0    R        TRUE    -
// 
// %REG_NAME SEDERSTR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEDF10       0      0      0    R        TRUE    -
//     %%BIT    SEDF11       1      1      0    R        TRUE    -
//     %%BIT    SEDF12       2      2      0    R        TRUE    -
//     %%BIT    SEDF13       3      3      0    R        TRUE    -
//     %%BIT    SEDF20       4      4      0    R        TRUE    -
//     %%BIT    SEDF21       5      5      0    R        TRUE    -
//     %%BIT    SEDF22       6      6      0    R        TRUE    -
//     %%BIT    SEDF23       7      7      0    R        TRUE    -
//     %%BIT    SEDF30       8      8      0    R        TRUE    -
//     %%BIT    SEDF31       9      9      0    R        TRUE    -
//     %%BIT    SEDF32       10     10     0    R        TRUE    -
//     %%BIT    SEDF33       11     11     0    R        TRUE    -
//     %%BIT    SEDF40       12     12     0    R        TRUE    -
//     %%BIT    SEDF41       13     13     0    R        TRUE    -
//     %%BIT    SEDF42       14     14     0    R        TRUE    -
//     %%BIT    SEDF43       15     15     0    R        TRUE    -
//     %%BIT    SEDF50       16     16     0    R        TRUE    -
//     %%BIT    SEDF51       17     17     0    R        TRUE    -
//     %%BIT    SEDF52       18     18     0    R        TRUE    -
//     %%BIT    SEDF53       19     19     0    R        TRUE    -
//     %%BIT    SEDF60       20     20     0    R        TRUE    -
//     %%BIT    SEDF61       21     21     0    R        TRUE    -
//     %%BIT    SEDF62       22     22     0    R        TRUE    -
//     %%BIT    SEDF63       23     23     0    R        TRUE    -
//     %%BIT    SEDF70       24     24     0    R        TRUE    -
//     %%BIT    SEDF71       25     25     0    R        TRUE    -
//     %%BIT    SEDF72       26     26     0    R        TRUE    -
//     %%BIT    SEDF73       27     27     0    R        TRUE    -
//     %%BIT    SEDF80       28     28     0    R        TRUE    -
//     %%BIT    SEDF81       29     29     0    R        TRUE    -
//     %%BIT    SEDF82       30     30     0    R        TRUE    -
//     %%BIT    SEDF83       31     31     0    R        TRUE    -
// 
// %REG_NAME D1STERSTR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    DEDF0        1      1      0    R        TRUE    -
//     %%BIT    APEF0        2      2      0    R        TRUE    -
//     %%BIT    EXDEDF0      5      5      0    R        TRUE    -
//     %%BIT    AECDEDF0     7      7      0    R        TRUE    -
//     %%BIT    DEDF1        9      9      0    R        TRUE    -
//     %%BIT    APEF1        10     10     0    R        TRUE    -
//     %%BIT    EXDEDF1      13     13     0    R        TRUE    -
//     %%BIT    AECDEDF1     15     15     0    R        TRUE    -
//     %%BIT    DEDF2        17     17     0    R        TRUE    -
//     %%BIT    APEF2        18     18     0    R        TRUE    -
//     %%BIT    EXDEDF2      21     21     0    R        TRUE    -
//     %%BIT    AECDEDF2     23     23     0    R        TRUE    -
//     %%BIT    DEDF3        25     25     0    R        TRUE    -
//     %%BIT    APEF3        26     26     0    R        TRUE    -
//     %%BIT    EXDEDF3      29     29     0    R        TRUE    -
//     %%BIT    AECDEDF3     31     31     0    R        TRUE    -
// 
// %REG_NAME S1STEADR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEADR1       31      0      0    R        TRUE    -
// 
// %REG_NAME S2NDEADR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEADR2       31      0      0    R        TRUE    -
// 
// %REG_NAME S3RDEADR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEADR3       31      0      0    R        TRUE    -
// 
// %REG_NAME S4THEADR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEADR4       31      0      0    R        TRUE    -
// 
// %REG_NAME S5THEADR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEADR5       31      0      0    R        TRUE    -
// 
// %REG_NAME S6THEADR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEADR6       31      0      0    R        TRUE    -
// 
// %REG_NAME S7THEADR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEADR7       31      0      0    R        TRUE    -
// 
// %REG_NAME S8THEADR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    SEADR8       31      0      0    R        TRUE    -
// 
// %REG_NAME D1STEADR
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    DEADR        31      0      0    R        TRUE    -
// 
// %REG_NAME STSTCTL
//     %%TITLE  name        upper  lower  init  access  support  callback                                     
//     %%BIT    ECCTST       0       0      0    W|R      TRUE    W
//     %%BIT    PROT0        14      14     0    W|R      TRUE    -
//     %%BIT    PROT1        15      15     0    W|R      TRUE    -
////////////////////////////////////////////////////////////////////////////////
/// @file ecccom_regif.h
/// @brief Register IF class of model ECCCOM
/// $Id$
/// $Date$
/// $Revison$
/// $Author$
////////////////////////////////////////////////////////////////////////////////
#ifndef __ECCCOM_REGIF_H__
#define __ECCCOM_REGIF_H__
#include <string>
#include <map>
#include <list>
#include <cstdarg>
#include <cerrno>
#include <iomanip>
#include <sstream>
#ifdef REGIF_NOT_USE_SYSTEMC
#include <cassert>
#else
#include "systemc.h"
#endif
#include "re_register.h"
#ifdef CWR_SYSTEMC
#include "scml.h"
#endif

/// Register IF class of ECCCOM model
class Cecccom_regif
: public vpcl::reg_super
{
protected:
    typedef const unsigned int cuint;
    typedef unsigned int uint;

    enum eRegGroup {
        emNum_of_gr
    }; ///< Enumeration for register group index
    enum eRegIndex {
        emNUM_S1STEADR  = 4,
        emNUM_S2NDEADR  = 4,
        emNUM_S3RDEADR  = 4,
        emNUM_S4THEADR  = 4,
        emNUM_S5THEADR  = 4,
        emNUM_S6THEADR  = 4,
        emNUM_S7THEADR  = 4,
        emNUM_S8THEADR  = 4,
        emNUM_D1STEADR  = 4
    }; ///< Enumeration for register factor index

    struct RegCBstr {
        uint channel;
        bool is_wr;
        uint size;
        uint pre_data;
        uint data;
        RegCBstr (uint channel, bool is_wr, uint size, uint pre_data, uint data)
        {
            this-> channel = channel;
            this-> is_wr   = is_wr;
            this-> size    = size;
            this-> pre_data= pre_data;
            this-> data    = data;
        }
    };
    struct SRegList {
        vpcl::re_register *my_p;
        SRegList *prev;
        uint channel;
        uint length;
        std::string wacc_size;
        std::string racc_size;
        bool block;
        SRegList( vpcl::re_register *_my_p, SRegList *_prev, uint _channel, uint _length, std::string _wacc_size, std::string _racc_size, bool _block = false) {
            this->my_p = NULL;
            if (_my_p != NULL) {
                this->my_p = _my_p;
            }
            this->prev = NULL;
            if (_prev != NULL) {
                this->prev = _prev;
            }
            this->channel = _channel;
            this->length  = _length;
            this->wacc_size = _wacc_size;
            this->racc_size = _racc_size;
            this->block = _block;
        }
    } *mRegList, *mCurReg, **mRegArray;

    uint *mRegMap;
    uint mTotalRegNum;

public:
    Cecccom_regif(std::string name,
                  uint buswidth,
                  uint ECCCTLInitial = 0,
                  uint ERRINTInitial = 0,
                  bool UeabMode = false);
    ~Cecccom_regif();

protected:
    vpcl::re_register *ECCCTL   ;
    vpcl::re_register *ERRINT   ;
    vpcl::re_register *SSTCLR   ;
    vpcl::re_register *DSTCLR   ;
    vpcl::re_register *OVFSTR   ;
    vpcl::re_register *S1STERSTR;
    vpcl::re_register *S2NDERSTR;
    vpcl::re_register *S3RDERSTR;
    vpcl::re_register *S4THERSTR;
    vpcl::re_register *S5THERSTR;
    vpcl::re_register *S6THERSTR;
    vpcl::re_register *S7THERSTR;
    vpcl::re_register *S8THERSTR;
    vpcl::re_register *SEDERSTR ;
    vpcl::re_register *D1STERSTR;
    vpcl::re_register *S1STEADR [4];
    vpcl::re_register *S2NDEADR [4];
    vpcl::re_register *S3RDEADR [4];
    vpcl::re_register *S4THEADR [4];
    vpcl::re_register *S5THEADR [4];
    vpcl::re_register *S6THEADR [4];
    vpcl::re_register *S7THEADR [4];
    vpcl::re_register *S8THEADR [4];
    vpcl::re_register *D1STEADR [4];
    vpcl::re_register *STSTCTL  ;

    #ifdef CWR_SYSTEMC
    scml2::memory<uint> cwmem;
    scml2::reg<uint> *CW_ECCCTL   ;
    scml2::reg<uint> *CW_ERRINT   ;
    scml2::reg<uint> *CW_SSTCLR   ;
    scml2::reg<uint> *CW_DSTCLR   ;
    scml2::reg<uint> *CW_OVFSTR   ;
    scml2::reg<uint> *CW_S1STERSTR;
    scml2::reg<uint> *CW_S2NDERSTR;
    scml2::reg<uint> *CW_S3RDERSTR;
    scml2::reg<uint> *CW_S4THERSTR;
    scml2::reg<uint> *CW_S5THERSTR;
    scml2::reg<uint> *CW_S6THERSTR;
    scml2::reg<uint> *CW_S7THERSTR;
    scml2::reg<uint> *CW_S8THERSTR;
    scml2::reg<uint> *CW_SEDERSTR ;
    scml2::reg<uint> *CW_D1STERSTR;
    scml2::reg<uint> *CW_S1STEADR [4];
    scml2::reg<uint> *CW_S2NDEADR [4];
    scml2::reg<uint> *CW_S3RDEADR [4];
    scml2::reg<uint> *CW_S4THEADR [4];
    scml2::reg<uint> *CW_S5THEADR [4];
    scml2::reg<uint> *CW_S6THEADR [4];
    scml2::reg<uint> *CW_S7THEADR [4];
    scml2::reg<uint> *CW_S8THEADR [4];
    scml2::reg<uint> *CW_D1STEADR [4];
    scml2::reg<uint> *CW_STSTCTL  ;
    #endif

    uint ECCCTL_ECCDIS;
    uint ECCCTL_SECDIS;
    uint ECCCTL_AECCDIS;
    uint ECCCTL_ASECDIS;
    uint ECCCTL_PROT0;
    uint ECCCTL_PROT1;
    uint ERRINT_SEDIE;
    uint ERRINT_DEDIE;
    uint ERRINT_APEIE;
    uint ERRINT_PBEIE;
    uint ERRINT_ASEDIE;
    uint ERRINT_ADEDIE;
    uint ERRINT_SEOVFIE;
    uint SSTCLR_SSTCLR10;
    uint SSTCLR_SSTCLR11;
    uint SSTCLR_SSTCLR12;
    uint SSTCLR_SSTCLR13;
    uint SSTCLR_SSTCLR20;
    uint SSTCLR_SSTCLR21;
    uint SSTCLR_SSTCLR22;
    uint SSTCLR_SSTCLR23;
    uint SSTCLR_SSTCLR30;
    uint SSTCLR_SSTCLR31;
    uint SSTCLR_SSTCLR32;
    uint SSTCLR_SSTCLR33;
    uint SSTCLR_SSTCLR40;
    uint SSTCLR_SSTCLR41;
    uint SSTCLR_SSTCLR42;
    uint SSTCLR_SSTCLR43;
    uint SSTCLR_SSTCLR50;
    uint SSTCLR_SSTCLR51;
    uint SSTCLR_SSTCLR52;
    uint SSTCLR_SSTCLR53;
    uint SSTCLR_SSTCLR60;
    uint SSTCLR_SSTCLR61;
    uint SSTCLR_SSTCLR62;
    uint SSTCLR_SSTCLR63;
    uint SSTCLR_SSTCLR70;
    uint SSTCLR_SSTCLR71;
    uint SSTCLR_SSTCLR72;
    uint SSTCLR_SSTCLR73;
    uint SSTCLR_SSTCLR80;
    uint SSTCLR_SSTCLR81;
    uint SSTCLR_SSTCLR82;
    uint SSTCLR_SSTCLR83;
    uint DSTCLR_DSTCLR0;
    uint DSTCLR_DSTCLR1;
    uint DSTCLR_DSTCLR2;
    uint DSTCLR_DSTCLR3;
    uint OVFSTR_SERROVF0;
    uint OVFSTR_SERROVF1;
    uint OVFSTR_SERROVF2;
    uint OVFSTR_SERROVF3;
    uint OVFSTR_DERROVF0;
    uint OVFSTR_DERROVF1;
    uint OVFSTR_DERROVF2;
    uint OVFSTR_DERROVF3;
    uint S1STERSTR_SEDF10;
    uint S1STERSTR_PBEF10;
    uint S1STERSTR_EXSEDF10;
    uint S1STERSTR_AECSEDF10;
    uint S1STERSTR_SEDF11;
    uint S1STERSTR_PBEF11;
    uint S1STERSTR_EXSEDF11;
    uint S1STERSTR_AECSEDF11;
    uint S1STERSTR_SEDF12;
    uint S1STERSTR_PBEF12;
    uint S1STERSTR_EXSEDF12;
    uint S1STERSTR_AECSEDF12;
    uint S1STERSTR_SEDF13;
    uint S1STERSTR_PBEF13;
    uint S1STERSTR_EXSEDF13;
    uint S1STERSTR_AECSEDF13;
    uint S2NDERSTR_SEDF20;
    uint S2NDERSTR_PBEF20;
    uint S2NDERSTR_EXSEDF20;
    uint S2NDERSTR_AECSEDF20;
    uint S2NDERSTR_SEDF21;
    uint S2NDERSTR_PBEF21;
    uint S2NDERSTR_EXSEDF21;
    uint S2NDERSTR_AECSEDF21;
    uint S2NDERSTR_SEDF22;
    uint S2NDERSTR_PBEF22;
    uint S2NDERSTR_EXSEDF22;
    uint S2NDERSTR_AECSEDF22;
    uint S2NDERSTR_SEDF23;
    uint S2NDERSTR_PBEF23;
    uint S2NDERSTR_EXSEDF23;
    uint S2NDERSTR_AECSEDF23;
    uint S3RDERSTR_SEDF30;
    uint S3RDERSTR_PBEF30;
    uint S3RDERSTR_EXSEDF30;
    uint S3RDERSTR_AECSEDF30;
    uint S3RDERSTR_SEDF31;
    uint S3RDERSTR_PBEF31;
    uint S3RDERSTR_EXSEDF31;
    uint S3RDERSTR_AECSEDF31;
    uint S3RDERSTR_SEDF32;
    uint S3RDERSTR_PBEF32;
    uint S3RDERSTR_EXSEDF32;
    uint S3RDERSTR_AECSEDF32;
    uint S3RDERSTR_SEDF33;
    uint S3RDERSTR_PBEF33;
    uint S3RDERSTR_EXSEDF33;
    uint S3RDERSTR_AECSEDF33;
    uint S4THERSTR_SEDF40;
    uint S4THERSTR_PBEF40;
    uint S4THERSTR_EXSEDF40;
    uint S4THERSTR_AECSEDF40;
    uint S4THERSTR_SEDF41;
    uint S4THERSTR_PBEF41;
    uint S4THERSTR_EXSEDF41;
    uint S4THERSTR_AECSEDF41;
    uint S4THERSTR_SEDF42;
    uint S4THERSTR_PBEF42;
    uint S4THERSTR_EXSEDF42;
    uint S4THERSTR_AECSEDF42;
    uint S4THERSTR_SEDF43;
    uint S4THERSTR_PBEF43;
    uint S4THERSTR_EXSEDF43;
    uint S4THERSTR_AECSEDF43;
    uint S5THERSTR_SEDF50;
    uint S5THERSTR_PBEF50;
    uint S5THERSTR_EXSEDF50;
    uint S5THERSTR_AECSEDF50;
    uint S5THERSTR_SEDF51;
    uint S5THERSTR_PBEF51;
    uint S5THERSTR_EXSEDF51;
    uint S5THERSTR_AECSEDF51;
    uint S5THERSTR_SEDF52;
    uint S5THERSTR_PBEF52;
    uint S5THERSTR_EXSEDF52;
    uint S5THERSTR_AECSEDF52;
    uint S5THERSTR_SEDF53;
    uint S5THERSTR_PBEF53;
    uint S5THERSTR_EXSEDF53;
    uint S5THERSTR_AECSEDF53;
    uint S6THERSTR_SEDF60;
    uint S6THERSTR_PBEF60;
    uint S6THERSTR_EXSEDF60;
    uint S6THERSTR_AECSEDF60;
    uint S6THERSTR_SEDF61;
    uint S6THERSTR_PBEF61;
    uint S6THERSTR_EXSEDF61;
    uint S6THERSTR_AECSEDF61;
    uint S6THERSTR_SEDF62;
    uint S6THERSTR_PBEF62;
    uint S6THERSTR_EXSEDF62;
    uint S6THERSTR_AECSEDF62;
    uint S6THERSTR_SEDF63;
    uint S6THERSTR_PBEF63;
    uint S6THERSTR_EXSEDF63;
    uint S6THERSTR_AECSEDF63;
    uint S7THERSTR_SEDF70;
    uint S7THERSTR_PBEF70;
    uint S7THERSTR_EXSEDF70;
    uint S7THERSTR_AECSEDF70;
    uint S7THERSTR_SEDF71;
    uint S7THERSTR_PBEF71;
    uint S7THERSTR_EXSEDF71;
    uint S7THERSTR_AECSEDF71;
    uint S7THERSTR_SEDF72;
    uint S7THERSTR_PBEF72;
    uint S7THERSTR_EXSEDF72;
    uint S7THERSTR_AECSEDF72;
    uint S7THERSTR_SEDF73;
    uint S7THERSTR_PBEF73;
    uint S7THERSTR_EXSEDF73;
    uint S7THERSTR_AECSEDF73;
    uint S8THERSTR_SEDF80;
    uint S8THERSTR_PBEF80;
    uint S8THERSTR_EXSEDF80;
    uint S8THERSTR_AECSEDF80;
    uint S8THERSTR_SEDF81;
    uint S8THERSTR_PBEF81;
    uint S8THERSTR_EXSEDF81;
    uint S8THERSTR_AECSEDF81;
    uint S8THERSTR_SEDF82;
    uint S8THERSTR_PBEF82;
    uint S8THERSTR_EXSEDF82;
    uint S8THERSTR_AECSEDF82;
    uint S8THERSTR_SEDF83;
    uint S8THERSTR_PBEF83;
    uint S8THERSTR_EXSEDF83;
    uint S8THERSTR_AECSEDF83;
    uint SEDERSTR_SEDF10;
    uint SEDERSTR_SEDF11;
    uint SEDERSTR_SEDF12;
    uint SEDERSTR_SEDF13;
    uint SEDERSTR_SEDF20;
    uint SEDERSTR_SEDF21;
    uint SEDERSTR_SEDF22;
    uint SEDERSTR_SEDF23;
    uint SEDERSTR_SEDF30;
    uint SEDERSTR_SEDF31;
    uint SEDERSTR_SEDF32;
    uint SEDERSTR_SEDF33;
    uint SEDERSTR_SEDF40;
    uint SEDERSTR_SEDF41;
    uint SEDERSTR_SEDF42;
    uint SEDERSTR_SEDF43;
    uint SEDERSTR_SEDF50;
    uint SEDERSTR_SEDF51;
    uint SEDERSTR_SEDF52;
    uint SEDERSTR_SEDF53;
    uint SEDERSTR_SEDF60;
    uint SEDERSTR_SEDF61;
    uint SEDERSTR_SEDF62;
    uint SEDERSTR_SEDF63;
    uint SEDERSTR_SEDF70;
    uint SEDERSTR_SEDF71;
    uint SEDERSTR_SEDF72;
    uint SEDERSTR_SEDF73;
    uint SEDERSTR_SEDF80;
    uint SEDERSTR_SEDF81;
    uint SEDERSTR_SEDF82;
    uint SEDERSTR_SEDF83;
    uint D1STERSTR_DEDF0;
    uint D1STERSTR_APEF0;
    uint D1STERSTR_EXDEDF0;
    uint D1STERSTR_AECDEDF0;
    uint D1STERSTR_DEDF1;
    uint D1STERSTR_APEF1;
    uint D1STERSTR_EXDEDF1;
    uint D1STERSTR_AECDEDF1;
    uint D1STERSTR_DEDF2;
    uint D1STERSTR_APEF2;
    uint D1STERSTR_EXDEDF2;
    uint D1STERSTR_AECDEDF2;
    uint D1STERSTR_DEDF3;
    uint D1STERSTR_APEF3;
    uint D1STERSTR_EXDEDF3;
    uint D1STERSTR_AECDEDF3;
    uint S1STEADR_SEADR1[4];
    uint S2NDEADR_SEADR2[4];
    uint S3RDEADR_SEADR3[4];
    uint S4THEADR_SEADR4[4];
    uint S5THEADR_SEADR5[4];
    uint S6THEADR_SEADR6[4];
    uint S7THEADR_SEADR7[4];
    uint S8THEADR_SEADR8[4];
    uint D1STEADR_DEADR[4];
    uint STSTCTL_ECCTST;
    uint STSTCTL_PROT0;
    uint STSTCTL_PROT1;

    void EnableReset(const bool is_active, const std::string clock_domain);
    uint bit_select(cuint val, cuint start, cuint end);
    bool reg_wr(cuint addr, const unsigned char *p_data, cuint size);
    bool reg_rd(cuint addr, unsigned char *p_data, cuint size);
    bool reg_wr_dbg(cuint addr, const unsigned char *p_data, cuint size);
    bool reg_rd_dbg(cuint addr, unsigned char *p_data, cuint size);
    std::string reg_handle_command(const std::vector<std::string>& args);
    int get_reg_index(cuint addr);
    vpcl::re_register *first_reg_object();
    vpcl::re_register *next_reg_object();

    void wr_cb(cuint addr, uint data);
    uint rd_cb(cuint addr);

    virtual void cb_ECCCTL_ECCDIS(RegCBstr str) = 0;
    virtual void cb_SSTCLR_SSTCLR10(RegCBstr str) = 0;
    virtual void cb_DSTCLR_DSTCLR0(RegCBstr str) = 0;
    virtual void cb_STSTCTL_ECCTST(RegCBstr str) = 0;

    void set_instance_name(std::string InstName);

    uint mBusByteWidth;
    uint mBusWidth;
    bool mIsReset;
    bool mDumpRegisterRW;
    std::map<std::string, bool> mMessageLevel;
    std::map<std::string, std::map<std::string, void (Cecccom_regif::*) (RegCBstr)> > mWrCbAPI;
    std::map<std::string, std::map<std::string, void (Cecccom_regif::*) (RegCBstr)> > mRdCbAPI;
    std::string mFileName;
    std::string mInstName;
    int mLineNum;

    bool reg_wr_process(cuint addr, const unsigned char *p_data, cuint size, bool IsDbgFunc);
    bool reg_rd_process(cuint addr, unsigned char *p_data, cuint size, bool IsDbgFunc);
    bool reg_wr_func(cuint addr, const unsigned char *p_data, cuint size, cuint reg_index, bool IsDbgFunc);
    bool reg_rd_func(cuint addr, unsigned char *p_data, cuint size, cuint reg_index, bool IsDbgFunc);
    void _re_printf(const std::string msg_level, const char *format, ...);
    void get_fileline(std::string filename, int line_number);
    void CommandInit();
    bool ChkSize(std::string expect_size, cuint detect_size, cuint addr);
    std::vector<std::string> Str2Vec(std::string str, const char sep);
    std::string Num2HexStr(cuint num, cuint num_length, bool space_strip);
    void DumpRegMsg(const std::string operation, const std::string RegName, const std::string BitName, cuint size, cuint addr, cuint wr_data, cuint pre_data, cuint data, cuint reg_length);
    std::string AccessRegCommand(const std::vector<std::string>& args, vpcl::re_register *Register, bool &BlockReg);
    void InitLocalVal();
    void UpdateLocalVal(cuint addr);
    void UpdateRegVal(cuint addr);

    #ifdef CWR_SYSTEMC
    uint cw_rd_cb(tlm::tlm_generic_payload& trans, int tag);
    uint cw_wr_cb(tlm::tlm_generic_payload& trans, int tag);
    void cw_instantiate_reg(scml2::reg<uint> * reg, std::string reg_name, int offset);
    #endif
};
#endif //__ECCCOM_REG_DEF_H__
