// -----------------------------------------------------------------------------
// $Id: dfe_regif.h,v 1.2 2018/09/06 10:17:09 huepham Exp $
//
// Copyright(c) 2015 Renesas Electronics Corporation
// Copyright(c) 2015 Renesas Design Vietnam Co., Ltd.
// RENESAS ELECTRONICS CONFIDENTIAL AND PROPRIETARY.
// This program must be used solely for the purpose for which
// it was furnished by Renesas Electronics Corporation. No part of this
// program may be reproduced or disclosed to others, in any
// form, without the prior written permission of Renesas Electronics
// Corporation.
// -----------------------------------------------------------------------------
// This file is generated by Register I/F generator
//    gen_regif.py 1.9 2013/12/04 09:51:36 sontran
//    gen_regif_class.py 1.60 2014/10/24 09:42:15 ducduong
//    regif_h.skl 1.30 2014/10/13 03:14:25 sontran
//
// Input file : /home/truongvv2/RHSIF/gen/dfe_input/dfe_regif.txt
////////////////////////////////////////////////////////////////////////////////
// ## ----------------------------------------------------------------------
// ## $Id: dfe_regif.h,v 1.2 2018/09/06 10:17:09 huepham Exp $
// ##
// ## Copyright(c) 2015 Renesas System Design Co., Ltd.
// ## Copyright(c) 2015 Renesas Design Vietnam Co., Ltd.
// ## RENESAS ELECTRONICS CONFIDENTIAL AND PROPRIETARY.
// ## This program must be used solely for the purpose for which
// ## it was furnished by Renesas Electronics Corporation. No part of this
// ## program may be reproduced or disclosed to others, in any
// ## form, without the prior written permission of Renesas Electronics
// ## Corporation.
// ## ----------------------------------------------------------------------
// 
// %MODULE DFE 
//     #              name     offset_size
//     %%REG_INSTANCE reg_def  12
// 
// %REG_CHANNEL reg_def
//     %%TITLE    name             reg_name            rsize      wsize      length  offset    factor_start factor_end  factor_index    factor_step access  init        support  callback
//     %%REG      DFEjCTLACHn      DFEjCTLACHn         8|16|32    8|16|32    32      0x000      0           11          -               0x04        R|W     0           TRUE     -
//     %%REG      DFEjCTLBCHn      DFEjCTLBCHn         8|16|32    8|16|32    32      0x040      0           11          -               0x04        R|W     0x01010000  TRUE     -
//     %%REG      DFEjDOCHn        DFEjDOCHn           8|16|32    -          32      0x080      0           11          -               0x04        R       0           TRUE     R
//     %%REG      DFEjPHCHn        DFEjPHCHn           8|16|32    -          32      0x0C0      0           11          -               0x04        R       0x80000000  TRUE     -
//     %%REG      DFEjPHINDCHn     DFEjPHINDCHn        8|16|32    -          32      0x100      0           11          -               0x04        R       0           TRUE     -
//     %%REG      DFEjSTCHn        DFEjSTCHn           8|16|32    -          32      0x140      0           11          -               0x04        R       0           TRUE     -
//     %%REG      DFEjCLRSTCHn     DFEjCLRSTCHn        8|16|32    8|16       16      0x180      0           11          -               0x04        R|W1:0  0           TRUE     -
//     %%REG      DFEjERMCHn       DFEjERMCHn          8|16|32    8           8      0x1C0      0           11          -               0x04        R|W     0           TRUE     -
//     %%REG      DFEjTRGCHn       DFEjTRGCHn          8|16|32    8|16|32    32      0x200      0           11          -               0x04        R|W     0           TRUE     -
//     %%REG      DFEjTRHCHn       DFEjTRHCHn          8|16|32    -           8      0x240      0           11          -               0x04        R       0           TRUE     -
//     %%REG      DFEjCPA          DFEjCPA             8|16|32    8|16|32    32      0x280      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjCPB          DFEjCPB             8|16|32    8|16|32    32      0x284      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjCPC          DFEjCPC             8|16|32    8|16|32    32      0x288      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjCPD          DFEjCPD             8|16|32    8|16|32    32      0x28C      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjPHIA         DFEjPHIA            8|16|32    8|16|32    32      0x290      -           -           -               -           R|W     0x80000000  TRUE     -
//     %%REG      DFEjPHIB         DFEjPHIB            8|16|32    8|16|32    32      0x294      -           -           -               -           R|W     0x80000000  TRUE     -
//     %%REG      DFEjPHIC         DFEjPHIC            8|16|32    8|16|32    32      0x298      -           -           -               -           R|W     0x80000000  TRUE     -
//     %%REG      DFEjPHID         DFEjPHID            8|16|32    8|16|32    32      0x29C      -           -           -               -           R|W     0x80000000  TRUE     -
//     %%REG      DFEjPMITRG0      DFEjPMITRG0         8|16|32    8|16|32    32      0x2A8      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjPMITRG1      DFEjPMITRG1         8|16|32    8|16|32    32      0x2AC      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjACA          DFEjACA             8|16|32    8|16       16      0x2B0      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjACB          DFEjACB             8|16|32    8|16       16      0x2B4      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjACC          DFEjACC             8|16|32    8|16       16      0x2B8      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjACD          DFEjACD             8|16|32    8|16       16      0x2BC      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjDI           DFEjDI              8|16|32    8|16|32    32      0x2C0      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjTRG          DFEjTRG             8|16|32    8           8      0x2C4      -           -           -               -           R|W1:0  0           TRUE     -
//     %%REG      DFEjEST          DFEjEST             8|16|32    -          32      0x2C8      -           -           -               -           R       0           TRUE     -
//     %%REG      DFEjST           DFEjST              8|16|32    -          32      0x2CC      -           -           -               -           R       0           TRUE     -
//     %%REG      DFEjPITRG1       DFEjPITRG1          8|16|32    8|16|32    32      0x2D4      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjMITRG1       DFEjMITRG1          8|16|32    8|16|32    32      0x2D8      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjFITRG1       DFEjFITRG1          8|16|32    8|16|32    32      0x2DC      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjPITRG        DFEjPITRG           8|16|32    8|16|32    32      0x300      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjMITRG        DFEjMITRG           8|16|32    8|16|32    32      0x304      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjFITRG        DFEjFITRG           8|16|32    8|16|32    32      0x308      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjPHUPDCn      DFEjPHUPDCn         8|16|32    8           8      0x310      0           3           -               0x04        R|W     0           TRUE     -
//     %%REG      DFEjHOLCH0       DFEjHOLCH0          8|16|32    -          32      0x320      -           -           -               -           R       0           TRUE     R
//     %%REG      DFEjHOHCH0       DFEjHOHCH0          8|16|32    -          32      0x324      -           -           -               -           R       0           TRUE     -
//     %%REG      DFEjHOLCH2       DFEjHOLCH2          8|16|32    -          32      0x328      -           -           -               -           R       0           TRUE     R
//     %%REG      DFEjHOHCH2       DFEjHOHCH2          8|16|32    -          32      0x32C      -           -           -               -           R       0           TRUE     -
//     %%REG      DFEjHOLCH4       DFEjHOLCH4          8|16|32    -          32      0x330      -           -           -               -           R       0           TRUE     R
//     %%REG      DFEjHOHCH4       DFEjHOHCH4          8|16|32    -          32      0x334      -           -           -               -           R       0           TRUE     -
//     %%REG      DFEjHOLCH6       DFEjHOLCH6          8|16|32    -          32      0x338      -           -           -               -           R       0           TRUE     R
//     %%REG      DFEjHOHCH6       DFEjHOHCH6          8|16|32    -          32      0x33C      -           -           -               -           R       0           TRUE     -
//     %%REG      DFEjHOLCH8       DFEjHOLCH8          8|16|32    -          32      0x340      -           -           -               -           R       0           TRUE     R
//     %%REG      DFEjHOHCH8       DFEjHOHCH8          8|16|32    -          32      0x344      -           -           -               -           R       0           TRUE     -
//     %%REG      DFEjHOLCH10      DFEjHOLCH10         8|16|32    -          32      0x348      -           -           -               -           R       0           TRUE     R
//     %%REG      DFEjHOHCH10      DFEjHOHCH10         8|16|32    -          32      0x34C      -           -           -               -           R       0           TRUE     -
//     %%REG      DFEjHOLMCH0      DFEjHOLMCH0         8|16|32    -          32      0x360      -           -           -               -           R       0           TRUE     -
//     %%REG      DFEjHOLMCH2      DFEjHOLMCH2         8|16|32    -          32      0x364      -           -           -               -           R       0           TRUE     -
//     %%REG      DFEjHOLMCH4      DFEjHOLMCH4         8|16|32    -          32      0x368      -           -           -               -           R       0           TRUE     -
//     %%REG      DFEjHOLMCH6      DFEjHOLMCH6         8|16|32    -          32      0x36C      -           -           -               -           R       0           TRUE     -
//     %%REG      DFEjHOLMCH8      DFEjHOLMCH8         8|16|32    -          32      0x370      -           -           -               -           R       0           TRUE     -
//     %%REG      DFEjHOLMCH10     DFEjHOLMCH10        8|16|32    -          32      0x374      -           -           -               -           R       0           TRUE     -
//     %%REG      DFEjGAINCHn      DFEjGAINCHn         8|16|32    8|16|32    32      0x380      0           11          -               0x04        R|W     0x40004000  TRUE     -
//     %%REG      DFEjTMTRGCHn     DFEjTMTRGCHn        8|16|32    8|16|32    32      0x3C0      0           11          -               0x04        R|W     0           TRUE     -
//     %%REG      DFEjCPOFSTn      DFEjCPOFSTn         8|16|32    8|16|32    32      0x440      0           2           -               0x04        R|W     0           TRUE     -
//     %%REG      DFEjPH23CCTL0    DFEjPH23CCTL0       8|16|32    8|16|32    32      0x700      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjPH2CTL0      DFEjPH2CTL0         8|16|32    8|16|32    32      0x704      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjPH3CTL0      DFEjPH3CTL0         8|16|32    8|16|32    32      0x708      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjPH20         DFEjPH20            8|16|32    -          32      0x780      -           -           -               -           R       0x80000000  TRUE     -
//     %%REG      DFEjPH30         DFEjPH30            8|16|32    -          32      0x784      -           -           -               -           R       0x80000000  TRUE     -
//     %%REG      DFEjPH2IND0      DFEjPH2IND0         8|16|32    -          32      0x7E0      -           -           -               -           R       0           TRUE     -
//     %%REG      DFEjPH3IND0      DFEjPH3IND0         8|16|32    -          32      0x7E4      -           -           -               -           R       0           TRUE     -
//     %%REG      DFEjSUBCTLCHn    DFEjSUBCTLCHn       8|16|32    8|16|32    32      0x840      0           2           -               0x04        R|W     0           TRUE     -
//     %%REG      DFEjSUBDOCHn     DFEjSUBDOCHn        8|16|32    -          32      0x860      0           2           -               0x04        R       0           TRUE     R
//     %%REG      DFEjSUBSTCHn     DFEjSUBSTCHn        8|16|32    -          32      0x880      0           2           -               0x04        R       0           TRUE     -
//     %%REG      DFEjSUBCLRSTCHn  DFEjSUBCLRSTCHn     8|16|32    8|16|32    32      0x8A0      0           2           -               0x04        R|W1:0  0           TRUE     -
//     %%REG      DFEjSUBERMCHn    DFEjSUBERMCHn       8|16|32    8|16|32    32      0x8C0      0           2           -               0x04        R|W     0           TRUE     -
//     %%REG      DFEjSUBTRGCHn    DFEjSUBTRGCHn       8|16|32    8|16|32    32      0x8E0      0           2           -               0x04        R|W     0           TRUE     -
//     %%REG      DFEjSUBTRHCHn    DFEjSUBTRHCHn       8|16|32    -          32      0x900      0           2           -               0x04        R       0           TRUE     -
//     %%REG      DFEjSUBTRG0      DFEjSUBTRG0         8|16|32    8|16|32    32      0x920      -           -           -               -           R|W     0           TRUE     -
//     %%REG      DFEjCAPCTLCHn    DFEjCAPCTLCHn       8|16|32    8|16|32    32      0x940      0           2           -               0x04        R|W     0           TRUE     -
//     %%REG      DFEjCAPDOCHn     DFEjCAPDOCHn        8|16|32    -          32      0x960      0           2           -               0x04        R       0           TRUE     R
//     %%REG      DFEjCAPSTCHn     DFEjCAPSTCHn        8|16|32    -          32      0x980      0           2           -               0x04        R       0           TRUE     -
//     %%REG      DFEjCAPCLRSTCHn  DFEjCAPCLRSTCHn     8|16|32    8|16|32    32      0x9A0      0           2           -               0x04        R|W1:0  0           TRUE     -
//     %%REG      DFEjCAPERMCHn    DFEjCAPERMCHn       8|16|32    8|16|32    32      0x9C0      0           2           -               0x04        R|W     0           TRUE     -
// 
// %REG_NAME DFEjCTLACHn      
//     %%TITLE  name           upper  lower  init  access   support  callback    
//     %%BIT    CATAG          30     26     0     R|W      TRUE     -
//     %%BIT    CAEN           25     24     0     R|W      TRUE     -
//     %%BIT    TAG            20     16     0     R|W      TRUE     -
//     %%BIT    CMD            15     12     0     R|W      TRUE     -
//     %%BIT    FMT             8      8     0     R|W      TRUE     -
//     %%BIT    IEP             7      7     0     R|W      TRUE     -
//     %%BIT    IEE             6      6     0     R|W      TRUE     -
//     %%BIT    IEC             5      5     0     R|W      TRUE     -
//     %%BIT    IEO             4      4     0     R|W      TRUE     -
//     %%BIT    CNSL            3      3     0     R|W      TRUE     -
//     %%BIT    CNSLE           2      2     0     R|W      TRUE     -
//     %%BIT    AIME            1      1     0     R|W      TRUE     -
//     %%BIT    EN              0      0     0     R|W      TRUE     W
// 
// %REG_NAME DFEjCTLBCHn      
//     %%TITLE  name           upper  lower  init  access   support  callback    
//     %%BIT    OFSL           26     25     0     R|W      TRUE     -
//     %%BIT    DISB           24     24     1     R|W      TRUE     -
//     %%BIT    PHPS           23     23     0     R|W      TRUE     -
//     %%BIT    CPCS           22     22     0     R|W      TRUE     -
//     %%BIT    PHSLB2         19     17     0     R|W      TRUE     -
//     %%BIT    DISA           16     16     1     R|W      TRUE     -
//     %%BIT    PRCSC          15     15     0     R|W      TRUE     -
//     %%BIT    SELB2          14     12     0     R|W      TRUE     -
//     %%BIT    SELB1          11     10     0     R|W      TRUE     -
//     %%BIT    PRCSB           9      8     0     R|W      TRUE     -
//     %%BIT    HOFS            7      7     0     R|W      TRUE     -
//     %%BIT    PICS            6      6     0     R|W      TRUE     -
//     %%BIT    SELA            5      4     0     R|W      TRUE     -
//     %%BIT    PFMT            3      3     0     R|W      TRUE     -
//     %%BIT    ABS             2      2     0     R|W      TRUE     -
//     %%BIT    PRCSA           1      0     0     R|W      TRUE     W
// 
// %REG_NAME DFEjPHINDCHn     
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    PHIOW          15     15     0     R        TRUE     -
//     %%BIT    PHIOF          14     14     0     R        TRUE     R
//     %%BIT    PHIND          13      0     0     R        TRUE     -
// 
// %REG_NAME DFEjSTCHn       
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    PH23ST         18     16     0     R        TRUE     -
//     %%BIT    VALID          12     12     0     R        TRUE     -
//     %%BIT    PHE            10     10     0     R        TRUE     -
//     %%BIT    CND             9      9     0     R        TRUE     -
//     %%BIT    DOEN            8      8     0     R        TRUE     -
//     %%BIT    CER             5      5     0     R        TRUE     -
//     %%BIT    AER             4      4     0     R        TRUE     -
//     %%BIT    MER             3      3     0     R        TRUE     -
//     %%BIT    GER             2      2     0     R        TRUE     -
//     %%BIT    DOOW            1      1     0     R        TRUE     -
//     %%BIT    DIOW            0      0     0     R        TRUE     -
// 
// %REG_NAME DFEjCLRSTCHn     
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    CLRPHIOW       15     15     0     R|W1:0  TRUE     -
//     %%BIT    CLRPHE         10     10     0     R|W1:0  TRUE     -
//     %%BIT    CLRCND          9      9     0     R|W1:0  TRUE     -
//     %%BIT    CLRDOEN         8      8     0     R|W1:0  TRUE     -
//     %%BIT    CLRCER          5      5     0     R|W1:0  TRUE     -
//     %%BIT    CLRAER          4      4     0     R|W1:0  TRUE     -
//     %%BIT    CLRMER          3      3     0     R|W1:0  TRUE     -
//     %%BIT    CLRGER          2      2     0     R|W1:0  TRUE     -
//     %%BIT    CLRDOOW         1      1     0     R|W1:0  TRUE     -
//     %%BIT    CLRDIOW         0      0     0     R|W1:0  TRUE     W
// 
// %REG_NAME DFEjERMCHn       
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    MSKCER          5      5     0     R|W      TRUE     -
//     %%BIT    MSKAER          4      4     0     R|W      TRUE     -
//     %%BIT    MSKMER          3      3     0     R|W      TRUE     -
//     %%BIT    MSKGER          2      2     0     R|W      TRUE     -
//     %%BIT    MSKDOOW         1      1     0     R|W      TRUE     -
//     %%BIT    MSKDIOW         0      0     0     R|W      TRUE     -
// 
// %REG_NAME DFEjTRGCHn       
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    PMFE           23     22     0     R|W     TRUE     -
//     %%BIT    PME            21     20     0     R|W     TRUE     -
//     %%BIT    PFE            19     18     0     R|W     TRUE     -
//     %%BIT    AFE            15     14     0     R|W     TRUE     -
//     %%BIT    PE             11     10     0     R|W     TRUE     -
//     %%BIT    PT              9      8     0     R|W     TRUE     -
//     %%BIT    AE              7      6     0     R|W     TRUE     -
//     %%BIT    AT              5      4     0     R|W     TRUE     -
//     %%BIT    FE              3      2     0     R|W     TRUE     -
//     %%BIT    FT              1      0     0     R|W     TRUE     -
// 
// %REG_NAME DFEjTRHCHn       
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    PMITS           6      6     0     R        TRUE     -
//     %%BIT    PMETS           5      5     0     R        TRUE     -
//     %%BIT    PITS            4      4     0     R        TRUE     -
//     %%BIT    PETS            3      3     0     R        TRUE     -
//     %%BIT    MITS            2      2     0     R        TRUE     -
//     %%BIT    METS            1      1     0     R        TRUE     -
//     %%BIT    FITS            0      0     0     R        TRUE     -
// 
// %REG_NAME DFEjPMITRG0     
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    PMITMTRG3      28     24     0     R|W     TRUE     -
//     %%BIT    PMITMTRG2      20     16     0     R|W     TRUE     -
//     %%BIT    PMITMTRG1      12      8     0     R|W     TRUE     -
//     %%BIT    PMITMTRG0       4      0     0     R|W     TRUE     -
// 
// %REG_NAME DFEjPMITRG1     
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    PMITMTRG5      12      8     0     R|W     TRUE     -
//     %%BIT    PMITMTRG4       4      0     0     R|W     TRUE     -
// 
// %REG_NAME DFEjACA     
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    AC              8      0     0     R|W      TRUE     -
// 
// %REG_NAME DFEjACB     
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    AC              8      0     0     R|W      TRUE     -
// 
// %REG_NAME DFEjACC     
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    AC              8      0     0     R|W      TRUE     -
// 
// %REG_NAME DFEjACD     
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    AC              8      0     0     R|W      TRUE     -
// 
// %REG_NAME DFEjDI      
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    TAG            20     16     0     R|W      TRUE     -
//     %%BIT    DI             15      0     0     R|W      TRUE     W
// 
// %REG_NAME DFEjTRG     
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    TRGA            0      0     0     R|W1:0  TRUE      W
// 
// %REG_NAME DFEjEST     
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    CP2S           18     18     0     R        TRUE     -
//     %%BIT    CP1S           17     17     0     R        TRUE     -
//     %%BIT    CP0S           16     16     0     R        TRUE     -
//     %%BIT    SB2S            2      2     0     R        TRUE     -
//     %%BIT    SB1S            1      1     0     R        TRUE     -
//     %%BIT    SB0S            0      0     0     R        TRUE     -
// 
// %REG_NAME DFEjST     
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    CH11S          23     22     0     R        TRUE     -
//     %%BIT    CH10S          21     20     0     R        TRUE     -
//     %%BIT    CH9S           19     18     0     R        TRUE     -
//     %%BIT    CH8S           17     16     0     R        TRUE     -
//     %%BIT    CH7S           15     14     0     R        TRUE     -
//     %%BIT    CH6S           13     12     0     R        TRUE     -
//     %%BIT    CH5S           11     10     0     R        TRUE     -
//     %%BIT    CH4S            9      8     0     R        TRUE     -
//     %%BIT    CH3S            7      6     0     R        TRUE     -
//     %%BIT    CH2S            5      4     0     R        TRUE     -
//     %%BIT    CH1S            3      2     0     R        TRUE     -
//     %%BIT    CH0S            1      0     0     R        TRUE     -
// 
// %REG_NAME DFEjPITRG1  
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    PITMTRG5       12      8     0     R|W     TRUE     -
//     %%BIT    PITMTRG4        4      0     0     R|W     TRUE     -
// 
// %REG_NAME DFEjMITRG1  
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    MITMTRG5       12      8     0     R|W     TRUE     -
//     %%BIT    MITMTRG4        4      0     0     R|W     TRUE     -
// 
// %REG_NAME DFEjFITRG1  
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    FITMTRG5       12      8     0     R|W     TRUE     -
//     %%BIT    FITMTRG4        4      0     0     R|W     TRUE     -
// 
// %REG_NAME DFEjPITRG  
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    PITMTRG3       28     24     0     R|W     TRUE     -
//     %%BIT    PITMTRG2       20     16     0     R|W     TRUE     -
//     %%BIT    PITMTRG1       12      8     0     R|W     TRUE     -
//     %%BIT    PITMTRG0        4      0     0     R|W     TRUE     -
// 
// %REG_NAME DFEjMITRG  
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    MITMTRG3       28     24     0     R|W     TRUE     -
//     %%BIT    MITMTRG2       20     16     0     R|W     TRUE     -
//     %%BIT    MITMTRG1       12      8     0     R|W     TRUE     -
//     %%BIT    MITMTRG0        4      0     0     R|W     TRUE     -
// 
// %REG_NAME DFEjFITRG  
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    FITMTRG3       28     24     0     R|W     TRUE     -
//     %%BIT    FITMTRG2       20     16     0     R|W     TRUE     -
//     %%BIT    FITMTRG1       12      8     0     R|W     TRUE     -
//     %%BIT    FITMTRG0        4      0     0     R|W     TRUE     -
// 
// %REG_NAME DFEjPHUPDCn 
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    PHUPDCH         7      4     0     R|W     TRUE     -
//     %%BIT    PH23SL          2      2     0     R|W     TRUE     -
//     %%BIT    PH23E           1      1     0     R|W     TRUE     -
//     %%BIT    OEPHUPD         0      0     0     R|W     TRUE     -
// 
// %REG_NAME DFEjHOHCH0  
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    GURD            5      0     0     R        TRUE     R
// 
// %REG_NAME DFEjHOHCH2  
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    GURD            5      0     0     R        TRUE     R
// 
// %REG_NAME DFEjHOHCH4  
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    GURD            5      0     0     R        TRUE     R
// 
// %REG_NAME DFEjHOHCH6  
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    GURD            5      0     0     R        TRUE     R
// 
// %REG_NAME DFEjHOHCH8  
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    GURD            5      0     0     R        TRUE     R
// 
// %REG_NAME DFEjHOHCH10 
//     %%TITLE  name           upper  lower  init  access  support  callback    
//     %%BIT    GURD            5      0     0     R        TRUE     R
// 
// %REG_NAME DFEjGAINCHn 
//     %%TITLE  name           upper  lower  init    access  support  callback    
//     %%BIT    GAIN3          31     16     0x4000  R|W      TRUE     -
//     %%BIT    GAIN2          15      0     0x4000  R|W      TRUE     -
// 
// %REG_NAME DFEjTMTRGCHn
//     %%TITLE  name           upper  lower  init    access  support  callback    
//     %%BIT    PMT            14     12     0       R|W     TRUE     -
//     %%BIT    PT             10      8     0       R|W     TRUE     -
//     %%BIT    AT              6      4     0       R|W     TRUE     -
//     %%BIT    FT              2      0     0       R|W     TRUE     -
// 
// %REG_NAME DFEjPH23CCTL0
//     %%TITLE  name           upper  lower  init    access  support  callback    
//     %%BIT    CHS             7      4     0       R|W     TRUE     -
//     %%BIT    PFMT            3      3     0       R|W     TRUE     -
//     %%BIT    PEN             0      0     0       R|W     TRUE     W
// 
// %REG_NAME DFEjPH2CTL0  
//     %%TITLE  name           upper  lower  init    access  support  callback    
//     %%BIT    OFSL            9      8     0       R|W     TRUE     -
//     %%BIT    PH2SLB2         6      4     0       R|W     TRUE     -
//     %%BIT    PHPS            3      3     0       R|W     TRUE     -
//     %%BIT    CN2SLB2         2      0     0       R|W     TRUE     W
// 
// %REG_NAME DFEjPH3CTL0  
//     %%TITLE  name           upper  lower  init    access   support  callback    
//     %%BIT    OFSL            9      8     0       R|W      TRUE     -
//     %%BIT    PH3SLB2         6      4     0       R|W      TRUE     -
//     %%BIT    PHPS            3      3     0       R|W      TRUE     -
//     %%BIT    CN3SLB2         2      0     0       R|W      TRUE     W
// 
// %REG_NAME DFEjPH2IND0  
//     %%TITLE  name           upper  lower  init    access  support  callback    
//     %%BIT    PH2IOW         15     15     0       R        TRUE     -
//     %%BIT    PH2IOF         14     14     0       R        TRUE     -
//     %%BIT    PH2IND         13      0     0       R        TRUE     -
// 
// %REG_NAME DFEjPH3IND0  
//     %%TITLE  name           upper  lower  init    access  support  callback    
//     %%BIT    PH3IOW         15     15     0       R        TRUE     -
//     %%BIT    PH3IOF         14     14     0       R        TRUE     -
//     %%BIT    PH3IND         13      0     0       R        TRUE     -
// 
// %REG_NAME DFEjSUBCTLCHn 
//     %%TITLE  name           upper  lower  init    access  support  callback    
//     %%BIT    CATAG          30     26     0       R|W     TRUE     -
//     %%BIT    CAEN           25     24     0       R|W     TRUE     -
//     %%BIT    MINCH          11      8     0       R|W     TRUE     -
//     %%BIT    SUBCH           7      4     0       R|W     TRUE     -
//     %%BIT    SFMT            3      3     0       R|W     TRUE     -
//     %%BIT    SIEE            2      2     0       R|W     TRUE     -
//     %%BIT    SIEO            1      1     0       R|W     TRUE     -
//     %%BIT    SEN             0      0     0       R|W     TRUE     W
// 
// %REG_NAME DFEjSUBSTCHn  
//     %%TITLE  name           upper  lower  init    access  support  callback    
//     %%BIT    SDOEN           8      8     0       R      TRUE     -
//     %%BIT    MINF            7      7     0       R      TRUE     -
//     %%BIT    SUBF            6      6     0       R      TRUE     -
//     %%BIT    SCER            5      5     0       R      TRUE     -
//     %%BIT    SGER            2      2     0       R      TRUE     -
//     %%BIT    SDOOW           1      1     0       R      TRUE     -
// 
// %REG_NAME DFEjSUBCLRSTCHn
//     %%TITLE  name           upper  lower  init    access  support  callback    
//     %%BIT    CLRSDOEN        8      8     0       R|W1:0  TRUE     -
//     %%BIT    CLRSCER         5      5     0       R|W1:0  TRUE     -
//     %%BIT    CLRSGER         2      2     0       R|W1:0  TRUE     -
//     %%BIT    CLRSDOOW        1      1     0       R|W1:0  TRUE     W
// 
// %REG_NAME DFEjSUBERMCHn  
//     %%TITLE  name           upper  lower  init    access  support  callback    
//     %%BIT    MSKSCER         5      5     0       R|W    TRUE     -
//     %%BIT    MSKSGER         2      2     0       R|W    TRUE     -
//     %%BIT    MSKSDOOW        1      1     0       R|W    TRUE     -
// 
// %REG_NAME DFEjSUBTRGCHn  
//     %%TITLE  name           upper  lower  init    access support  callback    
//     %%BIT    SBFE           15     14     0       R|W    TRUE     -
//     %%BIT    SBE             7      6     0       R|W    TRUE     -
//     %%BIT    SBT             1      0     0       R|W    TRUE     W
// 
// %REG_NAME DFEjSUBTRHCHn  
//     %%TITLE  name           upper  lower  init    access support  callback    
//     %%BIT    SITS            1      1     0       R      TRUE     -
//     %%BIT    SETS            0      0     0       R      TRUE     -
// 
// %REG_NAME DFEjSUBTRG0   
//     %%TITLE  name           upper  lower  init    access support  callback    
//     %%BIT    SUBTMTRG2      20     16     0       R|W    TRUE     -
//     %%BIT    SUBTMTRG1      12      8     0       R|W    TRUE     -
//     %%BIT    SUBTMTRG0       4      0     0       R|W    TRUE     -
// 
// %REG_NAME DFEjCAPCTLCHn  
//     %%TITLE  name           upper  lower  init    access support  callback    
//     %%BIT    CAPCH           7      4     0       R|W    TRUE     -
//     %%BIT    CIEE            2      2     0       R|W    TRUE     -
//     %%BIT    CEN             0      0     0       R|W    TRUE     W
// 
// %REG_NAME DFEjCAPSTCHn  
//     %%TITLE  name           upper  lower  init    access  support  callback    
//     %%BIT    CDOEN           8      8     0       R      TRUE     -
//     %%BIT    CDOOW           1      1     0       R      TRUE     -
// 
// %REG_NAME DFEjCAPCLRSTCHn  
//     %%TITLE  name           upper  lower  init    access  support  callback    
//     %%BIT    CLRCDOEN        8      8     0       R|W1:0  TRUE     -
//     %%BIT    CLRCDOOW        1      1     0       R|W1:0  TRUE     W
// 
// %REG_NAME DFEjCAPERMCHn  
//     %%TITLE  name           upper  lower  init    access  support  callback    
//     %%BIT    MSKCDOOW        1      1     0       R|W     TRUE     -
////////////////////////////////////////////////////////////////////////////////
/// @file dfe_regif.h
/// @brief Register IF class of model DFE
/// $Id: dfe_regif.h,v 1.2 2018/09/06 10:17:09 huepham Exp $
/// $Date: 2018/09/06 10:17:09 $
/// $Revison$
/// $Author: huepham $
////////////////////////////////////////////////////////////////////////////////
#ifndef __DFE_REGIF_H__
#define __DFE_REGIF_H__
#include <string>
#include <map>
#include <list>
#include <cstdarg>
#include <cerrno>
#include <iomanip>
#include <sstream>
#ifdef REGIF_NOT_USE_SYSTEMC
#include <cassert>
#else
#include "systemc.h"
#endif
#include "re_register.h"
#ifdef CWR_SYSTEMC
#include "scml.h"
#endif

/// Register IF class of DFE model
class Cdfe_regif
: public vpcl::reg_super
{
protected:
    typedef const unsigned int cuint;
    typedef unsigned int uint;

    enum eRegGroup {
        emNum_of_gr
    }; ///< Enumeration for register group index
    enum eRegIndex {
        emNUM_DFEjCTLACHn     = 12,
        emNUM_DFEjCTLBCHn     = 12,
        emNUM_DFEjDOCHn       = 12,
        emNUM_DFEjPHCHn       = 12,
        emNUM_DFEjPHINDCHn    = 12,
        emNUM_DFEjSTCHn       = 12,
        emNUM_DFEjCLRSTCHn    = 12,
        emNUM_DFEjERMCHn      = 12,
        emNUM_DFEjTRGCHn      = 12,
        emNUM_DFEjTRHCHn      = 12,
        emNUM_DFEjPHUPDCn     = 4,
        emNUM_DFEjGAINCHn     = 12,
        emNUM_DFEjTMTRGCHn    = 12,
        emNUM_DFEjCPOFSTn     = 3,
        emNUM_DFEjSUBCTLCHn   = 3,
        emNUM_DFEjSUBDOCHn    = 3,
        emNUM_DFEjSUBSTCHn    = 3,
        emNUM_DFEjSUBCLRSTCHn = 3,
        emNUM_DFEjSUBERMCHn   = 3,
        emNUM_DFEjSUBTRGCHn   = 3,
        emNUM_DFEjSUBTRHCHn   = 3,
        emNUM_DFEjCAPCTLCHn   = 3,
        emNUM_DFEjCAPDOCHn    = 3,
        emNUM_DFEjCAPSTCHn    = 3,
        emNUM_DFEjCAPCLRSTCHn = 3,
        emNUM_DFEjCAPERMCHn   = 3
    }; ///< Enumeration for register factor index

    struct RegCBstr {
        uint channel;
        bool is_wr;
        uint size;
        uint pre_data;
        uint data;
        RegCBstr (uint channel, bool is_wr, uint size, uint pre_data, uint data)
        {
            this-> channel = channel;
            this-> is_wr   = is_wr;
            this-> size    = size;
            this-> pre_data= pre_data;
            this-> data    = data;
        }
    };
    struct SRegList {
        vpcl::re_register *my_p;
        SRegList *prev;
        uint channel;
        uint length;
        std::string wacc_size;
        std::string racc_size;
        bool block;
        SRegList( vpcl::re_register *_my_p, SRegList *_prev, uint _channel, uint _length, std::string _wacc_size, std::string _racc_size, bool _block = false) {
            this->my_p = NULL;
            if (_my_p != NULL) {
                this->my_p = _my_p;
            }
            this->prev = NULL;
            if (_prev != NULL) {
                this->prev = _prev;
            }
            this->channel = _channel;
            this->length  = _length;
            this->wacc_size = _wacc_size;
            this->racc_size = _racc_size;
            this->block = _block;
        }
    } *mRegList, *mCurReg, **mRegArray;

    uint *mRegMap;
    uint mTotalRegNum;
    uint mNumChan;

public:
    Cdfe_regif(std::string name, uint buswidth, uint num_chan);
    ~Cdfe_regif();

protected:
    vpcl::re_register *DFEjCTLACHn    [12];
    vpcl::re_register *DFEjCTLBCHn    [12];
    vpcl::re_register *DFEjDOCHn      [12];
    vpcl::re_register *DFEjPHCHn      [12];
    vpcl::re_register *DFEjPHINDCHn   [12];
    vpcl::re_register *DFEjSTCHn      [12];
    vpcl::re_register *DFEjCLRSTCHn   [12];
    vpcl::re_register *DFEjERMCHn     [12];
    vpcl::re_register *DFEjTRGCHn     [12];
    vpcl::re_register *DFEjTRHCHn     [12];
    vpcl::re_register *DFEjCPA        ;
    vpcl::re_register *DFEjCPB        ;
    vpcl::re_register *DFEjCPC        ;
    vpcl::re_register *DFEjCPD        ;
    vpcl::re_register *DFEjPHIA       ;
    vpcl::re_register *DFEjPHIB       ;
    vpcl::re_register *DFEjPHIC       ;
    vpcl::re_register *DFEjPHID       ;
    vpcl::re_register *DFEjPMITRG0    ;
    vpcl::re_register *DFEjPMITRG1    ;
    vpcl::re_register *DFEjACA        ;
    vpcl::re_register *DFEjACB        ;
    vpcl::re_register *DFEjACC        ;
    vpcl::re_register *DFEjACD        ;
    vpcl::re_register *DFEjDI         ;
    vpcl::re_register *DFEjTRG        ;
    vpcl::re_register *DFEjEST        ;
    vpcl::re_register *DFEjST         ;
    vpcl::re_register *DFEjPITRG1     ;
    vpcl::re_register *DFEjMITRG1     ;
    vpcl::re_register *DFEjFITRG1     ;
    vpcl::re_register *DFEjPITRG      ;
    vpcl::re_register *DFEjMITRG      ;
    vpcl::re_register *DFEjFITRG      ;
    vpcl::re_register *DFEjPHUPDCn    [4];
    vpcl::re_register *DFEjHOLCH0     ;
    vpcl::re_register *DFEjHOHCH0     ;
    vpcl::re_register *DFEjHOLCH2     ;
    vpcl::re_register *DFEjHOHCH2     ;
    vpcl::re_register *DFEjHOLCH4     ;
    vpcl::re_register *DFEjHOHCH4     ;
    vpcl::re_register *DFEjHOLCH6     ;
    vpcl::re_register *DFEjHOHCH6     ;
    vpcl::re_register *DFEjHOLCH8     ;
    vpcl::re_register *DFEjHOHCH8     ;
    vpcl::re_register *DFEjHOLCH10    ;
    vpcl::re_register *DFEjHOHCH10    ;
    vpcl::re_register *DFEjHOLMCH0    ;
    vpcl::re_register *DFEjHOLMCH2    ;
    vpcl::re_register *DFEjHOLMCH4    ;
    vpcl::re_register *DFEjHOLMCH6    ;
    vpcl::re_register *DFEjHOLMCH8    ;
    vpcl::re_register *DFEjHOLMCH10   ;
    vpcl::re_register *DFEjGAINCHn    [12];
    vpcl::re_register *DFEjTMTRGCHn   [12];
    vpcl::re_register *DFEjCPOFSTn    [3];
    vpcl::re_register *DFEjPH23CCTL0  ;
    vpcl::re_register *DFEjPH2CTL0    ;
    vpcl::re_register *DFEjPH3CTL0    ;
    vpcl::re_register *DFEjPH20       ;
    vpcl::re_register *DFEjPH30       ;
    vpcl::re_register *DFEjPH2IND0    ;
    vpcl::re_register *DFEjPH3IND0    ;
    vpcl::re_register *DFEjSUBCTLCHn  [3];
    vpcl::re_register *DFEjSUBDOCHn   [3];
    vpcl::re_register *DFEjSUBSTCHn   [3];
    vpcl::re_register *DFEjSUBCLRSTCHn[3];
    vpcl::re_register *DFEjSUBERMCHn  [3];
    vpcl::re_register *DFEjSUBTRGCHn  [3];
    vpcl::re_register *DFEjSUBTRHCHn  [3];
    vpcl::re_register *DFEjSUBTRG0    ;
    vpcl::re_register *DFEjCAPCTLCHn  [3];
    vpcl::re_register *DFEjCAPDOCHn   [3];
    vpcl::re_register *DFEjCAPSTCHn   [3];
    vpcl::re_register *DFEjCAPCLRSTCHn[3];
    vpcl::re_register *DFEjCAPERMCHn  [3];

    #ifdef CWR_SYSTEMC
    scml2::memory<uint> cwmem;
    scml2::reg<uint>      *CW_DFEjCLRSTCHn_  [12];
    scml2::reg<uint>      *CW_DFEjERMCHn_    [12];
    scml2::reg<uint>      *CW_DFEjTRHCHn_    [12];
    scml2::reg<uint>      *CW_DFEjACA_       ;
    scml2::reg<uint>      *CW_DFEjACB_       ;
    scml2::reg<uint>      *CW_DFEjACC_       ;
    scml2::reg<uint>      *CW_DFEjACD_       ;
    scml2::reg<uint>      *CW_DFEjTRG_       ;
    scml2::reg<uint>      *CW_DFEjPHUPDCn_   [4];
    scml2::reg<uint>      *CW_DFEjCTLACHn    [12];
    scml2::reg<uint>      *CW_DFEjCTLBCHn    [12];
    scml2::reg<uint>      *CW_DFEjDOCHn      [12];
    scml2::reg<uint>      *CW_DFEjPHCHn      [12];
    scml2::reg<uint>      *CW_DFEjPHINDCHn   [12];
    scml2::reg<uint>      *CW_DFEjSTCHn      [12];
    scml2::bitfield<uint> *CW_DFEjCLRSTCHn   [12];
    scml2::bitfield<uint> *CW_DFEjERMCHn     [12];
    scml2::reg<uint>      *CW_DFEjTRGCHn     [12];
    scml2::bitfield<uint> *CW_DFEjTRHCHn     [12];
    scml2::reg<uint>      *CW_DFEjCPA        ;
    scml2::reg<uint>      *CW_DFEjCPB        ;
    scml2::reg<uint>      *CW_DFEjCPC        ;
    scml2::reg<uint>      *CW_DFEjCPD        ;
    scml2::reg<uint>      *CW_DFEjPHIA       ;
    scml2::reg<uint>      *CW_DFEjPHIB       ;
    scml2::reg<uint>      *CW_DFEjPHIC       ;
    scml2::reg<uint>      *CW_DFEjPHID       ;
    scml2::reg<uint>      *CW_DFEjPMITRG0    ;
    scml2::reg<uint>      *CW_DFEjPMITRG1    ;
    scml2::bitfield<uint> *CW_DFEjACA        ;
    scml2::bitfield<uint> *CW_DFEjACB        ;
    scml2::bitfield<uint> *CW_DFEjACC        ;
    scml2::bitfield<uint> *CW_DFEjACD        ;
    scml2::reg<uint>      *CW_DFEjDI         ;
    scml2::bitfield<uint> *CW_DFEjTRG        ;
    scml2::reg<uint>      *CW_DFEjEST        ;
    scml2::reg<uint>      *CW_DFEjST         ;
    scml2::reg<uint>      *CW_DFEjPITRG1     ;
    scml2::reg<uint>      *CW_DFEjMITRG1     ;
    scml2::reg<uint>      *CW_DFEjFITRG1     ;
    scml2::reg<uint>      *CW_DFEjPITRG      ;
    scml2::reg<uint>      *CW_DFEjMITRG      ;
    scml2::reg<uint>      *CW_DFEjFITRG      ;
    scml2::bitfield<uint> *CW_DFEjPHUPDCn    [4];
    scml2::reg<uint>      *CW_DFEjHOLCH0     ;
    scml2::reg<uint>      *CW_DFEjHOHCH0     ;
    scml2::reg<uint>      *CW_DFEjHOLCH2     ;
    scml2::reg<uint>      *CW_DFEjHOHCH2     ;
    scml2::reg<uint>      *CW_DFEjHOLCH4     ;
    scml2::reg<uint>      *CW_DFEjHOHCH4     ;
    scml2::reg<uint>      *CW_DFEjHOLCH6     ;
    scml2::reg<uint>      *CW_DFEjHOHCH6     ;
    scml2::reg<uint>      *CW_DFEjHOLCH8     ;
    scml2::reg<uint>      *CW_DFEjHOHCH8     ;
    scml2::reg<uint>      *CW_DFEjHOLCH10    ;
    scml2::reg<uint>      *CW_DFEjHOHCH10    ;
    scml2::reg<uint>      *CW_DFEjHOLMCH0    ;
    scml2::reg<uint>      *CW_DFEjHOLMCH2    ;
    scml2::reg<uint>      *CW_DFEjHOLMCH4    ;
    scml2::reg<uint>      *CW_DFEjHOLMCH6    ;
    scml2::reg<uint>      *CW_DFEjHOLMCH8    ;
    scml2::reg<uint>      *CW_DFEjHOLMCH10   ;
    scml2::reg<uint>      *CW_DFEjGAINCHn    [12];
    scml2::reg<uint>      *CW_DFEjTMTRGCHn   [12];
    scml2::reg<uint>      *CW_DFEjCPOFSTn    [3];
    scml2::reg<uint>      *CW_DFEjPH23CCTL0  ;
    scml2::reg<uint>      *CW_DFEjPH2CTL0    ;
    scml2::reg<uint>      *CW_DFEjPH3CTL0    ;
    scml2::reg<uint>      *CW_DFEjPH20       ;
    scml2::reg<uint>      *CW_DFEjPH30       ;
    scml2::reg<uint>      *CW_DFEjPH2IND0    ;
    scml2::reg<uint>      *CW_DFEjPH3IND0    ;
    scml2::reg<uint>      *CW_DFEjSUBCTLCHn  [3];
    scml2::reg<uint>      *CW_DFEjSUBDOCHn   [3];
    scml2::reg<uint>      *CW_DFEjSUBSTCHn   [3];
    scml2::reg<uint>      *CW_DFEjSUBCLRSTCHn[3];
    scml2::reg<uint>      *CW_DFEjSUBERMCHn  [3];
    scml2::reg<uint>      *CW_DFEjSUBTRGCHn  [3];
    scml2::reg<uint>      *CW_DFEjSUBTRHCHn  [3];
    scml2::reg<uint>      *CW_DFEjSUBTRG0    ;
    scml2::reg<uint>      *CW_DFEjCAPCTLCHn  [3];
    scml2::reg<uint>      *CW_DFEjCAPDOCHn   [3];
    scml2::reg<uint>      *CW_DFEjCAPSTCHn   [3];
    scml2::reg<uint>      *CW_DFEjCAPCLRSTCHn[3];
    scml2::reg<uint>      *CW_DFEjCAPERMCHn  [3];
    #endif

    uint DFEjCTLACHn_CATAG [12];
    uint DFEjCTLACHn_CAEN  [12];
    uint DFEjCTLACHn_TAG   [12];
    uint DFEjCTLACHn_CMD   [12];
    uint DFEjCTLACHn_FMT   [12];
    uint DFEjCTLACHn_IEP   [12];
    uint DFEjCTLACHn_IEE   [12];
    uint DFEjCTLACHn_IEC   [12];
    uint DFEjCTLACHn_IEO   [12];
    uint DFEjCTLACHn_CNSL  [12];
    uint DFEjCTLACHn_CNSLE [12];
    uint DFEjCTLACHn_AIME  [12];
    uint DFEjCTLACHn_EN    [12];
    uint DFEjCTLBCHn_OFSL  [12];
    uint DFEjCTLBCHn_DISB  [12];
    uint DFEjCTLBCHn_PHPS  [12];
    uint DFEjCTLBCHn_CPCS  [12];
    uint DFEjCTLBCHn_PHSLB2[12];
    uint DFEjCTLBCHn_DISA  [12];
    uint DFEjCTLBCHn_PRCSC [12];
    uint DFEjCTLBCHn_SELB2 [12];
    uint DFEjCTLBCHn_SELB1 [12];
    uint DFEjCTLBCHn_PRCSB [12];
    uint DFEjCTLBCHn_HOFS  [12];
    uint DFEjCTLBCHn_PICS  [12];
    uint DFEjCTLBCHn_SELA  [12];
    uint DFEjCTLBCHn_PFMT  [12];
    uint DFEjCTLBCHn_ABS   [12];
    uint DFEjCTLBCHn_PRCSA [12];
    uint DFEjDOCHn_DFEjDOCHn[12];
    uint DFEjPHCHn_DFEjPHCHn[12];
    uint DFEjPHINDCHn_PHIOW[12];
    uint DFEjPHINDCHn_PHIOF[12];
    uint DFEjPHINDCHn_PHIND[12];
    uint DFEjSTCHn_PH23ST  [12];
    uint DFEjSTCHn_VALID   [12];
    uint DFEjSTCHn_PHE     [12];
    uint DFEjSTCHn_CND     [12];
    uint DFEjSTCHn_DOEN    [12];
    uint DFEjSTCHn_CER     [12];
    uint DFEjSTCHn_AER     [12];
    uint DFEjSTCHn_MER     [12];
    uint DFEjSTCHn_GER     [12];
    uint DFEjSTCHn_DOOW    [12];
    uint DFEjSTCHn_DIOW    [12];
    uint DFEjCLRSTCHn_CLRPHIOW[12];
    uint DFEjCLRSTCHn_CLRPHE[12];
    uint DFEjCLRSTCHn_CLRCND[12];
    uint DFEjCLRSTCHn_CLRDOEN[12];
    uint DFEjCLRSTCHn_CLRCER[12];
    uint DFEjCLRSTCHn_CLRAER[12];
    uint DFEjCLRSTCHn_CLRMER[12];
    uint DFEjCLRSTCHn_CLRGER[12];
    uint DFEjCLRSTCHn_CLRDOOW[12];
    uint DFEjCLRSTCHn_CLRDIOW[12];
    uint DFEjERMCHn_MSKCER [12];
    uint DFEjERMCHn_MSKAER [12];
    uint DFEjERMCHn_MSKMER [12];
    uint DFEjERMCHn_MSKGER [12];
    uint DFEjERMCHn_MSKDOOW[12];
    uint DFEjERMCHn_MSKDIOW[12];
    uint DFEjTRGCHn_PMFE   [12];
    uint DFEjTRGCHn_PME    [12];
    uint DFEjTRGCHn_PFE    [12];
    uint DFEjTRGCHn_AFE    [12];
    uint DFEjTRGCHn_PE     [12];
    uint DFEjTRGCHn_PT     [12];
    uint DFEjTRGCHn_AE     [12];
    uint DFEjTRGCHn_AT     [12];
    uint DFEjTRGCHn_FE     [12];
    uint DFEjTRGCHn_FT     [12];
    uint DFEjTRHCHn_PMITS  [12];
    uint DFEjTRHCHn_PMETS  [12];
    uint DFEjTRHCHn_PITS   [12];
    uint DFEjTRHCHn_PETS   [12];
    uint DFEjTRHCHn_MITS   [12];
    uint DFEjTRHCHn_METS   [12];
    uint DFEjTRHCHn_FITS   [12];
    uint DFEjCPA_DFEjCPA   ;
    uint DFEjCPB_DFEjCPB   ;
    uint DFEjCPC_DFEjCPC   ;
    uint DFEjCPD_DFEjCPD   ;
    uint DFEjPHIA_DFEjPHIA ;
    uint DFEjPHIB_DFEjPHIB ;
    uint DFEjPHIC_DFEjPHIC ;
    uint DFEjPHID_DFEjPHID ;
    uint DFEjPMITRG0_PMITMTRG3;
    uint DFEjPMITRG0_PMITMTRG2;
    uint DFEjPMITRG0_PMITMTRG1;
    uint DFEjPMITRG0_PMITMTRG0;
    uint DFEjPMITRG1_PMITMTRG5;
    uint DFEjPMITRG1_PMITMTRG4;
    uint DFEjACA_AC        ;
    uint DFEjACB_AC        ;
    uint DFEjACC_AC        ;
    uint DFEjACD_AC        ;
    uint DFEjDI_TAG        ;
    uint DFEjDI_DI         ;
    uint DFEjTRG_TRGA      ;
    uint DFEjEST_CP2S      ;
    uint DFEjEST_CP1S      ;
    uint DFEjEST_CP0S      ;
    uint DFEjEST_SB2S      ;
    uint DFEjEST_SB1S      ;
    uint DFEjEST_SB0S      ;
    uint DFEjST_CH11S      ;
    uint DFEjST_CH10S      ;
    uint DFEjST_CH9S       ;
    uint DFEjST_CH8S       ;
    uint DFEjST_CH7S       ;
    uint DFEjST_CH6S       ;
    uint DFEjST_CH5S       ;
    uint DFEjST_CH4S       ;
    uint DFEjST_CH3S       ;
    uint DFEjST_CH2S       ;
    uint DFEjST_CH1S       ;
    uint DFEjST_CH0S       ;
    uint DFEjPITRG1_PITMTRG5;
    uint DFEjPITRG1_PITMTRG4;
    uint DFEjMITRG1_MITMTRG5;
    uint DFEjMITRG1_MITMTRG4;
    uint DFEjFITRG1_FITMTRG5;
    uint DFEjFITRG1_FITMTRG4;
    uint DFEjPITRG_PITMTRG3;
    uint DFEjPITRG_PITMTRG2;
    uint DFEjPITRG_PITMTRG1;
    uint DFEjPITRG_PITMTRG0;
    uint DFEjMITRG_MITMTRG3;
    uint DFEjMITRG_MITMTRG2;
    uint DFEjMITRG_MITMTRG1;
    uint DFEjMITRG_MITMTRG0;
    uint DFEjFITRG_FITMTRG3;
    uint DFEjFITRG_FITMTRG2;
    uint DFEjFITRG_FITMTRG1;
    uint DFEjFITRG_FITMTRG0;
    uint DFEjPHUPDCn_PHUPDCH[4];
    uint DFEjPHUPDCn_PH23SL[4];
    uint DFEjPHUPDCn_PH23E [4];
    uint DFEjPHUPDCn_OEPHUPD[4];
    uint DFEjHOLCH0_DFEjHOLCH0;
    uint DFEjHOHCH0_GURD   ;
    uint DFEjHOLCH2_DFEjHOLCH2;
    uint DFEjHOHCH2_GURD   ;
    uint DFEjHOLCH4_DFEjHOLCH4;
    uint DFEjHOHCH4_GURD   ;
    uint DFEjHOLCH6_DFEjHOLCH6;
    uint DFEjHOHCH6_GURD   ;
    uint DFEjHOLCH8_DFEjHOLCH8;
    uint DFEjHOHCH8_GURD   ;
    uint DFEjHOLCH10_DFEjHOLCH10;
    uint DFEjHOHCH10_GURD  ;
    uint DFEjHOLMCH0_DFEjHOLMCH0;
    uint DFEjHOLMCH2_DFEjHOLMCH2;
    uint DFEjHOLMCH4_DFEjHOLMCH4;
    uint DFEjHOLMCH6_DFEjHOLMCH6;
    uint DFEjHOLMCH8_DFEjHOLMCH8;
    uint DFEjHOLMCH10_DFEjHOLMCH10;
    uint DFEjGAINCHn_GAIN3 [12];
    uint DFEjGAINCHn_GAIN2 [12];
    uint DFEjTMTRGCHn_PMT  [12];
    uint DFEjTMTRGCHn_PT   [12];
    uint DFEjTMTRGCHn_AT   [12];
    uint DFEjTMTRGCHn_FT   [12];
    uint DFEjCPOFSTn_DFEjCPOFSTn[3];
    uint DFEjPH23CCTL0_CHS ;
    uint DFEjPH23CCTL0_PFMT;
    uint DFEjPH23CCTL0_PEN ;
    uint DFEjPH2CTL0_OFSL  ;
    uint DFEjPH2CTL0_PH2SLB2;
    uint DFEjPH2CTL0_PHPS  ;
    uint DFEjPH2CTL0_CN2SLB2;
    uint DFEjPH3CTL0_OFSL  ;
    uint DFEjPH3CTL0_PH3SLB2;
    uint DFEjPH3CTL0_PHPS  ;
    uint DFEjPH3CTL0_CN3SLB2;
    uint DFEjPH20_DFEjPH20 ;
    uint DFEjPH30_DFEjPH30 ;
    uint DFEjPH2IND0_PH2IOW;
    uint DFEjPH2IND0_PH2IOF;
    uint DFEjPH2IND0_PH2IND;
    uint DFEjPH3IND0_PH3IOW;
    uint DFEjPH3IND0_PH3IOF;
    uint DFEjPH3IND0_PH3IND;
    uint DFEjSUBCTLCHn_CATAG[3];
    uint DFEjSUBCTLCHn_CAEN[3];
    uint DFEjSUBCTLCHn_MINCH[3];
    uint DFEjSUBCTLCHn_SUBCH[3];
    uint DFEjSUBCTLCHn_SFMT[3];
    uint DFEjSUBCTLCHn_SIEE[3];
    uint DFEjSUBCTLCHn_SIEO[3];
    uint DFEjSUBCTLCHn_SEN [3];
    uint DFEjSUBDOCHn_DFEjSUBDOCHn[3];
    uint DFEjSUBSTCHn_SDOEN[3];
    uint DFEjSUBSTCHn_MINF [3];
    uint DFEjSUBSTCHn_SUBF [3];
    uint DFEjSUBSTCHn_SCER [3];
    uint DFEjSUBSTCHn_SGER [3];
    uint DFEjSUBSTCHn_SDOOW[3];
    uint DFEjSUBCLRSTCHn_CLRSDOEN[3];
    uint DFEjSUBCLRSTCHn_CLRSCER[3];
    uint DFEjSUBCLRSTCHn_CLRSGER[3];
    uint DFEjSUBCLRSTCHn_CLRSDOOW[3];
    uint DFEjSUBERMCHn_MSKSCER[3];
    uint DFEjSUBERMCHn_MSKSGER[3];
    uint DFEjSUBERMCHn_MSKSDOOW[3];
    uint DFEjSUBTRGCHn_SBFE[3];
    uint DFEjSUBTRGCHn_SBE [3];
    uint DFEjSUBTRGCHn_SBT [3];
    uint DFEjSUBTRHCHn_SITS[3];
    uint DFEjSUBTRHCHn_SETS[3];
    uint DFEjSUBTRG0_SUBTMTRG2;
    uint DFEjSUBTRG0_SUBTMTRG1;
    uint DFEjSUBTRG0_SUBTMTRG0;
    uint DFEjCAPCTLCHn_CAPCH[3];
    uint DFEjCAPCTLCHn_CIEE[3];
    uint DFEjCAPCTLCHn_CEN [3];
    uint DFEjCAPDOCHn_DFEjCAPDOCHn[3];
    uint DFEjCAPSTCHn_CDOEN[3];
    uint DFEjCAPSTCHn_CDOOW[3];
    uint DFEjCAPCLRSTCHn_CLRCDOEN[3];
    uint DFEjCAPCLRSTCHn_CLRCDOOW[3];
    uint DFEjCAPERMCHn_MSKCDOOW[3];

    void EnableReset(const bool is_active);
    uint bit_select(cuint val, cuint start, cuint end);
    bool reg_wr(cuint addr, const unsigned char *p_data, cuint size);
    bool reg_rd(cuint addr, unsigned char *p_data, cuint size);
    bool reg_wr_dbg(cuint addr, const unsigned char *p_data, cuint size);
    bool reg_rd_dbg(cuint addr, unsigned char *p_data, cuint size);
    std::string reg_handle_command(const std::vector<std::string>& args);
    int get_reg_index(cuint addr);
    vpcl::re_register *first_reg_object();
    vpcl::re_register *next_reg_object();

    void wr_cb(cuint addr, uint data);
    uint rd_cb(cuint addr);

    virtual void cb_DFEjCTLACHn_EN(RegCBstr str) = 0;
    virtual void cb_DFEjCTLBCHn_PRCSA(RegCBstr str) = 0;
    virtual void cb_DFEjDOCHn_DFEjDOCHn(RegCBstr str) = 0;
    virtual void cb_DFEjPHINDCHn_PHIOF(RegCBstr str) = 0;
    virtual void cb_DFEjCLRSTCHn_CLRDIOW(RegCBstr str) = 0;
    virtual void cb_DFEjDI_DI(RegCBstr str) = 0;
    virtual void cb_DFEjTRG_TRGA(RegCBstr str) = 0;
    virtual void cb_DFEjHOLCH0_DFEjHOLCH0(RegCBstr str) = 0;
    virtual void cb_DFEjHOHCH0_GURD(RegCBstr str) = 0;
    virtual void cb_DFEjHOLCH2_DFEjHOLCH2(RegCBstr str) = 0;
    virtual void cb_DFEjHOHCH2_GURD(RegCBstr str) = 0;
    virtual void cb_DFEjHOLCH4_DFEjHOLCH4(RegCBstr str) = 0;
    virtual void cb_DFEjHOHCH4_GURD(RegCBstr str) = 0;
    virtual void cb_DFEjHOLCH6_DFEjHOLCH6(RegCBstr str) = 0;
    virtual void cb_DFEjHOHCH6_GURD(RegCBstr str) = 0;
    virtual void cb_DFEjHOLCH8_DFEjHOLCH8(RegCBstr str) = 0;
    virtual void cb_DFEjHOHCH8_GURD(RegCBstr str) = 0;
    virtual void cb_DFEjHOLCH10_DFEjHOLCH10(RegCBstr str) = 0;
    virtual void cb_DFEjHOHCH10_GURD(RegCBstr str) = 0;
    virtual void cb_DFEjPH23CCTL0_PEN(RegCBstr str) = 0;
    virtual void cb_DFEjPH2CTL0_CN2SLB2(RegCBstr str) = 0;
    virtual void cb_DFEjPH3CTL0_CN3SLB2(RegCBstr str) = 0;
    virtual void cb_DFEjSUBCTLCHn_SEN(RegCBstr str) = 0;
    virtual void cb_DFEjSUBDOCHn_DFEjSUBDOCHn(RegCBstr str) = 0;
    virtual void cb_DFEjSUBCLRSTCHn_CLRSDOOW(RegCBstr str) = 0;
    virtual void cb_DFEjSUBTRGCHn_SBT(RegCBstr str) = 0;
    virtual void cb_DFEjCAPCTLCHn_CEN(RegCBstr str) = 0;
    virtual void cb_DFEjCAPDOCHn_DFEjCAPDOCHn(RegCBstr str) = 0;
    virtual void cb_DFEjCAPCLRSTCHn_CLRCDOOW(RegCBstr str) = 0;

    void set_instance_name(std::string InstName);

    uint mBusByteWidth;
    uint mBusWidth;
    bool mIsReset;
    bool mDumpRegisterRW;
    std::map<std::string, bool> mMessageLevel;
    std::map<std::string, std::map<std::string, void (Cdfe_regif::*) (RegCBstr)> > mWrCbAPI;
    std::map<std::string, std::map<std::string, void (Cdfe_regif::*) (RegCBstr)> > mRdCbAPI;
    std::string mFileName;
    std::string mInstName;
    int mLineNum;

    bool reg_wr_process(cuint addr, const unsigned char *p_data, cuint size, bool IsDbgFunc);
    bool reg_rd_process(cuint addr, unsigned char *p_data, cuint size, bool IsDbgFunc);
    bool reg_wr_func(cuint addr, const unsigned char *p_data, cuint size, cuint reg_index, bool IsDbgFunc);
    bool reg_rd_func(cuint addr, unsigned char *p_data, cuint size, cuint reg_index, bool IsDbgFunc);
    void _re_printf(const std::string msg_level, const char *format, ...);
    void get_fileline(std::string filename, int line_number);
    void CommandInit();
    bool ChkSize(std::string expect_size, cuint detect_size, cuint addr);
    std::vector<std::string> Str2Vec(std::string str, const char sep);
    std::string Num2HexStr(cuint num, cuint num_length, bool space_strip);
    void DumpRegMsg(const std::string operation, const std::string RegName, const std::string BitName, cuint size, cuint addr, cuint wr_data, cuint pre_data, cuint data, cuint reg_length);
    std::string AccessRegCommand(const std::vector<std::string>& args, vpcl::re_register *Register, bool &BlockReg);
    void InitLocalVal();
    void UpdateLocalVal(cuint addr);
    void UpdateRegVal(cuint addr);

    #ifdef CWR_SYSTEMC
    uint cw_rd_cb(tlm::tlm_generic_payload& trans, int tag);
    uint cw_wr_cb(tlm::tlm_generic_payload& trans, int tag);
    void cw_instantiate_reg(scml2::reg<uint> * reg, std::string reg_name, int offset);
    #endif
};
#endif //__DFE_REG_DEF_H__
